# 03 - Grievance Status Analysis

Two parallel status views are used throughout:

* **`status_group`** -- four buckets used for all count / volume breakdowns:
  Discard, Disposed with Benefit, Disposed, Open.
* **`status_bucket`** -- four buckets used for disposal-time statistics:
  Discard, Disposed with Benefit, Disposed, In Follow Up with close

Breakdowns produced for both views:
yearly, district, office, department, category, subcategory.

Shared scaffolding lives in `grievance_common.py`.

## Setup

In [1]:
import numpy as np
import pandas as pd

from grievance_common import (
    load_complaints, add_time_fields, filter_window, compute_disposal_days,
    clean_series, status_bucket, status_group, OUTPUT_DIR, FOCUS_YEAR, VALID_YEARS,
)

In [2]:
import importlib
import grievance_common
importlib.reload(grievance_common)
from grievance_common import *

## Data Load and Preparation

`df_filtered` is the windowed complaints frame with the four-way
`status_group` (Discard / Disposed with Benefit / Disposed / Open) attached.
`df_res` is the same frame with `disposal_days` computed (negatives
dropped) and the four-way `status_bucket` (Discard / Disposed with Benefit /
Disposed / In Follow Up) attached -- this is the frame used for
disposal-time stats.

In [3]:
df = add_time_fields(load_complaints())

# Volume view: status_group (Discard / Disposed with Benefit / Disposed / Open)
df_filtered = filter_window(df)
df_filtered["status_group"] = status_group(
    df_filtered["status"], df_filtered["benefitted"])

# Resolution view: status_bucket (Discard / Disposed with Benefit / Disposed
# / In Follow Up With Close). disposal_days computed; negatives dropped.
df_res = filter_window(compute_disposal_days(df, drop_negative=True))
df_res["status_bucket"] = status_bucket(
    df_res["status"], df_res["benefitted"])

print(f"Volume frame   (df_filtered): {len(df_filtered):,} rows")
print(f"Resolution frm (df_res)     : {len(df_res):,} rows")
print("\nstatus_group value counts (df_filtered):")
print(df_filtered["status_group"].value_counts())
print("\nstatus_bucket value counts (df_res):")
print(df_res["status_bucket"].value_counts())

Volume frame   (df_filtered): 1,323,840 rows
Resolution frm (df_res)     : 1,323,827 rows

status_group value counts (df_filtered):
status_group
Disposed                 911613
Discard                  187891
Open                     132560
Disposed with Benefit     91776
Name: count, dtype: int64

status_bucket value counts (df_res):
status_bucket
Disposed                   911600
Discard                    187891
Disposed with Benefit       91776
In Follow Up With Close        81
Name: count, dtype: int64

## Helper Functions

Two helpers that produce a `level x status` pivot table -- one for counts
(any year, with within-level percentages) and one for disposal-time stats
(mean / median days). Reused across every breakdown below.

In [4]:
STATUS_GROUP_ORDER  = ["Discard", "Disposed with Benefit", "Disposed", "Open"]
STATUS_BUCKET_ORDER = ["Discard", "Disposed with Benefit", "Disposed",
                       "In Follow Up With Close"]
YEAR_ORDER = VALID_YEARS + ["Aggregate"]


def _add_aggregate(df, year_col="custom_year"):
    """Append a copy of `df` with year set to 'Aggregate'."""
    agg = df.copy()
    agg[year_col] = "Aggregate"
    return pd.concat([df, agg], ignore_index=True)


def status_count_pivot(data, level_col,
                       status_col="status_group",
                       status_order=STATUS_GROUP_ORDER,
                       ticket_col="ticket_no",
                       year_col="custom_year"):
    """level x (year x status -> count, percentage).

    When level_col IS the year column the yearly breakdown is returned
    directly (no nested year grouping). Otherwise columns are grouped by
    year first (including an 'Aggregate' group spanning all years) and
    then by status, so you see both the overall picture and each year
    side by side.

    Percentage = share of that status within (level, year).
    """
    d = data.copy()
    d[level_col] = clean_series(d[level_col])

    is_yearly = (level_col == year_col)

    if is_yearly:
        # Simple: aggregate only needs the one Aggregate row appended.
        d = _add_aggregate(d, year_col)
        long = (
            d.groupby([level_col, status_col])[ticket_col]
             .nunique().reset_index(name="count")
        )
        long["denom"] = (long.groupby(level_col)["count"].transform("sum"))
        long["percentage"] = (long["count"] / long["denom"] * 100).round(2)
        long = long.drop(columns="denom")

        pivot = (
            long.pivot(index=level_col, columns=status_col,
                       values=["count", "percentage"])
                .swaplevel(0, 1, axis=1).sort_index(axis=1).fillna(0)
        )
        ordered = [(s, m) for s in status_order
                   for m in ("count", "percentage")
                   if (s, m) in pivot.columns]
        return pivot.reindex(
            columns=pd.MultiIndex.from_tuples(ordered))

    # Non-yearly: group by (level, year, status) — with Aggregate appended.
    d = _add_aggregate(d, year_col)
    long = (
        d.groupby([level_col, year_col, status_col])[ticket_col]
         .nunique().reset_index(name="count")
    )
    long["denom"] = (long.groupby([level_col, year_col])["count"]
                         .transform("sum"))
    long["percentage"] = (long["count"] / long["denom"] * 100).round(2)
    long = long.drop(columns="denom")

    pivot = long.pivot_table(
        index=level_col,
        columns=[year_col, status_col],
        values=["count", "percentage"],
        aggfunc="sum"
    )
    # Flatten MultiIndex from (metric, year, status) -> (year, status, metric)
    pivot.columns = pd.MultiIndex.from_tuples(
        [(yr, st, m) for m, yr, st in pivot.columns]
    )
    ordered = [
        (yr, st, m)
        for yr in YEAR_ORDER
        for st in status_order
        for m in ("count", "percentage")
        if (yr, st, m) in pivot.columns
    ]
    return pivot.reindex(
        columns=pd.MultiIndex.from_tuples(ordered)).fillna(0)


def disposal_time_pivot(data, level_col,
                        status_col="status_bucket",
                        status_order=STATUS_BUCKET_ORDER,
                        ticket_col="ticket_no",
                        year_col="custom_year"):
    """level x (year x status -> count, %, mean days, median days).

    Same aggregate + year-wise layout as status_count_pivot.
    """
    d = data.copy()
    d[level_col] = clean_series(d[level_col])

    is_yearly = (level_col == year_col)

    if is_yearly:
        d = _add_aggregate(d, year_col)
        agg = (
            d.groupby([level_col, status_col])
             .agg(count=(ticket_col, "nunique"),
                  mean=("disposal_days", "mean"),
                  median=("disposal_days", "median"))
             .reset_index()
        )
        agg[["mean", "median"]] = agg[["mean", "median"]].round(0)
        agg["denom"] = agg.groupby(level_col)["count"].transform("sum")
        agg["percentage"] = (agg["count"] / agg["denom"] * 100).round(2)
        agg = agg.drop(columns="denom")

        pivot = (
            agg.pivot(index=level_col, columns=status_col,
                      values=["count", "percentage", "mean", "median"])
               .swaplevel(0, 1, axis=1).sort_index(axis=1).fillna(0)
        )
        metrics = ["count", "percentage", "mean", "median"]
        ordered = [(s, m) for s in status_order for m in metrics
                   if (s, m) in pivot.columns]
        return pivot.reindex(columns=pd.MultiIndex.from_tuples(ordered))

    d = _add_aggregate(d, year_col)
    agg = (
        d.groupby([level_col, year_col, status_col])
         .agg(count=(ticket_col, "nunique"),
              mean=("disposal_days", "mean"),
              median=("disposal_days", "median"))
         .reset_index()
    )
    agg[["mean", "median"]] = agg[["mean", "median"]].round(0)
    agg["denom"] = (agg.groupby([level_col, year_col])["count"]
                       .transform("sum"))
    agg["percentage"] = (agg["count"] / agg["denom"] * 100).round(2)
    agg = agg.drop(columns="denom")

    pivot = agg.pivot_table(
        index=level_col,
        columns=[year_col, status_col],
        values=["count", "percentage", "mean", "median"],
        aggfunc="sum"
    )
    pivot.columns = pd.MultiIndex.from_tuples(
        [(yr, st, m) for m, yr, st in pivot.columns]
    )
    metrics = ["count", "percentage", "mean", "median"]
    ordered = [
        (yr, st, m)
        for yr in YEAR_ORDER
        for st in status_order
        for m in metrics
        if (yr, st, m) in pivot.columns
    ]
    return pivot.reindex(
        columns=pd.MultiIndex.from_tuples(ordered)).fillna(0)

In [16]:
# =============================================================================
# Petitioner-level Helper Function
# =============================================================================
 
def _add_petitioner_id(data):
    """Add petitioner_id (name | district | block) column."""
    d = data.copy()
    for col in ["petitioner_name", "district", "block"]:
        d[col] = d[col].fillna("NaN").astype(str).str.strip().replace("", "NaN")
    d["petitioner_id"] = (d["petitioner_name"] + " | "
                          + d["district"] + " | " + d["block"])
    return d
 
 
def petitioner_status_count_pivot(data, level_col,
                                  status_col="status_group",
                                  status_order=STATUS_GROUP_ORDER,
                                  year_col="custom_year"):
    """Exactly like status_count_pivot but counts unique petitioners
    instead of unique tickets. Uses petitioner_id as the count column."""
    d = _add_petitioner_id(data)
    return status_count_pivot(d, level_col,
                              status_col=status_col,
                              status_order=status_order,
                              ticket_col="petitioner_id",
                              year_col=year_col)

def petitioner_disposal_time_pivot(data, level_col,
                                   status_col="status_bucket",
                                   status_order=STATUS_BUCKET_ORDER,
                                   year_col="custom_year"):
    """Exactly like disposal_time_pivot but counts unique petitioners
    instead of unique tickets. Uses petitioner_id as the count column."""
    d = _add_petitioner_id(data)
    return disposal_time_pivot(d, level_col,
                               status_col=status_col,
                               status_order=status_order,
                               ticket_col="petitioner_id",
                               year_col=year_col)

In [5]:
pd.set_option("display.max_columns", None)

## 1. Status Group Counts

Count and percentage for the four-way status group (Discard / Disposed with Benefit / Disposed / Open) at each breakdown level. Columns are grouped first by year (plus an **Aggregate** column spanning all years), then by status.

### Yearly

In [6]:
pivot_status_yearly = status_count_pivot(df_filtered, "custom_year")
pivot_status_yearly

              Discard            Disposed with Benefit             Disposed  \
                count percentage                 count percentage     count
custom_year
2021-2022     13061.0      13.29               11613.0      11.82   71583.0
2022-2023     28687.0      15.79               24948.0      13.73  123123.0
2023-2024     39315.0      11.06               30033.0       8.45  267822.0
2024-2025    106828.0      15.52               25182.0       3.66  449085.0
Aggregate    187891.0      14.19               91776.0       6.93  911613.0

                            Open
            percentage     count percentage
custom_year
2021-2022        72.85    2001.0       2.04
2022-2023        67.76    4944.0       2.72
2023-2024        75.32   18409.0       5.18
2024-2025        65.25  107206.0      15.58
Aggregate        68.86  132560.0      10.01

### District

In [14]:
pivot_status_district = status_count_pivot(df_filtered, "district")
pivot_status_district

               2021-2022                                                       \
                 Discard            Disposed with Benefit            Disposed
                   count percentage                 count percentage    count
district
Angul                476      17.25                   245       8.88     2011
Balangir             458      11.19                   958      23.40     2622
Baleswar            1171      15.11                   348       4.49     6084
Bargarh              537      15.67                   247       7.21     2602
Bhadrak              649      13.13                   242       4.90     3830
Boudh                191      24.55                   103      13.24      478
Cuttack              689      16.06                   430      10.02     3078
Deogarh               70      11.78                    38       6.40      485
Dhenkanal            992      22.91                   140       3.23     3175
Gajapati             137       9.62                    66       4.63     1206
Ganjam               719      14.35                   508      10.14     3736
Jagatsinghapur       323       9.88                   152       4.65     2765
Jajpur              1126      18.64                   228       3.77     4032
Jharsuguda           118      15.90                    87      11.73      509
Kalahandi            917       9.75                   652       6.93     7818
Kandhamal            208       8.51                   348      14.24     1859
Kendrapara           432       8.91                   274       5.65     4099
Kendujhar            198       9.51                   179       8.60     1642
Khordha             1087      13.56                  2855      35.62     3939
Koraput              212      15.45                   192      13.99      951
Malkangiri            80      16.95                    90      19.07      293
Mayurbhanj           236       8.39                  1223      43.49     1309
NaN                  140       3.62                   603      15.57     3042
Nabarangpur          121      11.77                   106      10.31      798
Nayagarh             297      12.07                   198       8.05     1953
Nuapada              116       9.29                    95       7.61     1025
Puri                 452      14.15                   350      10.95     2331
Rayagada             159      13.58                   148      12.64      842
Sambalpur            274      17.42                   136       8.65     1136
Subarnapur           182      14.44                   223      17.70      840
Sundargarh           294      18.97                   149       9.61     1093

                                           2022-2023             \
                           Open              Discard
               percentage count percentage     count percentage
district
Angul               72.89    27       0.98       651      17.84
Balangir            64.04    56       1.37      1990      16.01
Baleswar            78.51   146       1.88      3255      20.55
Bargarh             75.95    40       1.17       736      16.28
Bhadrak             77.48   222       4.49      1179      14.18
Boudh               61.44     6       0.77       597      13.93
Cuttack             71.73    94       2.19      1272      16.75
Deogarh             81.65     1       0.17       115      12.18
Dhenkanal           73.33    23       0.53      1960      33.48
Gajapati            84.69    15       1.05       562      14.06
Ganjam              74.57    47       0.94      2042      16.18
Jagatsinghapur      84.61    28       0.86       555       6.96
Jajpur              66.73   656      10.86      2347      23.74
Jharsuguda          68.60    28       3.77       312      24.30
Kalahandi           83.12    19       0.20      1364      10.38
Kandhamal           76.06    29       1.19       309      13.08
Kendrapara          84.59    41       0.85      1228      16.00
Kendujhar           78.87    63       3.03       730      18.53
Khordha             49.14   135       1.68      2119      20.78
Koraput             69.31    17       1.24       443      19.93
Malkangiri          62.08     9       1.91       100      20.24
Mayurbhanj          46.55    44       1.56       555       8.13
NaN                 78.56    87       2.25       123      20.53
Nabarangpur         77.63     3       0.29       233       7.02
Nayagarh            79.39    12       0.49       863      13.39
Nuapada             82.07    13       1.04       236       7.28
Puri                72.96    62       1.94       926      10.84
Rayagada            71.90    22       1.88       323      12.97
Sambalpur           72.22    27       1.72       452      17.91
Subarnapur          66.67    15       1.19       314      11.80
Sundargarh          70.52    14       0.90       796      13.66

                                                                           \
               Disposed with Benefit            Disposed             Open
                               count percentage    count percentage count
district
Angul                            316       8.66     2594      71.09    88
Balangir                        5473      44.04     4822      38.80   143
Baleswar                         532       3.36    11469      72.41   584
Bargarh                          344       7.61     3371      74.56    70
Bhadrak                          378       4.55     6533      78.60   222
Boudh                            821      19.16     2828      65.98    40
Cuttack                          698       9.19     5379      70.85   243
Deogarh                           38       4.03      783      82.94     8
Dhenkanal                        433       7.40     3354      57.28   108
Gajapati                         120       3.00     3234      80.93    80
Ganjam                           853       6.76     9569      75.80   160
Jagatsinghapur                   266       3.33     7063      88.52    95
Jajpur                           538       5.44     5764      58.31  1236
Jharsuguda                       109       8.49      834      64.95    29
Kalahandi                       3905      29.73     7778      59.21    90
Kandhamal                        490      20.75     1492      63.17    71
Kendrapara                       695       9.06     5576      72.67   174
Kendujhar                        212       5.38     2793      70.91   204
Khordha                         1817      17.82     5696      55.85   566
Koraput                          353      15.88     1369      61.58    58
Malkangiri                        48       9.72      342      69.23     4
Mayurbhanj                      4615      67.61     1521      22.28   135
NaN                               63      10.52      382      63.77    31
Nabarangpur                      138       4.16     2912      87.74    36
Nayagarh                         236       3.66     5289      82.05    58
Nuapada                          102       3.15     2851      87.91    54
Puri                             423       4.95     7040      82.42   153
Rayagada                         327      13.13     1775      71.26    66
Sambalpur                        247       9.79     1776      70.36    49
Subarnapur                       148       5.56     2155      80.95    45
Sundargarh                       210       3.60     4779      81.99    44

                          2023-2024                                   \
                            Discard            Disposed with Benefit
               percentage     count percentage                 count
district
Angul                2.41      1040      11.95                   353
Balangir             1.15      2298       9.09                  1948
Baleswar             3.69      4074      18.41                   887
Bargarh              1.55      1011       9.85                   258
Bhadrak              2.67      1705      11.96                   745
Boudh                0.93       354       8.03                   252
Cuttack              3.20      1988      14.38                  1887
Deogarh              0.85       177       5.73                   302
Dhenkanal            1.84      3586      22.47                  1243
Gajapati             2.00       391       6.58                   205
Ganjam               1.27      2807      11.54                   682
Jagatsinghapur       1.19       650       7.47                   264
Jajpur              12.50      1921      15.00                   564
Jharsuguda           2.26       587      13.50                   128
Kalahandi            0.69      1560       7.08                  3720
Kandhamal            3.01       379       6.98                   638
Kendrapara           2.27      1560      18.81                   969
Kendujhar            5.18      1196       8.10                   298
Khordha              5.55      2132      13.31                  2514
Koraput              2.61       796      12.02                   984
Malkangiri           0.81       166       8.03                   400
Mayurbhanj           1.98      1410       7.88                  6627
NaN                  5.18       460      39.86                    48
Nabarangpur          1.08       762      12.19                   877
Nayagarh             0.90       758       9.02                   173
Nuapada              1.67       397       4.72                   385
Puri                 1.79      1216      10.89                   726
Rayagada             2.65       802      20.39                    80
Sambalpur            1.94      1046       4.60                   421
Subarnapur           1.69       661      13.01                    92
Sundargarh           0.75      1425       6.68                  1363

                                                               2024-2025  \
                          Disposed             Open              Discard
               percentage    count percentage count percentage     count
district
Angul                4.06     6794      78.07   516       5.93      2292
Balangir             7.71    20003      79.14  1026       4.06      5068
Baleswar             4.01    14156      63.96  3017      13.63      4340
Bargarh              2.51     8712      84.88   283       2.76      1434
Bhadrak              5.23    10963      76.90   843       5.91      3280
Boudh                5.72     3443      78.14   357       8.10       760
Cuttack             13.65     8995      65.05   958       6.93      3701
Deogarh              9.77     2578      83.40    34       1.10       495
Dhenkanal            7.79    10767      67.46   364       2.28      6382
Gajapati             3.45     5131      86.41   211       3.55      1000
Ganjam               2.80    20160      82.90   670       2.76      6611
Jagatsinghapur       3.04     7249      83.34   535       6.15      2147
Jajpur               4.40     8570      66.92  1752      13.68      5693
Jharsuguda           2.94     3553      81.73    79       1.82       887
Kalahandi           16.88    16312      74.03   442       2.01      3817
Kandhamal           11.74     4210      77.49   206       3.79       720
Kendrapara          11.69     5029      60.65   734       8.85      3380
Kendujhar            2.02    12645      85.69   618       4.19      2179
Khordha             15.70     9950      62.13  1418       8.85      4688
Koraput             14.86     4564      68.91   279       4.21       820
Malkangiri          19.35     1437      69.52    64       3.10       284
Mayurbhanj          37.05     9242      51.66   610       3.41      2036
NaN                  4.16      458      39.69   188      16.29       674
Nabarangpur         14.03     4021      64.33   591       9.45      1250
Nayagarh             2.06     7203      85.73   268       3.19     15620
Nuapada              4.58     6968      82.87   658       7.83       672
Puri                 6.50     8515      76.27   708       6.34      2719
Rayagada             2.03     2926      74.38   126       3.20      1349
Sambalpur            1.85    20898      91.98   356       1.57     20164
Subarnapur           1.81     4204      82.76   123       2.42      1133
Sundargarh           6.39    18166      85.17   375       1.76      1233

                                                                     \
                          Disposed with Benefit            Disposed
               percentage                 count percentage    count
district
Angul               11.39                   334       1.66    14163
Balangir            18.32                   295       1.07    17427
Baleswar            12.70                   886       2.59    19674
Bargarh              6.09                   303       1.29    19463
Bhadrak              8.75                  1642       4.38    25405
Boudh                9.59                   292       3.69     4908
Cuttack              9.85                  1263       3.36    26444
Deogarh              6.72                    95       1.29     5866
Dhenkanal           21.73                   633       2.16    18353
Gajapati            11.33                    94       1.06     6375
Ganjam              12.55                   923       1.75    40932
Jagatsinghapur       9.86                   398       1.83    16005
Jajpur              15.00                   667       1.76    24790
Jharsuguda          15.46                    89       1.55     3899
Kalahandi           13.41                  1391       4.89    20834
Kandhamal            6.16                   488       4.17     8818
Kendrapara          13.62                   738       2.97    15625
Kendujhar            9.58                   434       1.91    15886
Khordha             12.24                  1241       3.24    24122
Koraput              8.01                   321       3.14     7551
Malkangiri           4.66                   119       1.95     5145
Mayurbhanj           8.15                  8593      34.41    11361
NaN                 31.90                    69       3.27      644
Nabarangpur         10.73                   183       1.57     8901
Nayagarh            49.54                   601       1.91    10481
Nuapada              5.58                   430       3.57     8177
Puri                 9.92                   601       2.19    19267
Rayagada            19.72                   127       1.86     4464
Sambalpur           41.98                  1482       3.09    22111
Subarnapur           7.14                   172       1.08    11977
Sundargarh           9.26                   278       2.09    10017

                                           Aggregate             \
                           Open              Discard
               percentage count percentage     count percentage
district
Angul               70.41  3326      16.53      4459      12.66
Balangir            62.99  4875      17.62      9814      14.13
Baleswar            57.55  9284      27.16     12840      16.07
Bargarh             82.61  2359      10.01      3718       8.90
Bhadrak             67.77  7158      19.10      6813      10.48
Boudh               61.95  1963      24.78      1902      10.94
Cuttack             70.37  6169      16.42      7650      12.09
Deogarh             79.69   905      12.29       857       7.15
Dhenkanal           62.49  4002      13.63     12920      23.27
Gajapati            72.20  1361      15.41      2090      10.35
Ganjam              77.72  4201       7.98     12179      12.87
Jagatsinghapur      73.48  3231      14.83      3675       8.81
Jajpur              65.34  6792      17.90     11087      16.63
Jharsuguda          67.94   864      15.05      1904      15.72
Kalahandi           73.18  2429       8.53      7658      10.48
Kandhamal           75.39  1670      14.28      1616       7.37
Kendrapara          62.95  5080      20.46      6600      14.46
Kendujhar           69.81  4257      18.71      4303       9.88
Khordha             62.99  8242      21.52     10026      13.82
Koraput             73.79  1541      15.06      2271      11.10
Malkangiri          84.48   542       8.90       630       6.91
Mayurbhanj          45.49  2984      11.95      4237       8.07
NaN                 30.48   726      34.36      1397      18.05
Nabarangpur         76.38  1320      11.33      2366      10.63
Nayagarh            33.24  4825      15.30     17538      35.91
Nuapada             67.95  2755      22.89      1421       5.70
Puri                70.32  4813      17.57      5313      10.56
Rayagada            65.26   900      13.16      2633      18.24
Sambalpur           46.04  4272       8.89     21936      29.31
Subarnapur          75.51  2579      16.26      2290       9.21
Sundargarh          75.26  1781      13.38      3748       8.92

                                                                            \
               Disposed with Benefit            Disposed              Open
                               count percentage    count percentage  count
district
Angul                           1248       3.54    25562      72.57   3957
Balangir                        8674      12.49    44874      64.60   6100
Baleswar                        2653       3.32    51383      64.30  13031
Bargarh                         1152       2.76    34148      81.75   2752
Bhadrak                         3007       4.63    46731      71.90   8445
Boudh                           1468       8.44    11657      67.02   2366
Cuttack                         4278       6.76    43896      69.36   7464
Deogarh                          473       3.94     9712      81.00    948
Dhenkanal                       2449       4.41    35649      64.22   4497
Gajapati                         485       2.40    15946      78.99   1667
Ganjam                          2966       3.13    74397      78.63   5078
Jagatsinghapur                  1080       2.59    33082      79.28   3889
Jajpur                          1997       3.00    43156      64.72  10436
Jharsuguda                       413       3.41     8795      72.61   1000
Kalahandi                       9668      13.24    52742      72.20   2980
Kandhamal                       1964       8.95    16379      74.67   1976
Kendrapara                      2676       5.86    30329      66.46   6029
Kendujhar                       1123       2.58    32966      75.72   5142
Khordha                         8427      11.62    43707      60.27  10361
Koraput                         1850       9.05    14435      70.58   1895
Malkangiri                       657       7.20     7217      79.11    619
Mayurbhanj                     21058      40.11    23433      44.63   3773
NaN                              783      10.12     4526      58.49   1032
Nabarangpur                     1304       5.86    16632      74.74   1950
Nayagarh                        1208       2.47    24926      51.04   5163
Nuapada                         1012       4.06    19021      76.29   3480
Puri                            2100       4.17    37153      73.86   5736
Rayagada                         682       4.72    10007      69.32   1114
Sambalpur                       2286       3.05    45921      61.35   4704
Subarnapur                       635       2.55    19176      77.13   2762
Sundargarh                      2000       4.76    34055      81.05   2214



               percentage
district
Angul               11.23
Balangir             8.78
Baleswar            16.31
Bargarh              6.59
Bhadrak             12.99
Boudh               13.60
Cuttack             11.79
Deogarh              7.91
Dhenkanal            8.10
Gajapati             8.26
Ganjam               5.37
Jagatsinghapur       9.32
Jajpur              15.65
Jharsuguda           8.26
Kalahandi            4.08
Kandhamal            9.01
Kendrapara          13.21
Kendujhar           11.81
Khordha             14.29
Koraput              9.27
Malkangiri           6.79
Mayurbhanj           7.19
NaN                 13.34
Nabarangpur          8.76
Nayagarh            10.57

### Office

In [15]:
pivot_status_office = status_count_pivot(df_filtered, "office")
pivot_status_office

                         2021-2022                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary              702.0      25.79                1501.0
Collector                   4442.0      13.53                5305.0
DG & IG Police                83.0       4.07                 110.0
Departments                 3654.0      18.53                2208.0
Governor                     340.0      19.54                   3.0
NaN                          193.0       2.01                1471.0
Office of Chief Minister    3092.0      13.23                 780.0
Superintendent of Police     555.0       8.94                 235.0

                                                                           \
                                    Disposed              Open
                         percentage    count percentage  count percentage
office
Chief Secretary               55.14    454.0      16.68   65.0       2.39
Collector                     16.16  22910.0      69.78  176.0       0.54
DG & IG Police                 5.40   1817.0      89.16   28.0       1.37
Departments                   11.20  13532.0      68.61  329.0       1.67
Governor                       0.17   1358.0      78.05   39.0       2.24
NaN                           15.29   7729.0      80.32  230.0       2.39
Office of Chief Minister       3.34  19222.0      82.26  274.0       1.17
Superintendent of Police       3.78   4561.0      73.43  860.0      13.85

                         2022-2023                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary             1737.0      27.53                3814.0
Collector                  10746.0      12.78               15733.0
DG & IG Police               224.0       5.83                   0.0
Departments                 6748.0      19.94                1767.0
Governor                     580.0      28.40                   0.0
NaN                          167.0       1.60                1380.0
Office of Chief Minister    7836.0      24.56                1283.0
Superintendent of Police     649.0       7.02                 971.0

                                                                            \
                                    Disposed               Open
                         percentage    count percentage   count percentage
office
Chief Secretary               60.45    515.0       8.16   243.0       3.85
Collector                     18.71  56507.0      67.21  1085.0       1.29
DG & IG Police                 0.00   3514.0      91.53   101.0       2.63
Departments                    5.22  24299.0      71.79  1033.0       3.05
Governor                       0.00   1390.0      68.07    72.0       3.53
NaN                           13.22   8340.0      79.90   551.0       5.28
Office of Chief Minister       4.02  22326.0      69.97   462.0       1.45
Superintendent of Police      10.50   6232.0      67.38  1397.0      15.10

                         2023-2024                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary             3353.0      37.03                5003.0
Collector                  13928.0       6.23               20316.0
DG & IG Police               378.0       5.49                   1.0
Departments                12830.0      24.03                1126.0
Governor                     728.0      22.53                   2.0
NaN                          145.0       1.41                1895.0
Office of Chief Minister    6842.0      16.69                 819.0
Superintendent of Police    1111.0      13.38                 871.0

                                                                             \
                                     Disposed               Open
                         percentage     count percentage   count percentage
office
Chief Secretary               55.25      62.0       0.68   638.0       7.05
Collector                      9.09  183662.0      82.20  5531.0       2.48
DG & IG Police                 0.01    3484.0      50.65  3016.0      43.84
Departments                    2.11   36157.0      67.72  3277.0       6.14
Governor                       0.06    2201.0      68.12   300.0       9.29
NaN                           18.41    6444.0      62.59  1812.0      17.60
Office of Chief Minister       2.00   31367.0      76.53  1959.0       4.78
Superintendent of Police      10.49    4445.0      53.53  1876.0      22.59

                         2024-2025                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary             4405.0      31.99                7162.0
Collector                  34904.0      10.28               10632.0
DG & IG Police              2741.0      18.38                   6.0
Departments                48131.0      29.24                2735.0
Governor                    2022.0      24.37                   1.0
NaN                          164.0       0.79                2421.0
Office of Chief Minister    8655.0       7.90                 327.0
Superintendent of Police    5806.0      34.41                1898.0

                                                                              \
                                     Disposed                Open
                         percentage     count percentage    count percentage
office
Chief Secretary               52.02     295.0       2.14   1907.0      13.85
Collector                      3.13  267539.0      78.82  26340.0       7.76
DG & IG Police                 0.04     986.0       6.61  11178.0      74.96
Departments                    1.66   75873.0      46.10  37841.0      22.99
Governor                       0.01    4640.0      55.92   1634.0      19.69
NaN                           11.61    8815.0      42.28   9449.0      45.32
Office of Chief Minister       0.30   87866.0      80.16  12761.0      11.64
Superintendent of Police      11.25    3071.0      18.20   6096.0      36.13

                         Aggregate                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary            10197.0      32.01               17480.0
Collector                  64020.0       9.42               51986.0
DG & IG Police              3426.0      12.38                 117.0
Departments                71363.0      26.28                7836.0
Governor                    3670.0      23.97                   6.0
NaN                          669.0       1.31                7167.0
Office of Chief Minister   26425.0      12.84                3209.0
Superintendent of Police    8121.0      19.99                3975.0


                                     Disposed                Open
                         percentage     count percentage    count percentage
office
Chief Secretary               54.87    1326.0       4.16   2853.0       8.96
Collector                      7.65  530618.0      78.06  33132.0       4.87
DG & IG Police                 0.42    9801.0      35.42  14323.0      51.77
Departments                    2.89  149861.0      55.19  42480.0      15.64
Governor                       0.04    9589.0      62.63   2045.0      13.36
NaN                           14.00   31328.0      61.18  12042.0      23.52
Office of Chief Minister       1.56  160781.0      78.10  15456.0       7.51
Superintendent of Police       9.78   18309.0      45.06  10229.0      25.17

### Department

In [16]:
pivot_status_dept = status_count_pivot(df_filtered, "dept")
pivot_status_dept

                                                   2021-2022             \
                                                     Discard
                                                       count percentage
dept
Agriculture & Farmers' Empowerment                      75.0       3.47
Co-operation                                             7.0       2.24
Commerce & Transport                                    12.0       3.08
Electronics & Information Technology                     4.0       3.85
Energy                                                  13.0       0.81
Excise                                                   2.0       0.97
Finance                                                 13.0       5.20
Fisheries & Animal Resources Development                 1.0       0.42
Food Supplies & Consumer Welfare                        43.0       1.61
Forest, Environment and Climate Change Department        7.0       2.22
General Administration & Public Grievance              176.0       7.90
Handlooms ,Textiles & Handicrafts                        1.0       3.03
Health & Family Welfare                                 81.0       1.84
Higher Education                                        70.0      12.22
Home department                                        179.0       1.81
Housing & Urban Development                            131.0       1.93
Industries                                               5.0       7.46
Information & Public Relations                          10.0      15.62
Labour & Employees' State Insurance                     12.0       2.61
Law                                                      2.0       1.85
Micro, Small & Medium Enterprise                        13.0      22.03
Mission Shakti                                           0.0       0.00
NaN                                                  11409.0      40.35
Odia Language Literature & Culture                       2.0       1.45
Panchayati Raj & Drinking Water                        289.0       1.36
Parliamentary Affairs                                    0.0       0.00
Planning & Convergence                                   1.0       2.27
Public Enterprises                                       0.0       0.00
Revenue & Disaster Management                          168.0       2.84
Rural Development                                       56.0       8.63
ST & SC Development, Minorities & Backward Clas...      54.0       8.71
School & Mass Education                                 66.0       1.74
Science & Technology                                     0.0       0.00
Skill Development & Technical Education                 10.0       4.26
Social Security & Empowerment of Persons with D...      73.0       3.51
Sports & Youth Services                                  1.0       1.96
Steel & Mines                                            6.0       8.33
Tourism                                                  3.0       7.32
Water Resources                                         15.0       1.92
Women & Child Development                                7.0       0.94
Works                                                   44.0       9.28

                                                                          \
                                                   Disposed with Benefit
                                                                   count
dept
Agriculture & Farmers' Empowerment                                 162.0
Co-operation                                                        19.0
Commerce & Transport                                                31.0
Electronics & Information Technology                                 7.0
Energy                                                             419.0
Excise                                                               5.0
Finance                                                             40.0
Fisheries & Animal Resources Development                            41.0
Food Supplies & Consumer Welfare                                   638.0
Forest, Environment and Climate Change Department                   34.0
General Administration & Public Grievance                          288.0
Handlooms ,Textiles & Handicrafts                                   13.0
Health & Family Welfare                                            544.0
Higher Education                                                    66.0
Home department                                                   1708.0
Housing & Urban Development                                       1114.0
Industries                                                           9.0
Information & Public Relations                                      14.0
Labour & Employees' State Insurance                                 43.0
Law                                                                  8.0
Micro, Small & Medium Enterprise                                     3.0
Mission Shakti                                                       4.0
NaN                                                               1379.0
Odia Language Literature & Culture                                   8.0
Panchayati Raj & Drinking Water                                   2960.0
Parliamentary Affairs                                                1.0
Planning & Convergence                                              14.0
Public Enterprises                                                   1.0
Revenue & Disaster Management                                      929.0
Rural Development                                                   66.0
ST & SC Development, Minorities & Backward Clas...                  65.0
School & Mass Education                                            372.0
Science & Technology                                                 0.0
Skill Development & Technical Education                             30.0
Social Security & Empowerment of Persons with D...                 242.0
Sports & Youth Services                                              4.0
Steel & Mines                                                        2.0
Tourism                                                              9.0
Water Resources                                                    177.0
Women & Child Development                                           50.0
Works                                                               94.0

                                                                        \
                                                              Disposed
                                                   percentage    count
dept
Agriculture & Farmers' Empowerment                       7.50   1911.0
Co-operation                                             6.07    281.0
Commerce & Transport                                     7.95    345.0
Electronics & Information Technology                     6.73     91.0
Energy                                                  26.12   1144.0
Excise                                                   2.42    197.0
Finance                                                 16.00    195.0
Fisheries & Animal Resources Development                17.08    197.0
Food Supplies & Consumer Welfare                        23.86   1983.0
Forest, Environment and Climate Change Department       10.76    272.0
General Administration & Public Grievance               12.92   1728.0
Handlooms ,Textiles & Handicrafts                       39.39     19.0
Health & Family Welfare                                 12.34   3564.0
Higher Education                                        11.52    424.0
Home department                                         17.30   7082.0
Housing & Urban Development                             16.42   5484.0
Industries                                              13.43     52.0
Information & Public Relations                          21.88     40.0
Labour & Employees' State Insurance                      9.37    400.0
Law                                                      7.41     95.0
Micro, Small & Medium Enterprise                         5.08     42.0
Mission Shakti                                           5.26     72.0
NaN                                                      4.88  15296.0
Odia Language Literature & Culture                       5.80    127.0
Panchayati Raj & Drinking Water                         13.88  17903.0
Parliamentary Affairs                                    5.88     16.0
Planning & Convergence                                  31.82     29.0
Public Enterprises                                       8.33     11.0
Revenue & Disaster Management                           15.71   4789.0
Rural Development                                       10.17    514.0
ST & SC Development, Minorities & Backward Clas...      10.48    490.0
School & Mass Education                                  9.80   3151.0
Science & Technology                                     0.00      7.0
Skill Development & Technical Education                 12.77    192.0
Social Security & Empowerment of Persons with D...      11.64   1752.0
Sports & Youth Services                                  7.84     45.0
Steel & Mines                                            2.78     63.0
Tourism                                                 21.95     28.0
Water Resources                                         22.63    554.0
Women & Child Development                                6.74    668.0
Works                                                   19.83    330.0

                                                                      \
                                                                Open
                                                   percentage  count
dept
Agriculture & Farmers' Empowerment                      88.43   13.0
Co-operation                                            89.78    6.0
Commerce & Transport                                    88.46    2.0
Electronics & Information Technology                    87.50    2.0
Energy                                                  71.32   28.0
Excise                                                  95.17    3.0
Finance                                                 78.00    2.0
Fisheries & Animal Resources Development                82.08    1.0
Food Supplies & Consumer Welfare                        74.16   10.0
Forest, Environment and Climate Change Department       86.08    3.0
General Administration & Public Grievance               77.52   37.0
Handlooms ,Textiles & Handicrafts                       57.58    0.0
Health & Family Welfare                                 80.87  218.0
Higher Education                                        74.00   13.0
Home department                                         71.75  901.0
Housing & Urban Development                             80.84   55.0
Industries                                              77.61    1.0
Information & Public Relations                          62.50    0.0
Labour & Employees' State Insurance                     87.15    4.0
Law                                                     87.96    3.0
Micro, Small & Medium Enterprise                        71.19    1.0
Mission Shakti                                          94.74    0.0
NaN                                                     54.10  190.0
Odia Language Literature & Culture                      92.03    1.0
Panchayati Raj & Drinking Water                         83.96  171.0
Parliamentary Affairs                                   94.12    0.0
Planning & Convergence                                  65.91    0.0
Public Enterprises                                      91.67    0.0
Revenue & Disaster Management                           80.96   29.0
Rural Development                                       79.20   13.0
ST & SC Development, Minorities & Backward Clas...      79.03   11.0
School & Mass Education                                 83.05  205.0
Science & Technology                                    87.50    1.0
Skill Development & Technical Education                 81.70    3.0
Social Security & Empowerment of Persons with D...      84.27   12.0
Sports & Youth Services                                 88.24    1.0
Steel & Mines                                           87.50    1.0
Tourism                                                 68.29    1.0
Water Resources                                         70.84   36.0
Women & Child Development                               90.03   17.0
Works                                                   69.62    6.0

                                                              2022-2023  \
                                                                Discard
                                                   percentage     count
dept
Agriculture & Farmers' Empowerment                       0.60      40.0
Co-operation                                             1.92       3.0
Commerce & Transport                                     0.51      11.0
Electronics & Information Technology                     1.92       0.0
Energy                                                   1.75      30.0
Excise                                                   1.45       4.0
Finance                                                  0.80       7.0
Fisheries & Animal Resources Development                 0.42       2.0
Food Supplies & Consumer Welfare                         0.37      36.0
Forest, Environment and Climate Change Department        0.95      19.0
General Administration & Public Grievance                1.66      45.0
Handlooms ,Textiles & Handicrafts                        0.00       1.0
Health & Family Welfare                                  4.95      58.0
Higher Education                                         2.27     116.0
Home department                                          9.13     220.0
Housing & Urban Development                              0.81     109.0
Industries                                               1.49       2.0
Information & Public Relations                           0.00      12.0
Labour & Employees' State Insurance                      0.87      20.0
Law                                                      2.78       4.0
Micro, Small & Medium Enterprise                         1.69       2.0
Mission Shakti                                           0.00       2.0
NaN                                                      0.67   26685.0
Odia Language Literature & Culture                       0.72       3.0
Panchayati Raj & Drinking Water                          0.80     328.0
Parliamentary Affairs                                    0.00       0.0
Planning & Convergence                                   0.00       4.0
Public Enterprises                                       0.00       0.0
Revenue & Disaster Management                            0.49     219.0
Rural Development                                        2.00     238.0
ST & SC Development, Minorities & Backward Clas...       1.77     154.0
School & Mass Education                                  5.40     129.0
Science & Technology                                    12.50       0.0
Skill Development & Technical Education                  1.28      10.0
Social Security & Empowerment of Persons with D...       0.58      61.0
Sports & Youth Services                                  1.96       8.0
Steel & Mines                                            1.39       3.0
Tourism                                                  2.44       0.0
Water Resources                                          4.60      29.0
Women & Child Development                                2.29      46.0
Works                                                    1.27      27.0

                                                               \

                                                   percentage
dept
Agriculture & Farmers' Empowerment                       0.67
Co-operation                                             0.62
Commerce & Transport                                     1.38
Electronics & Information Technology                     0.00
Energy                                                   1.10
Excise                                                   1.40
Finance                                                  1.63
Fisheries & Animal Resources Development                 0.44
Food Supplies & Consumer Welfare                         0.73
Forest, Environment and Climate Change Department        2.40
General Administration & Public Grievance                0.59
Handlooms ,Textiles & Handicrafts                        1.30
Health & Family Welfare                                  1.05
Higher Education                                        10.10
Home department                                          1.21
Housing & Urban Development                              1.04
Industries                                               2.35
Information & Public Relations                           1.29
Labour & Employees' State Insurance                      1.49
Law                                                      1.42
Micro, Small & Medium Enterprise                         1.42
Mission Shakti                                           0.98
NaN                                                     98.62
Odia Language Literature & Culture                       0.83
Panchayati Raj & Drinking Water                          0.59
Parliamentary Affairs                                    0.00
Planning & Convergence                                   4.82
Public Enterprises                                       0.00
Revenue & Disaster Management                            1.54
Rural Development                                       14.58
ST & SC Development, Minorities & Backward Clas...      10.44
School & Mass Education                                  1.70
Science & Technology                                     0.00
Skill Development & Technical Education                  3.44
Social Security & Empowerment of Persons with D...       1.05
Sports & Youth Services                                  5.37
Steel & Mines                                            3.49
Tourism                                                  0.00
Water Resources                                          3.33
Women & Child Development                                2.93
Works                                                    1.99

                                                                          \
                                                   Disposed with Benefit
                                                                   count
dept
Agriculture & Farmers' Empowerment                                 485.0
Co-operation                                                        49.0
Commerce & Transport                                               112.0
Electronics & Information Technology                                24.0
Energy                                                             546.0
Excise                                                              25.0
Finance                                                             59.0
Fisheries & Animal Resources Development                            91.0
Food Supplies & Consumer Welfare                                   694.0
Forest, Environment and Climate Change Department                  166.0
General Administration & Public Grievance                         2750.0
Handlooms ,Textiles & Handicrafts                                   24.0
Health & Family Welfare                                            842.0
Higher Education                                                   156.0
Home department                                                   2234.0
Housing & Urban Development                                        981.0
Industries                                                          15.0
Information & Public Relations                                      60.0

### Category

In [17]:
pivot_status_category = status_count_pivot(df_filtered, "category")
pivot_status_category

                            2021-2022                                   \
                              Discard            Disposed with Benefit
                                count percentage                 count
category
Accident                          1.0       7.69                   3.0
Agriculture & Farming            25.0       2.43                  77.0
BSKY                              0.0       0.00                   4.0
CMRF                              3.0       0.58                 165.0
COVID-19                          6.0       3.55                  31.0
Culture                           0.0       0.00                   1.0
Disaster Management               0.0       0.00                  24.0
Education                        66.0       6.23                  92.0
Energy                           26.0       1.36                 512.0
Environment                       0.0       0.00                   7.0
Excise                            1.0       0.52                   4.0
Financial Assistance             17.0       2.29                  94.0
General                         268.0       2.15                2723.0
Health Care                      53.0       2.04                 221.0
Housing                         161.0       1.19                 948.0
ICDS                              2.0       0.91                   5.0
Infrastructure                  117.0       4.55                 334.0
Irrigation                        0.0       0.00                   0.0
Land Matters                     68.0       2.55                 331.0
Legal                             0.0       0.00                   1.0
Miscellaneous                   157.0       4.04                 658.0
NaN                           11621.0      37.51                1756.0
Pension/Retirement Benefits      30.0       2.34                 695.0
Police Case                      99.0       1.66                1090.0
Public Utility                   24.0       2.29                  84.0
Scheme &amp;amp; Benefits         0.0       0.00                   0.0
School & College                  7.0       2.35                  14.0
Service Matters                 118.0       3.32                 382.0
Social Welfare                  148.0       1.89                 585.0
Sports                            1.0       2.38                   1.0
Tourism                           0.0       0.00                   0.0
Traffic                           0.0       0.00                   4.0
Transport                         6.0       2.52                  12.0
Waste Management                  9.0       3.44                  94.0
Water Supply                     26.0       0.95                 653.0
Women Issues                      1.0       1.03                   8.0

                                                                              \
                                       Disposed              Open
                            percentage    count percentage  count percentage
category
Accident                         23.08      9.0      69.23    0.0       0.00
Agriculture & Farming             7.50    912.0      88.80   13.0       1.27
BSKY                              6.15     51.0      78.46   10.0      15.38
CMRF                             31.73    349.0      67.12    3.0       0.58
COVID-19                         18.34    127.0      75.15    5.0       2.96
Culture                           7.69     12.0      92.31    0.0       0.00
Disaster Management              27.91     62.0      72.09    0.0       0.00
Education                         8.68    859.0      81.04   43.0       4.06
Energy                           26.76   1345.0      70.31   30.0       1.57
Environment                       4.49    149.0      95.51    0.0       0.00
Excise                            2.09    185.0      96.86    1.0       0.52
Financial Assistance             12.69    625.0      84.35    5.0       0.67
General                          21.86   8634.0      69.30  833.0       6.69
Health Care                       8.52   2237.0      86.20   84.0       3.24
Housing                           7.01  12410.0      91.77    4.0       0.03
ICDS                              2.27    210.0      95.45    3.0       1.36
Infrastructure                   13.00   2050.0      79.80   68.0       2.65
Irrigation                        0.00      0.0       0.00    0.0       0.00
Land Matters                     12.42   2240.0      84.05   26.0       0.98
Legal                             7.14     13.0      92.86    0.0       0.00
Miscellaneous                    16.94   2982.0      76.78   87.0       2.24
NaN                               5.67  17359.0      56.03  244.0       0.79
Pension/Retirement Benefits      54.25    524.0      40.91   32.0       2.50
Police Case                      18.24   4528.0      75.77  259.0       4.33
Public Utility                    8.02    921.0      87.88   19.0       1.81
Scheme &amp;amp; Benefits         0.00      1.0     100.00    0.0       0.00
School & College                  4.70    254.0      85.23   23.0       7.72
Service Matters                  10.74   2931.0      82.42  125.0       3.52
Social Welfare                    7.47   7055.0      90.07   45.0       0.57
Sports                            2.38     39.0      92.86    1.0       2.38
Tourism                           0.00      7.0     100.00    0.0       0.00
Traffic                          17.39     17.0      73.91    2.0       8.70
Transport                         5.04    219.0      92.02    1.0       0.42
Waste Management                 35.88    158.0      60.31    1.0       0.38
Water Supply                     23.88   2023.0      73.99   32.0       1.17
Women Issues                      8.25     86.0      88.66    2.0       2.06

                            2022-2023                                   \
                              Discard            Disposed with Benefit
                                count percentage                 count
category
Accident                          0.0       0.00                   6.0
Agriculture & Farming            18.0       1.23                 141.0
BSKY                              2.0       1.80                   7.0
CMRF                              0.0       0.00                 148.0
COVID-19                          1.0       1.49                   8.0
Culture                           0.0       0.00                   1.0
Disaster Management               4.0       2.92                  14.0
Education                       120.0       7.85                 175.0
Energy                           29.0       0.98                 568.0
Environment                       0.0       0.00                  12.0
Excise                            3.0       1.31                  11.0
Financial Assistance             20.0       0.83                 568.0
General                         401.0       1.30                7194.0
Health Care                      33.0       1.09                 349.0
Housing                         149.0       0.40                7754.0
ICDS                             10.0       2.76                  13.0
Infrastructure                  306.0       5.56                 544.0
Irrigation                        0.0       0.00                   5.0
Land Matters                     89.0       1.17                1194.0
Legal                             1.0       4.17                   3.0
Miscellaneous                   243.0       1.95                1412.0
NaN                           26689.0      98.61                   0.0
Pension/Retirement Benefits      32.0       2.10                 259.0
Police Case                     130.0       1.15                1312.0
Public Utility                   23.0       0.98                 190.0
Scheme &amp;amp; Benefits         0.0       0.00                   0.0
School & College                  2.0       0.24                  94.0
Service Matters                 184.0       3.49                 788.0
Social Welfare                  151.0       0.68                1363.0
Sports                            8.0       6.61                   3.0
Tourism                           0.0       0.00                   0.0
Traffic                           1.0       2.50                   4.0
Transport                         4.0       0.96                   3.0
Waste Management                  3.0       1.32                  86.0
Water Supply                     31.0       0.92                 694.0
Women Issues                      0.0       0.00                  25.0

                                                                               \
                                       Disposed               Open
                            percentage    count percentage   count percentage
category
Accident                         17.14     29.0      82.86     0.0       0.00
Agriculture & Farming             9.65   1272.0      87.06    30.0       2.05
BSKY                              6.31     95.0      85.59     7.0       6.31
CMRF                             30.02    341.0      69.17     4.0       0.81
COVID-19                         11.94     55.0      82.09     3.0       4.48
Culture                          20.00      4.0      80.00     0.0       0.00
Disaster Management              10.22    119.0      86.86     0.0       0.00
Education                        11.45   1155.0      75.54    79.0       5.17
Energy                           19.18   2282.0      77.07    82.0       2.77
Environment                       6.67    166.0      92.22     2.0       1.11
Excise                            4.80    212.0      92.58     3.0       1.31
Financial Assistance             23.47   1781.0      73.60    51.0       2.11
General                          23.33  20928.0      67.87  2312.0       7.50
Health Care                      11.53   2486.0      82.10   160.0       5.28
Housing                          20.79  29331.0      78.64    64.0       0.17
ICDS                              3.59    329.0      90.88    10.0       2.76
Infrastructure                    9.89   4455.0      81.00   195.0       3.55
Irrigation                       13.89     28.0      77.78     3.0       8.33
Land Matters                     15.69   6258.0      82.23    69.0       0.91
Legal                            12.50     19.0      79.17     1.0       4.17
Miscellaneous                    11.34  10313.0      82.86   479.0       3.85
NaN                               0.00      0.0       0.00   376.0       1.39
Pension/Retirement Benefits      17.03   1143.0      75.15    87.0       5.72
Police Case                      11.63   9648.0      85.51   193.0       1.71
Public Utility                    8.06   2077.0      88.08    68.0       2.88
Scheme &amp;amp; Benefits         0.00      0.0       0.00     0.0       0.00
School & College                 11.15    659.0      78.17    88.0      10.44
Service Matters                  14.94   3930.0      74.52   372.0       7.05
Social Welfare                    6.13  20631.0      92.79    89.0       0.40
Sports                            2.48    110.0      90.91     0.0       0.00
Tourism                           0.00      7.0      87.50     1.0      12.50
Traffic                          10.00     35.0      87.50     0.0       0.00
Transport                         0.72    408.0      98.31     0.0       0.00
Waste Management                 37.89    134.0      59.03     4.0       1.76
Water Supply                     20.55   2545.0      75.36   107.0       3.17
Women Issues                     14.88    138.0      82.14     5.0       2.98

                            2023-2024                                   \
                              Discard            Disposed with Benefit
                                count percentage                 count
category
Accident                          0.0       0.00                   4.0
Agriculture & Farming            27.0       1.38                 122.0
BSKY                              1.0       0.34                  21.0
CMRF                              0.0       0.00                 176.0
COVID-19                          0.0       0.00                   5.0
Culture                           3.0       0.71                  35.0
Disaster Management               0.0       0.00                  13.0
Education                       849.0      15.94                 328.0
Energy                           30.0       0.69                 719.0
Environment                      12.0       4.27                  22.0
Excise                            0.0       0.00                  27.0
Financial Assistance             32.0       0.63                 959.0
General                         306.0       0.98                6180.0
Health Care                      38.0       1.03                 378.0
Housing                         187.0       0.22                5466.0
ICDS                             11.0       1.83                  29.0
Infrastructure                  241.0       0.46                6322.0
Irrigation                       19.0       0.87                 264.0
Land Matters                    146.0       1.13                1144.0
Legal                             3.0       1.81                   9.0
Miscellaneous                   277.0       1.22                1354.0
NaN                           36381.0      99.05                   0.0
Pension/Retirement Benefits      17.0       1.04                 148.0
Police Case                     115.0       0.83                 926.0
Public Utility                   47.0       0.73                 467.0
Scheme &amp;amp; Benefits         0.0       0.00                   0.0
School & College                 14.0       0.51                 212.0
Service Matters                 322.0       2.43                 638.0
Social Welfare                  167.0       0.37                2840.0
Sports                           20.0       2.74                  81.0
Tourism                           3.0       0.53                  73.0
Traffic                           1.0       1.37                   7.0
Transport                         1.0       0.26                  25.0
Waste Management                  3.0       2.68                  28.0
Water Supply                     40.0       0.76                 998.0
Women Issues                      2.0       1.77                  13.0

                                                                               \
                                       Disposed               Open
                            percentage    count percentage   count percentage
category
Accident                          7.84     42.0      82.35     5.0       9.80
Agriculture & Farming             6.25   1683.0      86.18   121.0       6.20
BSKY                              7.17    239.0      81.57    32.0      10.92
CMRF                             22.06    467.0      58.52   155.0      19.42
COVID-19                          7.69     48.0      73.85    12.0      18.46
Culture                           8.25    373.0      87.97    13.0       3.07
Disaster Management               7.14    161.0      88.46     8.0       4.40
Education                         6.16   3896.0      73.14   254.0       4.77
Energy                           16.43   3366.0      76.94   260.0       5.94
Environment                       7.83    236.0      83.99    11.0       3.91
Excise                            8.36    287.0      88.85     9.0       2.79
Financial Assistance             18.88   3808.0      74.96   281.0       5.53
General                          19.82  20595.0      66.05  4102.0      13.15
Health Care                      10.22   2847.0      77.01   434.0      11.74
Housing                           6.51  77307.0      92.14   939.0       1.12
ICDS                              4.83    489.0      81.50    71.0      11.83
Infrastructure                   12.13  43799.0      84.05  1750.0       3.36
Irrigation                       12.07   1760.0      80.48   144.0       6.58
Land Matters                      8.89  11252.0      87.46   323.0       2.51
Legal                             5.42    139.0      83.73    15.0       9.04
Miscellaneous                     5.94  18907.0      82.98  2246.0       9.86
NaN                               0.00      0.0       0.00   349.0       0.95
Pension/Retirement Benefits       9.04   1273.0      77.76   199.0      12.16
Police Case                       6.69   9520.0      68.79  3278.0      23.69
Public Utility                    7.26   5475.0      85.15   441.0       6.86
Scheme &amp;amp; Benefits         0.00      0.0       0.00     0.0       0.00
School & College                  7.78   2224.0      81.61   275.0      10.09
Service Matters                   4.80  11078.0      83.43  1240.0       9.34
Social Welfare                    6.31  41458.0      92.10   550.0       1.22
Sports                           11.10    586.0      80.27    43.0       5.89
Tourism                          12.87    479.0      84.48    12.0       2.12
Traffic                           9.59     58.0      79.45     7.0       9.59
Transport                         6.43    355.0      91.26     8.0       2.06
Waste Management                 25.00     73.0      65.18     8.0       7.14
Water Supply                     18.84   3449.0      65.12   809.0      15.28
Women Issues                     11.50     93.0      82.30     5.0       4.42

                            2024-2025                                   \
                              Discard            Disposed with Benefit
                                count percentage                 count
category
Accident                          0.0       0.00                   4.0
Agriculture & Farming            39.0       1.40                  39.0
BSKY                              2.0       1.34                   1.0
CMRF                              9.0       0.62                  25.0
COVID-19                          0.0       0.00                   0.0
Culture                           7.0       3.80                   5.0
Disaster Management               2.0       0.65                  14.0
Education                       619.0      10.28                 554.0
Energy                           34.0       0.38                 631.0
Environment                       5.0       0.70                  70.0
Excise                            2.0       0.34                   7.0
Financial Assistance             79.0       0.81                 250.0
General                         427.0       0.70               11348.0
Health Care                      35.0       0.68                 168.0
Housing                         238.0       0.14                4000.0
ICDS                              6.0       0.60                  31.0
Infrastructure                  151.0       0.85                 582.0
Irrigation                       25.0       2.10                  12.0
Land Matters                    185.0       0.73                 539.0
Legal                             4.0       1.15                   2.0
Miscellaneous                   603.0       1.22                1117.0
NaN                          103328.0      84.01                   0.0
Pension/Retirement Benefits      49.0       1.19                  78.0
Police Case                      93.0       0.35                1579.0
Public Utility                   19.0       0.40                 131.0
Scheme &amp;amp; Benefits         0.0       0.00                   0.0
School & College                 15.0       0.58                  57.0
Service Matters                 355.0       1.52                 373.0
Social Welfare                  443.0       0.33                2709.0
Sports                           18.0       5.70                   1.0
Tourism                           1.0       0.68                  11.0
Traffic                           4.0       2.52                   3.0

### Subcategory

In [18]:
pivot_status_subcategory = status_count_pivot(df_filtered, "subcategory")
pivot_status_subcategory

                              2021-2022                                   \
                                Discard            Disposed with Benefit
                                  count percentage                 count
subcategory
AIDS                                0.0       0.00                   0.0
Aadhar Card Issues                  0.0       0.00                   1.0
Absence of officials                0.0       0.00                   0.0
Absurd/Irrelevant                   0.0       0.00                   1.0
Accidental Claims                   0.0       0.00                   0.0
...                                 ...        ...                   ...
Voltage fluctuations                0.0       0.00                   3.0
Water Supply issue                 11.0       4.47                  74.0
Water Tanks/ Reservoirs/Ponds       0.0       0.00                   0.0
Web Portal Issues                   0.0       0.00                   3.0
Workplace Harrassement              0.0       0.00                   0.0

                                                                               \
                                         Disposed             Open
                              percentage    count percentage count percentage
subcategory
AIDS                                0.00      0.0       0.00   0.0       0.00
Aadhar Card Issues                  5.88     15.0      88.24   1.0       5.88
Absence of officials                0.00      0.0       0.00   0.0       0.00
Absurd/Irrelevant                  20.00      4.0      80.00   0.0       0.00
Accidental Claims                   0.00      5.0     100.00   0.0       0.00
...                                  ...      ...        ...   ...        ...
Voltage fluctuations               15.79     16.0      84.21   0.0       0.00
Water Supply issue                 30.08    154.0      62.60   7.0       2.85
Water Tanks/ Reservoirs/Ponds       0.00      0.0       0.00   0.0       0.00
Web Portal Issues                  20.00     12.0      80.00   0.0       0.00
Workplace Harrassement              0.00      8.0     100.00   0.0       0.00

                              2022-2023                                   \
                                Discard            Disposed with Benefit
                                  count percentage                 count
subcategory
AIDS                                0.0       0.00                   0.0
Aadhar Card Issues                  0.0       0.00                   4.0
Absence of officials                0.0       0.00                   0.0
Absurd/Irrelevant                   0.0       0.00                   1.0
Accidental Claims                   0.0       0.00                   5.0
...                                 ...        ...                   ...
Voltage fluctuations                0.0       0.00                   2.0
Water Supply issue                 10.0       3.47                  79.0
Water Tanks/ Reservoirs/Ponds       0.0       0.00                   0.0
Web Portal Issues                   1.0       7.14                   1.0
Workplace Harrassement              0.0       0.00                   0.0

                                                                               \
                                         Disposed             Open
                              percentage    count percentage count percentage
subcategory
AIDS                                0.00      1.0     100.00   0.0       0.00
Aadhar Card Issues                 28.57      9.0      64.29   1.0       7.14
Absence of officials                0.00      0.0       0.00   0.0       0.00
Absurd/Irrelevant                   7.14     11.0      78.57   2.0      14.29
Accidental Claims                  21.74     18.0      78.26   0.0       0.00
...                                  ...      ...        ...   ...        ...
Voltage fluctuations                7.69     24.0      92.31   0.0       0.00
Water Supply issue                 27.43    192.0      66.67   7.0       2.43
Water Tanks/ Reservoirs/Ponds       0.00      2.0     100.00   0.0       0.00
Web Portal Issues                   7.14     11.0      78.57   1.0       7.14
Workplace Harrassement              0.00     17.0      80.95   4.0      19.05

                              2023-2024                                   \
                                Discard            Disposed with Benefit
                                  count percentage                 count
subcategory
AIDS                                1.0      25.00                   1.0
Aadhar Card Issues                  1.0       3.57                   4.0
Absence of officials                0.0       0.00                   1.0
Absurd/Irrelevant                   0.0       0.00                   1.0
Accidental Claims                   0.0       0.00                   3.0
...                                 ...        ...                   ...
Voltage fluctuations                0.0       0.00                  12.0
Water Supply issue                 21.0       1.05                 354.0
Water Tanks/ Reservoirs/Ponds       2.0       0.25                  46.0
Web Portal Issues                   0.0       0.00                   1.0
Workplace Harrassement              0.0       0.00                   1.0

                                                                     \
                                         Disposed              Open
                              percentage    count percentage  count
subcategory
AIDS                               25.00      2.0      50.00    0.0
Aadhar Card Issues                 14.29     20.0      71.43    3.0
Absence of officials               50.00      1.0      50.00    0.0
Absurd/Irrelevant                   8.33      7.0      58.33    4.0
Accidental Claims                   8.33     31.0      86.11    2.0
...                                  ...      ...        ...    ...
Voltage fluctuations               15.58     64.0      83.12    1.0
Water Supply issue                 17.69   1157.0      57.82  469.0
Water Tanks/ Reservoirs/Ponds       5.79    724.0      91.18   22.0
Web Portal Issues                   4.76     11.0      52.38    9.0
Workplace Harrassement              5.56     16.0      88.89    1.0

                                         2024-2025             \
                                           Discard
                              percentage     count percentage
subcategory
AIDS                                0.00       0.0       0.00
Aadhar Card Issues                 10.71       4.0       2.34
Absence of officials                0.00       0.0       0.00
Absurd/Irrelevant                  33.33       1.0       2.50
Accidental Claims                   5.56       3.0       2.73
...                                  ...       ...        ...
Voltage fluctuations                1.30       0.0       0.00
Water Supply issue                 23.44      15.0       0.44
Water Tanks/ Reservoirs/Ponds       2.77       1.0       0.52
Web Portal Issues                  42.86       1.0       1.67
Workplace Harrassement              5.56       0.0       0.00

                                                                         \
                              Disposed with Benefit            Disposed
                                              count percentage    count
subcategory
AIDS                                            0.0       0.00     12.0
Aadhar Card Issues                              5.0       2.92     99.0
Absence of officials                            0.0       0.00      0.0
Absurd/Irrelevant                               1.0       2.50     31.0
Accidental Claims                               7.0       6.36     80.0
...                                             ...        ...      ...
Voltage fluctuations                           13.0       9.85     73.0
Water Supply issue                            435.0      12.69   1656.0
Water Tanks/ Reservoirs/Ponds                   1.0       0.52    145.0
Web Portal Issues                               2.0       3.33     35.0
Workplace Harrassement                          0.0       0.00     31.0

                                                            Aggregate  \
                                            Open              Discard
                              percentage   count percentage     count
subcategory
AIDS                               92.31     1.0       7.69       1.0
Aadhar Card Issues                 57.89    63.0      36.84       5.0
Absence of officials                0.00     0.0       0.00       0.0
Absurd/Irrelevant                  77.50     7.0      17.50       1.0
Accidental Claims                  72.73    20.0      18.18       3.0
...                                  ...     ...        ...       ...
Voltage fluctuations               55.30    46.0      34.85       0.0
Water Supply issue                 48.32  1321.0      38.55      57.0
Water Tanks/ Reservoirs/Ponds      75.92    44.0      23.04       3.0
Web Portal Issues                  58.33    22.0      36.67       2.0
Workplace Harrassement             67.39    15.0      32.61       0.0

                                                                           \
                                         Disposed with Benefit
                              percentage                 count percentage
subcategory
AIDS                                5.56                   1.0       5.56
Aadhar Card Issues                  2.17                  14.0       6.09
Absence of officials                0.00                   1.0      50.00
Absurd/Irrelevant                   1.41                   4.0       5.63
Accidental Claims                   1.72                  15.0       8.62
...                                  ...                   ...        ...
Voltage fluctuations                0.00                  30.0      11.81
Water Supply issue                  0.96                 942.0      15.80
Water Tanks/ Reservoirs/Ponds       0.30                  47.0       4.76
Web Portal Issues                   1.82                   7.0       6.36
Workplace Harrassement              0.00                   1.0       1.08


                              Disposed               Open
                                 count percentage   count percentage
subcategory
AIDS                              15.0      83.33     1.0       5.56
Aadhar Card Issues               143.0      62.17    68.0      29.57
Absence of officials               1.0      50.00     0.0       0.00
Absurd/Irrelevant                 53.0      74.65    13.0      18.31
Accidental Claims                134.0      77.01    22.0      12.64
...                                ...        ...     ...        ...
Voltage fluctuations             177.0      69.69    47.0      18.50
Water Supply issue              3159.0      52.99  1804.0      30.26
Water Tanks/ Reservoirs/Ponds    871.0      88.25    66.0       6.69
Web Portal Issues                 69.0      62.73    32.0      29.09
Workplace Harrassement            72.0      77.42    20.0      21.51

[239 rows x 40 columns]

### Export -- Status Group Tables

In [ ]:
output_file = f"{OUTPUT_DIR}/status_group_breakdowns.xlsx"

with pd.ExcelWriter(output_file) as writer:
    pivot_status_yearly.to_excel(writer, sheet_name="Yearly")
    pivot_status_district.to_excel(writer, sheet_name="District")
    pivot_status_office.to_excel(writer, sheet_name="Office")
    pivot_status_dept.to_excel(writer, sheet_name="Department")
    pivot_status_category.to_excel(writer, sheet_name="Category")
    pivot_status_subcategory.to_excel(writer, sheet_name="Subcategory")

print(f"Status-group breakdowns exported: {output_file}")

## 2. Disposal Time by Status Bucket

Count, percentage, mean and median disposal days (Discard / Disposed with Benefit / Disposed / In Follow Up) at each breakdown level, with the same Aggregate + year-wise layout.

### Yearly

In [5]:
pivot_res_yearly = disposal_time_pivot(df_res, "custom_year")
pivot_res_yearly

              Discard                         Disposed with Benefit  \
                count percentage  mean median                 count
custom_year
2021-2022     13061.0      13.56  67.0    3.0               11613.0
2022-2023     28687.0      16.23  20.0    2.0               24948.0
2023-2024     39315.0      11.66  21.0    3.0               30033.0
2024-2025    106828.0      18.38  30.0    3.0               25182.0
Aggregate    187891.0      15.77  29.0    3.0               91776.0

                                      Disposed                           \
            percentage   mean median     count percentage   mean median
custom_year
2021-2022        12.06  194.0  126.0   71583.0      74.34  219.0  163.0
2022-2023        14.11   90.0   37.0  123120.0      69.65  107.0   48.0
2023-2024         8.91   98.0   49.0  267814.0      79.43  109.0   64.0
2024-2025         4.33   76.0   46.0  449083.0      77.28   63.0   41.0
Aggregate         7.70  102.0   50.0  911600.0      76.52   95.0   51.0

            In Follow Up With Close
                              count percentage   mean median
custom_year
2021-2022                      38.0       0.04   71.0   35.0
2022-2023                       6.0       0.00   21.0    7.0
2023-2024                       2.0       0.00  439.0  439.0
2024-2025                      35.0       0.01  144.0  181.0
Aggregate                      81.0       0.01  108.0   57.0

### District

In [8]:
pivot_res_district = disposal_time_pivot(df_res, "district")
pivot_res_district

               2021-2022                                                 \
                 Discard                          Disposed with Benefit
                   count percentage   mean median                 count
district
Angul              476.0      17.42   66.0    3.0                 245.0
Balangir           458.0      11.34   72.0    8.0                 958.0
Baleswar          1171.0      15.40   43.0    4.0                 348.0
Bargarh            537.0      15.84   57.0    4.0                 247.0
Bhadrak            649.0      13.75  136.0    9.0                 242.0
Boudh              191.0      24.74   42.0   10.0                 103.0
Cuttack            689.0      16.42  117.0   22.0                 430.0
Deogarh             70.0      11.80   72.0   12.0                  38.0
Dhenkanal          992.0      23.03   16.0    1.0                 140.0
Gajapati           137.0       9.72  108.0    6.0                  66.0
Ganjam             719.0      14.49   77.0    3.0                 508.0
Jagatsinghapur     323.0       9.97   71.0   16.0                 152.0
Jajpur            1126.0      20.91   42.0    2.0                 228.0
Jharsuguda         118.0      16.12   41.0    4.0                  87.0
Kalahandi          917.0       9.77   41.0    2.0                 652.0
Kandhamal          208.0       8.61   67.0   20.0                 348.0
Kendrapara         432.0       8.99   63.0    4.0                 274.0
Kendujhar          198.0       9.81   86.0    6.0                 179.0
Khordha           1087.0      13.79   80.0    3.0                2855.0
Koraput            212.0      15.63   76.0   14.0                 192.0
Malkangiri          80.0      17.28   30.0    2.0                  90.0
Mayurbhanj         236.0       8.53   81.0    5.0                1223.0
NaN                140.0       3.70  264.0  177.0                 603.0
Nabarangpur        121.0      11.80   45.0    5.0                 106.0
Nayagarh           297.0      12.12   67.0    3.0                 198.0
Nuapada            116.0       9.39   48.0   10.0                  95.0
Puri               452.0      14.43   76.0    6.0                 350.0
Rayagada           159.0      13.84   72.0    4.0                 148.0
Sambalpur          274.0      17.71   69.0    4.0                 136.0
Subarnapur         182.0      14.61   70.0    8.0                 223.0
Sundargarh         294.0      19.13   61.0    5.0                 149.0

                                                                           \
                                        Disposed
               percentage   mean median    count percentage   mean median
district
Angul                8.96  179.0  150.0   2011.0      73.58  204.0  169.0
Balangir            23.72  238.0  218.0   2622.0      64.92  295.0  272.0
Baleswar             4.58  289.0  210.0   6084.0      80.01  280.0  229.0
Bargarh              7.28  139.0   84.0   2602.0      76.73  146.0   97.0
Bhadrak              5.13  353.0  232.0   3830.0      81.13  233.0  198.0
Boudh               13.34  150.0   96.0    478.0      61.92  162.0  105.0
Cuttack             10.25  298.0  259.0   3078.0      73.34  305.0  263.0
Deogarh              6.41  189.0  150.0    485.0      81.79  256.0  215.0
Dhenkanal            3.25  182.0  115.0   3175.0      73.70  119.0   59.0
Gajapati             4.68  205.0  140.0   1206.0      85.59  212.0  113.0
Ganjam              10.24  213.0  144.0   3736.0      75.28  178.0  106.0
Jagatsinghapur       4.69  236.0  220.0   2765.0      85.31  205.0  158.0
Jajpur               4.23  270.0  219.0   4032.0      74.86  200.0  145.0
Jharsuguda          11.89  173.0   73.0    509.0      69.54  144.0   54.0
Kalahandi            6.95  181.0  158.0   7818.0      83.28  193.0  154.0
Kandhamal           14.40  252.0  196.0   1859.0      76.95  240.0  202.0
Kendrapara           5.70  222.0  139.0   4099.0      85.31  188.0  128.0
Kendujhar            8.87  179.0  114.0   1642.0      81.33  250.0  190.0
Khordha             36.22  157.0   87.0   3939.0      49.97  319.0  243.0
Koraput             14.16  210.0  175.0    951.0      70.13  202.0  171.0
Malkangiri          19.44   75.0   35.0    293.0      63.28  118.0   15.0
Mayurbhanj          44.18  157.0   81.0   1309.0      47.29  257.0  172.0
NaN                 15.93  146.0   99.0   3042.0      80.37  208.0  106.0
Nabarangpur         10.34  226.0  139.0    798.0      77.85  140.0   88.0
Nayagarh             8.08  241.0  205.0   1953.0      79.71  201.0  165.0
Nuapada              7.69  182.0  117.0   1025.0      82.93  150.0   83.0
Puri                11.17  223.0  170.0   2331.0      74.40  234.0  176.0
Rayagada            12.88  183.0  124.0    842.0      73.28  301.0  224.0
Sambalpur            8.79  185.0  103.0   1136.0      73.43  163.0   95.0
Subarnapur          17.90  134.0   89.0    840.0      67.42  234.0  168.0
Sundargarh           9.69  182.0  134.0   1093.0      71.11  198.0  133.0

                                                                2022-2023  \
               In Follow Up With Close                            Discard
                                 count percentage   mean median     count
district
Angul                              1.0       0.04  235.0  235.0     651.0
Balangir                           1.0       0.02   77.0   77.0    1990.0
Baleswar                           1.0       0.01   10.0   10.0    3255.0
Bargarh                            5.0       0.15   52.0   27.0     736.0
Bhadrak                            0.0       0.00    0.0    0.0    1179.0
Boudh                              0.0       0.00    0.0    0.0     597.0
Cuttack                            0.0       0.00    0.0    0.0    1272.0
Deogarh                            0.0       0.00    0.0    0.0     115.0
Dhenkanal                          1.0       0.02   16.0   16.0    1960.0
Gajapati                           0.0       0.00    0.0    0.0     562.0
Ganjam                             0.0       0.00    0.0    0.0    2042.0
Jagatsinghapur                     1.0       0.03  359.0  359.0     555.0
Jajpur                             0.0       0.00    0.0    0.0    2347.0
Jharsuguda                        18.0       2.46   34.0   25.0     312.0
Kalahandi                          1.0       0.01   50.0   50.0    1364.0
Kandhamal                          1.0       0.04  148.0  148.0     309.0
Kendrapara                         0.0       0.00    0.0    0.0    1228.0
Kendujhar                          0.0       0.00    0.0    0.0     730.0
Khordha                            2.0       0.03  150.0  150.0    2119.0
Koraput                            1.0       0.07  296.0  296.0     443.0
Malkangiri                         0.0       0.00    0.0    0.0     100.0
Mayurbhanj                         0.0       0.00    0.0    0.0     555.0
NaN                                0.0       0.00    0.0    0.0     123.0
Nabarangpur                        0.0       0.00    0.0    0.0     233.0
Nayagarh                           2.0       0.08  107.0  107.0     863.0
Nuapada                            0.0       0.00    0.0    0.0     236.0
Puri                               0.0       0.00    0.0    0.0     926.0
Rayagada                           0.0       0.00    0.0    0.0     323.0
Sambalpur                          1.0       0.06   14.0   14.0     452.0
Subarnapur                         1.0       0.08   32.0   32.0     314.0
Sundargarh                         1.0       0.07   58.0   58.0     796.0

                                                                         \
                                       Disposed with Benefit
               percentage  mean median                 count percentage
district
Angul               18.28  18.0    2.0                 316.0       8.87
Balangir            16.20  12.0    1.0                5473.0      44.55
Baleswar            21.34  14.0    2.0                 532.0       3.49
Bargarh             16.54  17.0    1.0                 344.0       7.73
Bhadrak             14.57  11.0    1.0                 378.0       4.67
Boudh               14.06  16.0    2.0                 821.0      19.34
Cuttack             17.31  31.0    2.0                 698.0       9.50
Deogarh             12.29  16.0    2.0                  38.0       4.06
Dhenkanal           34.10   7.0    1.0                 433.0       7.53
Gajapati            14.35  26.0    6.0                 120.0       3.06
Ganjam              16.38  15.0    1.0                 853.0       6.84
Jagatsinghapur       7.04  29.0    2.0                 266.0       3.37
Jajpur              27.14  38.0    1.0                 538.0       6.22
Jharsuguda          24.82  20.0    2.0                 109.0       8.67
Kalahandi           10.45  15.0    1.0                3905.0      29.93
Kandhamal           13.49  37.0    8.0                 490.0      21.39
Kendrapara          16.38  18.0    2.0                 695.0       9.27
Kendujhar           19.55  19.0    2.0                 212.0       5.68
Khordha             22.00  37.0    2.0                1817.0      18.86
Koraput             20.44  23.0    2.0                 353.0      16.29
Malkangiri          20.41  55.0    8.0                  48.0       9.80
Mayurbhanj           8.29  21.0    2.0                4615.0      68.97
NaN                 21.65  49.0    4.0                  63.0      11.09
Nabarangpur          7.10  23.0    2.0                 138.0       4.20
Nayagarh            13.51   9.0    1.0                 236.0       3.69
Nuapada              7.40  27.0    2.0                 102.0       3.20
Puri                11.04  20.0    2.0                 423.0       5.04
Rayagada            13.32  40.0    3.0                 327.0      13.48
Sambalpur           18.26   8.0    1.0                 247.0       9.98
Subarnapur          12.00  40.0    2.0                 148.0       5.66
Sundargarh          13.76  19.0    3.0                 210.0       3.63

                                                                \
                             Disposed
                 mean median    count percentage   mean median
district
Angul           128.0   73.0   2594.0      72.82   87.0   45.0
Balangir         34.0   19.0   4822.0      39.25   73.0   33.0
Baleswar        142.0   85.0  11469.0      75.18  132.0   89.0
Bargarh         124.0   42.0   3371.0      75.74   82.0   26.0
Bhadrak         215.0   90.0   6533.0      80.75   91.0   45.0
Boudh            47.0   29.0   2828.0      66.60   81.0   42.0
Cuttack         140.0   70.0   5379.0      73.19  126.0   58.0
Deogarh         209.0  127.0    783.0      83.65  146.0   74.0
Dhenkanal       126.0   60.0   3354.0      58.36   86.0   39.0
Gajapati        152.0   87.0   3234.0      82.58  155.0   53.0
Ganjam          106.0   43.0   9569.0      76.77   71.0   31.0
Jagatsinghapur  133.0   61.0   7063.0      89.58  100.0   57.0
Jajpur          113.0   53.0   5764.0      66.64  106.0   52.0
Jharsuguda      145.0   66.0    834.0      66.35   80.0   33.0
Kalahandi        75.0   57.0   7778.0      59.62  100.0   52.0
Kandhamal       164.0   87.0   1492.0      65.12  153.0   77.0
Kendrapara      151.0   91.0   5575.0      74.35  130.0   53.0
Kendujhar       130.0   56.0   2792.0      74.77  131.0   56.0
Khordha         117.0   51.0   5696.0      59.14  166.0   75.0
Koraput          91.0   35.0   1369.0      63.17  101.0   40.0
Malkangiri      121.0   68.0    342.0      69.80   80.0   16.0
Mayurbhanj       97.0   33.0   1521.0      22.73  191.0   75.0
NaN              85.0   46.0    382.0      67.25  120.0   54.0
Nabarangpur     107.0   46.0   2911.0      88.70   67.0   41.0
Nayagarh        112.0   51.0   5289.0      82.80   99.0   46.0
Nuapada          80.0   25.0   2851.0      89.40  106.0   42.0
Puri            153.0   70.0   7040.0      83.92   88.0   44.0
Rayagada         73.0   28.0   1775.0      73.20  250.0  157.0
Sambalpur        72.0   33.0   1776.0      71.76   82.0   31.0
Subarnapur      175.0   91.0   2155.0      82.35  143.0   86.0
Sundargarh       77.0   29.0   4779.0      82.61   45.0   16.0

                                                               2023-2024  \
               In Follow Up With Close                           Discard
                                 count percentage  mean median     count
district
Angul                              1.0       0.03  11.0   11.0    1040.0
Balangir                           0.0       0.00   0.0    0.0    2298.0
Baleswar                           0.0       0.00   0.0    0.0    4074.0
Bargarh                            0.0       0.00   0.0    0.0    1011.0
Bhadrak                            0.0       0.00   0.0    0.0    1705.0
Boudh                              0.0       0.00   0.0    0.0     354.0
Cuttack                            0.0       0.00   0.0    0.0    1988.0
Deogarh                            0.0       0.00   0.0    0.0     177.0
Dhenkanal                          0.0       0.00   0.0    0.0    3586.0
Gajapati                           0.0       0.00   0.0    0.0     391.0
Ganjam                             0.0       0.00   0.0    0.0    2807.0
Jagatsinghapur                     1.0       0.01   3.0    3.0     650.0
Jajpur                             0.0       0.00   0.0    0.0    1921.0
Jharsuguda                         2.0       0.16  52.0   52.0     587.0
Kalahandi                          0.0       0.00   0.0    0.0    1560.0
Kandhamal                          0.0       0.00   0.0    0.0     379.0
Kendrapara                         0.0       0.00   0.0    0.0    1560.0
Kendujhar                          0.0       0.00   0.0    0.0    1196.0
Khordha                            0.0       0.00   0.0    0.0    2132.0
Koraput                            2.0       0.09   3.0    3.0     796.0
Malkangiri                         0.0       0.00   0.0    0.0     166.0
Mayurbhanj                         0.0       0.00   0.0    0.0    1410.0
NaN                                0.0       0.00   0.0    0.0     460.0
Nabarangpur                        0.0       0.00   0.0    0.0     762.0
Nayagarh                           0.0       0.00   0.0    0.0     758.0
Nuapada                            0.0       0.00   0.0    0.0     397.0
Puri                               0.0       0.00   0.0    0.0    1216.0
Rayagada                           0.0       0.00   0.0    0.0     802.0
Sambalpur                          0.0       0.00   0.0    0.0    1046.0
Subarnapur                         0.0       0.00   0.0    0.0     661.0
Sundargarh                         0.0       0.00   0.0    0.0    1425.0

                                                                         \
                                       Disposed with Benefit
               percentage  mean median                 count percentage
district
Angul               12.70  17.0    2.0                 353.0       4.31
Balangir             9.48  17.0    2.0                1948.0       8.03
Baleswar            21.31  13.0    1.0                 887.0       4.64
Bargarh             10.13  19.0    3.0                 258.0       2.58
Bhadrak             12.72  16.0    2.0                 745.0       5.56
Boudh                8.74  29.0    2.0                 252.0       6.22
Cuttack             15.45  33.0    2.0                1887.0      14.66
Deogarh              5.79  19.0    3.0                 302.0       9.88
Dhenkanal           22.99  11.0    4.0                1243.0       7.97
Gajapati             6.83  20.0    2.0                 205.0       3.58
Ganjam              11.87  28.0    3.0                 682.0       2.88
Jagatsinghapur       7.96  20.0    3.0                 264.0       3.23
Jajpur              17.38  32.0    3.0                 564.0       5.10
Jharsuguda          13.75  10.0    1.0                 128.0       3.00
Kalahandi            7.22  23.0    5.0                3720.0      17.23
Kandhamal            7.25  18.0    3.0                 638.0      12.21
Kendrapara          20.64  33.0    3.0                 969.0      12.82
Kendujhar            8.46  32.0    4.0                 298.0       2.11
Khordha             14.61  29.0    4.0                2514.0      17.22
Koraput             12.55  18.0    2.0                 984.0      15.51
Malkangiri           8.29  19.0    4.0                 400.0      19.97
Mayurbhanj           8.16  16.0    2.0                6627.0      38.35
NaN                 47.62  46.0    7.0                  48.0       4.97
Nabarangpur         13.46  14.0    4.0                 877.0      15.49
Nayagarh             9.32  13.0    2.0                 173.0       2.13
Nuapada              5.12  15.0    3.0                 385.0       4.97
Puri                11.63  24.0    3.0                 726.0       6.94
Rayagada            21.06  15.0    2.0                  80.0       2.10
Sambalpur            4.68  15.0    2.0                 421.0       1.88
Subarnapur          13.33  17.0    2.0                  92.0       1.86
Sundargarh           6.80  22.0    5.0                1363.0       6.50

                                                                \
                             Disposed
                 mean median    count percentage   mean median
district
Angul            99.0   31.0   6794.0      82.99  104.0   70.0
Balangir         47.0   16.0  20003.0      82.49  133.0  114.0
Baleswar        111.0   41.0  14156.0      74.05  125.0   66.0
Bargarh         148.0   74.0   8712.0      87.29  104.0   53.0
Bhadrak         117.0   65.0  10956.0      81.72  105.0   60.0
Boudh           113.0   54.0   3443.0      85.03  115.0   56.0
Cuttack          78.0   25.0   8995.0      69.89  133.0   70.0
Deogarh          46.0   25.0   2578.0      84.33  106.0   93.0
Dhenkanal        68.0   29.0  10767.0      69.04   82.0   44.0
Gajapati        107.0  111.0   5131.0      89.59  140.0  122.0
Ganjam          109.0   61.0  20160.0      85.25   91.0   53.0
Jagatsinghapur  142.0   89.0   7249.0      88.80  119.0   58.0
Jajpur          162.0   85.0   8570.0      77.52  109.0   46.0
Jharsuguda      172.0  125.0   3553.0      83.25   92.0   45.0
Kalahandi       111.0   92.0  16312.0      75.55  142.0   95.0
Kandhamal       174.0  115.0   4210.0      80.54   77.0   30.0
Kendrapara       82.0   40.0   5028.0      66.53  125.0   82.0
Kendujhar       179.0  116.0  12645.0      89.43  103.0   96.0
Khordha          79.0   46.0   9950.0      68.17  132.0   84.0
Koraput          57.0   34.0   4564.0      71.94  103.0   56.0
Malkangiri       39.0   17.0   1437.0      71.74   77.0   39.0
Mayurbhanj      123.0   86.0   9242.0      53.49  102.0   53.0
NaN             114.0   66.0    458.0      47.41  115.0   75.0
Nabarangpur      28.0   13.0   4021.0      71.04  137.0   52.0
Nayagarh        113.0   64.0   7203.0      88.54   76.0   42.0
Nuapada          90.0   27.0   6968.0      89.91  148.0  104.0
Puri            153.0   82.0   8515.0      81.43   98.0   47.0
Rayagada         93.0   66.0   2926.0      76.84  101.0   50.0
Sambalpur       139.0   72.0  20898.0      93.44   85.0   49.0
Subarnapur      110.0   59.0   4204.0      84.81   85.0   44.0
Sundargarh       50.0   31.0  18166.0      86.69   98.0   76.0

                                                                2024-2025  \
               In Follow Up With Close                            Discard
                                 count percentage   mean median     count
district
Angul                              0.0       0.00    0.0    0.0    2292.0
Balangir                           0.0       0.00    0.0    0.0    5068.0
Baleswar                           0.0       0.00    0.0    0.0    4340.0
Bargarh                            0.0       0.00    0.0    0.0    1434.0
Bhadrak                            0.0       0.00    0.0    0.0    3280.0
Boudh                              0.0       0.00    0.0    0.0     760.0
Cuttack                            1.0       0.01  479.0  479.0    3701.0
Deogarh                            0.0       0.00    0.0    0.0     495.0

### Office

In [9]:
pivot_res_office = disposal_time_pivot(df_res, "office")
pivot_res_office

                         2021-2022                           \
                           Discard
                             count percentage   mean median
office
Chief Secretary              702.0      26.42   24.0    1.0
Collector                   4442.0      13.59   39.0    3.0
DG & IG Police                83.0       4.13   95.0   73.0
Departments                 3654.0      18.83  111.0   39.0
Governor                     340.0      19.99   41.0    4.0
NaN                          193.0       2.05  325.0  268.0
Office of Chief Minister    3092.0      13.39   19.0    1.0
Superintendent of Police     555.0      10.37  239.0  126.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         1501.0      56.49  306.0  222.0
Collector                               5305.0      16.23  152.0  104.0
DG & IG Police                           110.0       5.47   84.0   56.0
Departments                             2208.0      11.38  182.0  149.0
Governor                                   3.0       0.18  127.0  107.0
NaN                                     1471.0      15.66  137.0   87.0
Office of Chief Minister                 780.0       3.38  396.0  392.0
Superintendent of Police                 235.0       4.39  281.0   64.0

                                                            \
                         Disposed
                            count percentage   mean median
office
Chief Secretary             454.0      17.09  250.0  210.0
Collector                 22910.0      70.10  162.0  107.0
DG & IG Police             1817.0      90.35  156.0  106.0
Departments               13532.0      69.74  249.0  194.0
Governor                   1358.0      79.84  287.0  213.0
NaN                        7729.0      82.28  187.0  107.0
Office of Chief Minister  19222.0      83.23  288.0  237.0
Superintendent of Police   4561.0      85.19  181.0  143.0

                                                                           \
                         In Follow Up With Close
                                           count percentage   mean median
office
Chief Secretary                              0.0       0.00    0.0    0.0
Collector                                   24.0       0.07   55.0   33.0
DG & IG Police                               1.0       0.05  149.0  149.0
Departments                                 10.0       0.05  113.0   64.0
Governor                                     0.0       0.00    0.0    0.0
NaN                                          0.0       0.00    0.0    0.0
Office of Chief Minister                     0.0       0.00    0.0    0.0
Superintendent of Police                     3.0       0.06   27.0   14.0

                         2022-2023                           \
                           Discard
                             count percentage   mean median
office
Chief Secretary             1737.0      28.64    6.0    1.0
Collector                  10746.0      12.95   11.0    1.0
DG & IG Police               224.0       5.99   10.0    2.0
Departments                 6748.0      20.56   38.0    3.0
Governor                     580.0      29.44   18.0    7.0
NaN                          167.0       1.69  282.0  168.0
Office of Chief Minister    7836.0      24.92    3.0    1.0
Superintendent of Police     649.0       8.26  174.0    6.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         3814.0      62.88  174.0   75.0
Collector                              15733.0      18.96   64.0   30.0
DG & IG Police                             0.0       0.00    0.0    0.0
Departments                             1767.0       5.38  102.0   54.0
Governor                                   0.0       0.00    0.0    0.0
NaN                                     1380.0      13.96  121.0   49.0
Office of Chief Minister                1283.0       4.08  118.0   80.0
Superintendent of Police                 971.0      12.36   85.0   29.0

                                                            \
                         Disposed
                            count percentage   mean median
office
Chief Secretary             515.0       8.49   74.0   40.0
Collector                 56506.0      68.09  100.0   47.0
DG & IG Police             3514.0      94.01   88.0   43.0
Departments               24299.0      74.05  118.0   53.0
Governor                   1390.0      70.56  167.0   72.0
NaN                        8338.0      84.35  130.0   49.0
Office of Chief Minister  22326.0      71.00  106.0   46.0
Superintendent of Police   6232.0      79.36   94.0   42.0

                                                                          \
                         In Follow Up With Close
                                           count percentage  mean median
office
Chief Secretary                              0.0       0.00   0.0    0.0
Collector                                    5.0       0.01  24.0   11.0
DG & IG Police                               0.0       0.00   0.0    0.0
Departments                                  0.0       0.00   0.0    0.0
Governor                                     0.0       0.00   0.0    0.0
NaN                                          0.0       0.00   0.0    0.0
Office of Chief Minister                     0.0       0.00   0.0    0.0
Superintendent of Police                     1.0       0.01   3.0    3.0

                         2023-2024                           \
                           Discard
                             count percentage   mean median
office
Chief Secretary             3353.0      39.83    3.0    1.0
Collector                  13928.0       6.39   25.0    4.0
DG & IG Police               378.0       9.79    5.0    2.0
Departments                12830.0      25.60   24.0    3.0
Governor                     728.0      24.84   29.0    7.0
NaN                          145.0       1.71  202.0  195.0
Office of Chief Minister    6842.0      17.53    7.0    2.0
Superintendent of Police    1111.0      17.29   51.0    3.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         5003.0      59.43  177.0  106.0
Collector                              20316.0       9.32   75.0   35.0
DG & IG Police                             1.0       0.03  423.0  423.0
Departments                             1126.0       2.25  130.0   87.0
Governor                                   2.0       0.07  263.0  263.0
NaN                                     1895.0      22.34  113.0   57.0
Office of Chief Minister                 819.0       2.10  115.0   80.0
Superintendent of Police                 871.0      13.55   91.0   56.0

                                                             \
                          Disposed
                             count percentage   mean median
office
Chief Secretary               62.0       0.74  260.0  281.0
Collector                 183654.0      84.28  101.0   59.0
DG & IG Police              3484.0      90.19   77.0   49.0
Departments                36157.0      72.15  105.0   69.0
Governor                    2201.0      75.09  202.0  181.0
NaN                         6444.0      75.95  159.0   90.0
Office of Chief Minister   31367.0      80.37  153.0   95.0
Superintendent of Police    4445.0      69.16   79.0   42.0

                                                                           \
                         In Follow Up With Close
                                           count percentage   mean median
office
Chief Secretary                              0.0        0.0    0.0    0.0
Collector                                    0.0        0.0    0.0    0.0
DG & IG Police                               0.0        0.0    0.0    0.0
Departments                                  2.0        0.0  439.0  439.0
Governor                                     0.0        0.0    0.0    0.0
NaN                                          0.0        0.0    0.0    0.0
Office of Chief Minister                     0.0        0.0    0.0    0.0
Superintendent of Police                     0.0        0.0    0.0    0.0

                         2024-2025                          \
                           Discard
                             count percentage  mean median
office
Chief Secretary             4405.0      37.14  16.0    1.0
Collector                  34904.0      11.15  11.0    2.0
DG & IG Police              2741.0      73.43   3.0    2.0
Departments                48131.0      37.97  49.0    5.0
Governor                    2022.0      30.35  28.0   16.0
NaN                          164.0       1.44  43.0   21.0
Office of Chief Minister    8655.0       8.94  30.0   10.0
Superintendent of Police    5806.0      53.88  17.0    3.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         7162.0      60.38  129.0  128.0
Collector                              10632.0       3.40   50.0   30.0
DG & IG Police                             6.0       0.16  129.0  132.0
Departments                             2735.0       2.16   61.0   39.0
Governor                                   1.0       0.02  128.0  128.0
NaN                                     2421.0      21.24   76.0   52.0
Office of Chief Minister                 327.0       0.34   68.0   56.0
Superintendent of Police                1898.0      17.61   40.0   24.0

                                                             \
                          Disposed
                             count percentage   mean median
office
Chief Secretary              295.0       2.49  144.0  142.0
Collector                 267539.0      85.46   48.0   29.0
DG & IG Police               986.0      26.41   83.0   41.0
Departments                75873.0      59.85  103.0   79.0
Governor                    4640.0      69.64  123.0  118.0
NaN                         8815.0      77.32   89.0   63.0
Office of Chief Minister   87864.0      90.72   69.0   53.0
Superintendent of Police    3071.0      28.50   60.0   39.0

                                                                           \
                         In Follow Up With Close
                                           count percentage   mean median
office
Chief Secretary                              0.0       0.00    0.0    0.0
Collector                                    0.0       0.00    0.0    0.0
DG & IG Police                               0.0       0.00    0.0    0.0
Departments                                 34.0       0.03  147.0  185.0
Governor                                     0.0       0.00    0.0    0.0
NaN                                          0.0       0.00    0.0    0.0
Office of Chief Minister                     1.0       0.00   20.0   20.0
Superintendent of Police                     0.0       0.00    0.0    0.0

                         Aggregate                           \
                           Discard
                             count percentage   mean median
office
Chief Secretary            10197.0      35.16   11.0    1.0
Collector                  64020.0       9.90   16.0    2.0
DG & IG Police              3426.0      25.67    5.0    2.0
Departments                71363.0      31.15   46.0    4.0
Governor                    3670.0      27.67   28.0    9.0
NaN                          669.0       1.71  218.0  124.0
Office of Chief Minister   26425.0      13.88   15.0    2.0
Superintendent of Police    8121.0      26.71   49.0    3.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                        17480.0      60.27  168.0  117.0
Collector                              51986.0       8.04   75.0   35.0
DG & IG Police                           117.0       0.88   89.0   56.0
Departments                             7836.0       3.42  114.0   67.0
Governor                                   6.0       0.05  172.0  148.0
NaN                                     7167.0      18.30  107.0   59.0
Office of Chief Minister                3209.0       1.69  180.0  113.0
Superintendent of Police                3975.0      13.07   76.0   32.0

                                                             \
                          Disposed
                             count percentage   mean median
office
Chief Secretary             1326.0       4.57  158.0  130.0
Collector                 530609.0      82.06   77.0   41.0
DG & IG Police              9801.0      73.44   96.0   55.0
Departments               149861.0      65.41  119.0   77.0
Governor                    9589.0      72.29  171.0  132.0
NaN                        31326.0      79.99  139.0   74.0
Office of Chief Minister  160779.0      84.44  117.0   64.0
Superintendent of Police   18309.0      60.21  106.0   51.0


                         In Follow Up With Close
                                           count percentage   mean median
office
Chief Secretary                              0.0       0.00    0.0    0.0
Collector                                   29.0       0.00   50.0   32.0
DG & IG Police                               1.0       0.01  149.0  149.0
Departments                                 46.0       0.02  153.0  178.0
Governor                                     0.0       0.00    0.0    0.0
NaN                                          0.0       0.00    0.0    0.0
Office of Chief Minister                     1.0       0.00   20.0   20.0
Superintendent of Police                     4.0       0.01   21.0   12.0

### Department

In [10]:
pivot_res_dept = disposal_time_pivot(df_res, "dept")
pivot_res_dept

                                                   2021-2022             \
                                                     Discard
                                                       count percentage
dept
Agriculture & Farmers' Empowerment                      75.0       3.49
Co-operation                                             7.0       2.28
Commerce & Transport                                    12.0       3.08
Electronics & Information Technology                     4.0       3.92
Energy                                                  13.0       0.82
Excise                                                   2.0       0.98
Finance                                                 13.0       5.24
Fisheries & Animal Resources Development                 1.0       0.42
Food Supplies & Consumer Welfare                        43.0       1.61
Forest, Environment and Climate Change Department        7.0       2.24
General Administration & Public Grievance              176.0       8.02
Handlooms ,Textiles & Handicrafts                        1.0       3.03
Health & Family Welfare                                 81.0       1.93
Higher Education                                        70.0      12.48
Home department                                        179.0       2.00
Housing & Urban Development                            131.0       1.95
Industries                                               5.0       7.58
Information & Public Relations                          10.0      15.62
Labour & Employees' State Insurance                     12.0       2.63
Law                                                      2.0       1.90
Micro, Small & Medium Enterprise                        13.0      22.41
Mission Shakti                                           0.0       0.00
NaN                                                  11409.0      40.62
Odia Language Literature & Culture                       2.0       1.46
Panchayati Raj & Drinking Water                        289.0       1.37
Parliamentary Affairs                                    0.0       0.00
Planning & Convergence                                   1.0       2.27
Public Enterprises                                       0.0       0.00
Revenue & Disaster Management                          168.0       2.85
Rural Development                                       56.0       8.79
ST & SC Development, Minorities & Backward Clas...      54.0       8.87
School & Mass Education                                 66.0       1.84
Science & Technology                                     0.0       0.00
Skill Development & Technical Education                 10.0       4.31
Social Security & Empowerment of Persons with D...      73.0       3.53
Sports & Youth Services                                  1.0       2.00
Steel & Mines                                            6.0       8.45
Tourism                                                  3.0       7.50
Water Resources                                         15.0       2.01
Women & Child Development                                7.0       0.97
Works                                                   44.0       9.40

                                                                  \

                                                     mean median
dept
Agriculture & Farmers' Empowerment                   85.0   25.0
Co-operation                                        251.0  243.0
Commerce & Transport                                158.0  151.0
Electronics & Information Technology                222.0  152.0
Energy                                              188.0   69.0
Excise                                               70.0   70.0
Finance                                             529.0  526.0
Fisheries & Animal Resources Development             29.0   29.0
Food Supplies & Consumer Welfare                    254.0  198.0
Forest, Environment and Climate Change Department   252.0  285.0
General Administration & Public Grievance           130.0  101.0
Handlooms ,Textiles & Handicrafts                   201.0  201.0
Health & Family Welfare                             414.0  426.0
Higher Education                                    629.0  692.0
Home department                                     185.0  139.0
Housing & Urban Development                         210.0  166.0
Industries                                           90.0   98.0
Information & Public Relations                      113.0   71.0
Labour & Employees' State Insurance                 174.0  107.0
Law                                                 348.0  348.0
Micro, Small & Medium Enterprise                    325.0  325.0
Mission Shakti                                        0.0    0.0
NaN                                                  43.0    2.0
Odia Language Literature & Culture                  167.0  167.0
Panchayati Raj & Drinking Water                     189.0  134.0
Parliamentary Affairs                                 0.0    0.0
Planning & Convergence                              121.0  121.0
Public Enterprises                                    0.0    0.0
Revenue & Disaster Management                       192.0  189.0
Rural Development                                   120.0   49.0
ST & SC Development, Minorities & Backward Clas...  454.0  456.0
School & Mass Education                             350.0  230.0
Science & Technology                                  0.0    0.0
Skill Development & Technical Education             433.0  420.0
Social Security & Empowerment of Persons with D...  231.0  190.0
Sports & Youth Services                             243.0  243.0
Steel & Mines                                       105.0  100.0
Tourism                                             308.0  330.0
Water Resources                                     322.0  121.0
Women & Child Development                           206.0   53.0
Works                                               184.0  140.0

                                                                          \
                                                   Disposed with Benefit
                                                                   count
dept
Agriculture & Farmers' Empowerment                                 162.0
Co-operation                                                        19.0
Commerce & Transport                                                31.0
Electronics & Information Technology                                 7.0
Energy                                                             419.0
Excise                                                               5.0
Finance                                                             40.0
Fisheries & Animal Resources Development                            41.0
Food Supplies & Consumer Welfare                                   638.0
Forest, Environment and Climate Change Department                   34.0
General Administration & Public Grievance                          288.0
Handlooms ,Textiles & Handicrafts                                   13.0
Health & Family Welfare                                            544.0
Higher Education                                                    66.0
Home department                                                   1708.0
Housing & Urban Development                                       1114.0
Industries                                                           9.0
Information & Public Relations                                      14.0
Labour & Employees' State Insurance                                 43.0
Law                                                                  8.0
Micro, Small & Medium Enterprise                                     3.0
Mission Shakti                                                       4.0
NaN                                                               1379.0
Odia Language Literature & Culture                                   8.0
Panchayati Raj & Drinking Water                                   2960.0
Parliamentary Affairs                                                1.0
Planning & Convergence                                              14.0
Public Enterprises                                                   1.0
Revenue & Disaster Management                                      929.0
Rural Development                                                   66.0
ST & SC Development, Minorities & Backward Clas...                  65.0
School & Mass Education                                            372.0
Science & Technology                                                 0.0
Skill Development & Technical Education                             30.0
Social Security & Empowerment of Persons with D...                 242.0
Sports & Youth Services                                              4.0
Steel & Mines                                                        2.0
Tourism                                                              9.0
Water Resources                                                    177.0
Women & Child Development                                           50.0
Works                                                               94.0

                                                                             \

                                                   percentage   mean median
dept
Agriculture & Farmers' Empowerment                       7.54  151.0  112.0
Co-operation                                             6.19  422.0  458.0
Commerce & Transport                                     7.95  153.0  147.0
Electronics & Information Technology                     6.86  161.0  169.0
Energy                                                  26.57  124.0   63.0
Excise                                                   2.44  216.0  191.0
Finance                                                 16.13  391.0  298.0
Fisheries & Animal Resources Development                17.15  215.0  108.0
Food Supplies & Consumer Welfare                        23.94  143.0  101.0
Forest, Environment and Climate Change Department       10.86  339.0  228.0
General Administration & Public Grievance               13.12  139.0   77.0
Handlooms ,Textiles & Handicrafts                       39.39  247.0  321.0
Health & Family Welfare                                 12.99  272.0  261.0
Higher Education                                        11.76  460.0  483.0
Home department                                         19.04  149.0   99.0
Housing & Urban Development                             16.55  147.0   93.0
Industries                                              13.64  271.0  232.0
Information & Public Relations                          21.88  103.0   85.0
Labour & Employees' State Insurance                      9.43  189.0  157.0
Law                                                      7.62  257.0  162.0
Micro, Small & Medium Enterprise                         5.17  474.0  457.0
Mission Shakti                                           5.26  297.0  228.0
NaN                                                      4.91  402.0  368.0
Odia Language Literature & Culture                       5.84  393.0  300.0
Panchayati Raj & Drinking Water                         13.99  149.0  105.0
Parliamentary Affairs                                    5.88  275.0  275.0
Planning & Convergence                                  31.82  188.0  178.0
Public Enterprises                                       8.33  517.0  517.0
Revenue & Disaster Management                           15.76  119.0   80.0
Rural Development                                       10.36  200.0  137.0
ST & SC Development, Minorities & Backward Clas...      10.67  250.0  113.0
School & Mass Education                                 10.34  251.0  154.0
Science & Technology                                     0.00    0.0    0.0
Skill Development & Technical Education                 12.93  418.0  419.0
Social Security & Empowerment of Persons with D...      11.70  172.0  125.0
Sports & Youth Services                                  8.00   83.0   26.0
Steel & Mines                                            2.82  217.0  217.0
Tourism                                                 22.50  285.0  192.0
Water Resources                                         23.73  366.0  337.0
Women & Child Development                                6.90  130.0  109.0
Works                                                   20.09  181.0  134.0

                                                                               \
                                                   Disposed
                                                      count percentage   mean
dept
Agriculture & Farmers' Empowerment                   1911.0      88.97   92.0
Co-operation                                          281.0      91.53  415.0
Commerce & Transport                                  345.0      88.46  293.0
Electronics & Information Technology                   91.0      89.22  188.0
Energy                                               1144.0      72.54  125.0
Excise                                                197.0      96.10  186.0
Finance                                               195.0      78.63  365.0
Fisheries & Animal Resources Development              197.0      82.43  152.0
Food Supplies & Consumer Welfare                     1983.0      74.41  183.0
Forest, Environment and Climate Change Department     272.0      86.90  254.0
General Administration & Public Grievance            1728.0      78.72  186.0
Handlooms ,Textiles & Handicrafts                      19.0      57.58  232.0
Health & Family Welfare                              3564.0      85.08  245.0
Higher Education                                      424.0      75.58  482.0
Home department                                      7082.0      78.93  171.0
Housing & Urban Development                          5484.0      81.49  187.0
Industries                                             52.0      78.79  220.0
Information & Public Relations                         40.0      62.50  142.0
Labour & Employees' State Insurance                   400.0      87.72  206.0
Law                                                    95.0      90.48  344.0
Micro, Small & Medium Enterprise                       42.0      72.41  381.0
Mission Shakti                                         72.0      94.74  127.0
NaN                                                 15296.0      54.46  340.0
Odia Language Literature & Culture                    127.0      92.70  450.0
Panchayati Raj & Drinking Water                     17903.0      84.62  153.0
Parliamentary Affairs                                  16.0      94.12  188.0
Planning & Convergence                                 29.0      65.91  232.0
Public Enterprises                                     11.0      91.67   88.0
Revenue & Disaster Management                        4789.0      81.22  158.0
Rural Development                                     514.0      80.69  197.0
ST & SC Development, Minorities & Backward Clas...    490.0      80.46  252.0
School & Mass Education                              3151.0      87.63  302.0
Science & Technology                                    7.0     100.00  248.0
Skill Development & Technical Education               192.0      82.76  542.0
Social Security & Empowerment of Persons with D...   1752.0      84.72  171.0
Sports & Youth Services                                45.0      90.00  132.0
Steel & Mines                                          63.0      88.73  199.0
Tourism                                                28.0      70.00  313.0
Water Resources                                       554.0      74.26  329.0
Women & Child Development                             668.0      92.14  174.0
Works                                                 330.0      70.51  221.0

                                                           \

                                                   median
dept
Agriculture & Farmers' Empowerment                   47.0
Co-operation                                        426.0
Commerce & Transport                                265.0
Electronics & Information Technology                171.0
Energy                                               56.0
Excise                                              193.0
Finance                                             364.0
Fisheries & Animal Resources Development            112.0
Food Supplies & Consumer Welfare                    127.0
Forest, Environment and Climate Change Department   218.0
General Administration & Public Grievance            97.0
Handlooms ,Textiles & Handicrafts                   241.0
Health & Family Welfare                             160.0
Higher Education                                    524.0
Home department                                     107.0
Housing & Urban Development                         111.0
Industries                                           95.0
Information & Public Relations                       99.0
Labour & Employees' State Insurance                 173.0
Law                                                 363.0
Micro, Small & Medium Enterprise                    319.0
Mission Shakti                                      112.0
NaN                                                 296.0
Odia Language Literature & Culture                  410.0
Panchayati Raj & Drinking Water                     107.0
Parliamentary Affairs                               117.0
Planning & Convergence                              140.0
Public Enterprises                                   32.0
Revenue & Disaster Management                       117.0
Rural Development                                   111.0
ST & SC Development, Minorities & Backward Clas...  183.0
School & Mass Education                             216.0
Science & Technology                                207.0
Skill Development & Technical Education             506.0
Social Security & Empowerment of Persons with D...  110.0
Sports & Youth Services                              99.0
Steel & Mines                                       143.0
Tourism                                             257.0
Water Resources                                     166.0
Women & Child Development                           109.0
Works                                               156.0

                                                                            \
                                                   In Follow Up With Close
                                                                     count
dept
Agriculture & Farmers' Empowerment                                     0.0
Co-operation                                                           0.0
Commerce & Transport                                                   2.0
Electronics & Information Technology                                   0.0
Energy                                                                 1.0
Excise                                                                 1.0
Finance                                                                0.0
Fisheries & Animal Resources Development                               0.0
Food Supplies & Consumer Welfare                                       1.0
Forest, Environment and Climate Change Department                      0.0
General Administration & Public Grievance                              3.0
Handlooms ,Textiles & Handicrafts                                      0.0
Health & Family Welfare                                                0.0
Higher Education                                                       1.0
Home department                                                        3.0
Housing & Urban Development                                            1.0
Industries                                                             0.0
Information & Public Relations                                         0.0

### Category

In [11]:
pivot_res_category = disposal_time_pivot(df_res, "category")
pivot_res_category

                            2021-2022                           \
                              Discard
                                count percentage   mean median
category
Accident                          1.0       7.69  243.0  243.0
Agriculture & Farming            25.0       2.47  199.0   62.0
BSKY                              0.0       0.00    0.0    0.0
CMRF                              3.0       0.58  411.0  460.0
COVID-19                          6.0       3.66  235.0  147.0
Culture                           0.0       0.00    0.0    0.0
Disaster Management               0.0       0.00    0.0    0.0
Education                        66.0       6.48  530.0  546.0
Energy                           26.0       1.38  200.0  166.0
Environment                       0.0       0.00    0.0    0.0
Excise                            1.0       0.52  121.0  121.0
Financial Assistance             17.0       2.31  214.0  187.0
General                         268.0       2.30  222.0  166.0
Health Care                      53.0       2.11  375.0  348.0
Housing                         161.0       1.19  125.0   80.0
ICDS                              2.0       0.92   50.0   50.0
Infrastructure                  117.0       4.68  200.0  105.0
Irrigation                        0.0       0.00    0.0    0.0
Land Matters                     68.0       2.57  153.0  132.0
Legal                             0.0       0.00    0.0    0.0
Miscellaneous                   157.0       4.13  180.0  120.0
NaN                           11621.0      37.81   49.0    2.0
Pension/Retirement Benefits      30.0       2.40  243.0  125.0
Police Case                      99.0       1.73  130.0  101.0
Public Utility                   24.0       2.33  195.0  141.0
Scheme &amp;amp; Benefits         0.0       0.00    0.0    0.0
School & College                  7.0       2.55  559.0  781.0
Service Matters                 118.0       3.44  241.0  153.0
Social Welfare                  148.0       1.90  181.0   98.0
Sports                            1.0       2.44  243.0  243.0
Tourism                           0.0       0.00    0.0    0.0
Traffic                           0.0       0.00    0.0    0.0
Transport                         6.0       2.52  201.0  194.0
Waste Management                  9.0       3.45  241.0  271.0
Water Supply                     26.0       0.96  254.0  216.0
Women Issues                      1.0       1.05  201.0  201.0

                                                                            \
                            Disposed with Benefit
                                            count percentage   mean median
category
Accident                                      3.0      23.08  148.0  174.0
Agriculture & Farming                        77.0       7.59  232.0  193.0
BSKY                                          4.0       7.27  166.0   42.0
CMRF                                        165.0      31.91  294.0  286.0
COVID-19                                     31.0      18.90  227.0   99.0
Culture                                       1.0       7.69   58.0   58.0
Disaster Management                          24.0      27.91  106.0  100.0
Education                                    92.0       9.03  294.0  110.0
Energy                                      512.0      27.18  131.0   80.0
Environment                                   7.0       4.49  201.0   46.0
Excise                                        4.0       2.09  151.0  179.0
Financial Assistance                         94.0      12.77  276.0  264.0
General                                    2723.0      23.40  152.0   79.0
Health Care                                 221.0       8.80  233.0  147.0
Housing                                     948.0       7.01  121.0   97.0
ICDS                                          5.0       2.30  111.0   91.0
Infrastructure                              334.0      13.35  219.0  165.0
Irrigation                                    0.0       0.00    0.0    0.0
Land Matters                                331.0      12.53  105.0   58.0
Legal                                         1.0       7.14  194.0  194.0
Miscellaneous                               658.0      17.33  183.0  143.0
NaN                                        1756.0       5.71  376.0  324.0
Pension/Retirement Benefits                 695.0      55.51  132.0   80.0
Police Case                                1090.0      19.06  138.0   80.0
Public Utility                               84.0       8.15  263.0  269.0
Scheme &amp;amp; Benefits                     0.0       0.00    0.0    0.0
School & College                             14.0       5.09  175.0  125.0
Service Matters                             382.0      11.13  281.0  272.0
Social Welfare                              585.0       7.51  172.0  138.0
Sports                                        1.0       2.44  258.0  258.0
Tourism                                       0.0       0.00    0.0    0.0
Traffic                                       4.0      19.05  137.0  141.0
Transport                                    12.0       5.04  127.0  148.0
Waste Management                             94.0      36.02  103.0   92.0
Water Supply                                653.0      24.17  150.0   92.0
Women Issues                                  8.0       8.42  227.0  163.0

                                                               \
                            Disposed
                               count percentage   mean median
category
Accident                         9.0      69.23  157.0  113.0
Agriculture & Farming          912.0      89.94  187.0  109.0
BSKY                            51.0      92.73  231.0  200.0
CMRF                           349.0      67.50  293.0  269.0
COVID-19                       127.0      77.44  255.0  241.0
Culture                         12.0      92.31  131.0   39.0
Disaster Management             62.0      72.09  169.0  145.0
Education                      859.0      84.30  325.0  226.0
Energy                        1345.0      71.39  151.0   82.0
Environment                    149.0      95.51  203.0  147.0
Excise                         185.0      96.86  180.0  193.0
Financial Assistance           625.0      84.92  230.0  142.0
General                       8634.0      74.19  204.0  132.0
Health Care                   2237.0      89.09  192.0  105.0
Housing                      12410.0      91.78  129.0   93.0
ICDS                           210.0      96.77  180.0  120.0
Infrastructure                2050.0      81.93  240.0  160.0
Irrigation                       0.0       0.00    0.0    0.0
Land Matters                  2240.0      84.82  144.0  103.0
Legal                           13.0      92.86  234.0   69.0
Miscellaneous                 2982.0      78.54  229.0  161.0
NaN                          17359.0      56.47  346.0  300.0
Pension/Retirement Benefits    524.0      41.85  270.0  182.0
Police Case                   4528.0      79.16  146.0   91.0
Public Utility                 921.0      89.33  259.0  174.0
Scheme &amp;amp; Benefits        1.0     100.00  186.0  186.0
School & College               254.0      92.36  247.0  148.0
Service Matters               2931.0      85.40  246.0  167.0
Social Welfare                7055.0      90.55  142.0   80.0
Sports                          39.0      95.12  134.0   85.0
Tourism                          7.0     100.00  207.0   60.0
Traffic                         17.0      80.95   93.0   44.0
Transport                      219.0      92.02  301.0  281.0
Waste Management               158.0      60.54  213.0  207.0
Water Supply                  2023.0      74.87  184.0  113.0
Women Issues                    86.0      90.53  168.0   72.0

                                                                              \
                            In Follow Up With Close
                                              count percentage   mean median
category
Accident                                        0.0       0.00    0.0    0.0
Agriculture & Farming                           0.0       0.00    0.0    0.0
BSKY                                            0.0       0.00    0.0    0.0
CMRF                                            0.0       0.00    0.0    0.0
COVID-19                                        0.0       0.00    0.0    0.0
Culture                                         0.0       0.00    0.0    0.0
Disaster Management                             0.0       0.00    0.0    0.0
Education                                       2.0       0.20   42.0   42.0
Energy                                          1.0       0.05   74.0   74.0
Environment                                     0.0       0.00    0.0    0.0
Excise                                          1.0       0.52  152.0  152.0
Financial Assistance                            0.0       0.00    0.0    0.0
General                                        13.0       0.11   41.0   27.0
Health Care                                     0.0       0.00    0.0    0.0
Housing                                         2.0       0.01   14.0   14.0
ICDS                                            0.0       0.00    0.0    0.0
Infrastructure                                  1.0       0.04   16.0   16.0
Irrigation                                      0.0       0.00    0.0    0.0
Land Matters                                    2.0       0.08   85.0   85.0
Legal                                           0.0       0.00    0.0    0.0
Miscellaneous                                   0.0       0.00    0.0    0.0
NaN                                             3.0       0.01  249.0  235.0
Pension/Retirement Benefits                     3.0       0.24   25.0   12.0
Police Case                                     3.0       0.05   65.0   34.0
Public Utility                                  2.0       0.19  151.0  151.0
Scheme &amp;amp; Benefits                       0.0       0.00    0.0    0.0
School & College                                0.0       0.00    0.0    0.0
Service Matters                                 1.0       0.03   50.0   50.0
Social Welfare                                  3.0       0.04   77.0   88.0
Sports                                          0.0       0.00    0.0    0.0
Tourism                                         0.0       0.00    0.0    0.0
Traffic                                         0.0       0.00    0.0    0.0
Transport                                       1.0       0.42   32.0   32.0
Waste Management                                0.0       0.00    0.0    0.0
Water Supply                                    0.0       0.00    0.0    0.0
Women Issues                                    0.0       0.00    0.0    0.0

                            2022-2023                           \
                              Discard
                                count percentage   mean median
category
Accident                          0.0       0.00    0.0    0.0
Agriculture & Farming            18.0       1.26  203.0  133.0
BSKY                              2.0       1.92  251.0  251.0
CMRF                              0.0       0.00    0.0    0.0
COVID-19                          1.0       1.56  732.0  732.0
Culture                           0.0       0.00    0.0    0.0
Disaster Management               4.0       2.92  262.0  104.0
Education                       120.0       8.28  311.0  273.0
Energy                           29.0       1.01  180.0   26.0
Environment                       0.0       0.00    0.0    0.0
Excise                            3.0       1.33   17.0   14.0
Financial Assistance             20.0       0.84  140.0   25.0
General                         401.0       1.41  206.0  118.0
Health Care                      33.0       1.15  277.0  168.0
Housing                         149.0       0.40   51.0   25.0
ICDS                             10.0       2.84  173.0  209.0
Infrastructure                  306.0       5.77   81.0   26.0
Irrigation                        0.0       0.00    0.0    0.0
Land Matters                     89.0       1.18   75.0   27.0
Legal                             1.0       4.35  343.0  343.0
Miscellaneous                   243.0       2.03  105.0   37.0
NaN                           26689.0     100.00   11.0    1.0
Pension/Retirement Benefits      32.0       2.23  203.0  152.0
Police Case                     130.0       1.17  129.0   36.0
Public Utility                   23.0       1.00  221.0   84.0
Scheme &amp;amp; Benefits         0.0       0.00    0.0    0.0
School & College                  2.0       0.26  252.0  252.0
Service Matters                 184.0       3.75  186.0  150.0
Social Welfare                  151.0       0.68   91.0   35.0
Sports                            8.0       6.61   21.0   12.0
Tourism                           0.0       0.00    0.0    0.0
Traffic                           1.0       2.50   10.0   10.0
Transport                         4.0       0.96  338.0  321.0
Waste Management                  3.0       1.35   22.0   32.0
Water Supply                     31.0       0.95  221.0  130.0
Women Issues                      0.0       0.00    0.0    0.0

                                                                            \
                            Disposed with Benefit
                                            count percentage   mean median
category
Accident                                      6.0      17.14   27.0   23.0
Agriculture & Farming                       141.0       9.85  120.0   94.0
BSKY                                          7.0       6.73   69.0   59.0
CMRF                                        148.0      30.27  119.0  107.0
COVID-19                                      8.0      12.50   84.0   39.0
Culture                                       1.0      20.00  420.0  420.0
Disaster Management                          14.0      10.22   49.0   35.0
Education                                   175.0      12.07  183.0  114.0
Energy                                      568.0      19.72  107.0   45.0
Environment                                  12.0       6.74  186.0  153.0
Excise                                       11.0       4.87  109.0  109.0
Financial Assistance                        568.0      23.98  114.0   70.0
General                                    7194.0      25.22  128.0   47.0
Health Care                                 349.0      12.17  105.0   42.0
Housing                                    7754.0      20.83   44.0   24.0
ICDS                                         13.0       3.69  123.0   28.0
Infrastructure                              544.0      10.25  141.0   62.0
Irrigation                                    5.0      15.15  619.0  616.0
Land Matters                               1194.0      15.83   66.0   34.0
Legal                                         3.0      13.04   61.0    9.0
Miscellaneous                              1412.0      11.80   79.0   35.0
NaN                                           0.0       0.00    0.0    0.0
Pension/Retirement Benefits                 259.0      18.06  115.0   42.0
Police Case                                1312.0      11.83   80.0   34.0
Public Utility                              190.0       8.30  103.0   59.0
Scheme &amp;amp; Benefits                     0.0       0.00    0.0    0.0
School & College                             94.0      12.45  151.0   92.0
Service Matters                             788.0      16.08  142.0   60.0
Social Welfare                             1363.0       6.16   84.0   50.0
Sports                                        3.0       2.48   85.0   74.0
Tourism                                       0.0       0.00    0.0    0.0
Traffic                                       4.0      10.00  148.0   55.0
Transport                                     3.0       0.72   20.0   29.0
Waste Management                             86.0      38.57   40.0   13.0
Water Supply                                694.0      21.22  131.0   63.0
Women Issues                                 25.0      15.34   66.0   36.0

                                                               \
                            Disposed
                               count percentage   mean median
category
Accident                        29.0      82.86  107.0   66.0
Agriculture & Farming         1272.0      88.83  171.0   71.0
BSKY                            95.0      91.35   86.0   69.0
CMRF                           341.0      69.73  128.0  105.0
COVID-19                        55.0      85.94  153.0   93.0
Culture                          4.0      80.00  127.0   90.0
Disaster Management            119.0      86.86  111.0   44.0
Education                     1155.0      79.66  211.0  138.0
Energy                        2282.0      79.21  113.0   36.0
Environment                    166.0      93.26  123.0   62.0
Excise                         212.0      93.81   88.0   55.0
Financial Assistance          1781.0      75.18  155.0   67.0
General                      20928.0      73.37  141.0   60.0
Health Care                   2485.0      86.68  108.0   39.0
Housing                      29330.0      78.77   74.0   45.0
ICDS                           329.0      93.47  120.0   69.0
Infrastructure                4455.0      83.98  151.0   54.0
Irrigation                      28.0      84.85  582.0  658.0
Land Matters                  6258.0      82.99   92.0   41.0
Legal                           19.0      82.61  150.0   92.0
Miscellaneous                10313.0      86.17  129.0   63.0
NaN                              0.0       0.00    0.0    0.0
Pension/Retirement Benefits   1143.0      79.71  156.0   81.0
Police Case                   9648.0      86.99   75.0   37.0
Public Utility                2077.0      90.70  175.0   82.0
Scheme &amp;amp; Benefits        0.0       0.00    0.0    0.0
School & College               659.0      87.28  165.0   81.0
Service Matters               3930.0      80.17  169.0   94.0
Social Welfare               20630.0      93.16   72.0   34.0
Sports                         110.0      90.91   41.0   17.0
Tourism                          7.0     100.00  139.0   50.0
Traffic                         35.0      87.50  197.0   83.0
Transport                      408.0      98.31  121.0   79.0
Waste Management               134.0      60.09  106.0   40.0
Water Supply                  2545.0      77.83  159.0   64.0
Women Issues                   138.0      84.66   90.0   37.0

                                                                             \
                            In Follow Up With Close
                                              count percentage  mean median
category
Accident                                        0.0       0.00   0.0    0.0
Agriculture & Farming                           1.0       0.07  51.0   51.0
BSKY                                            0.0       0.00   0.0    0.0
CMRF                                            0.0       0.00   0.0    0.0
COVID-19                                        0.0       0.00   0.0    0.0
Culture                                         0.0       0.00   0.0    0.0
Disaster Management                             0.0       0.00   0.0    0.0
Education                                       0.0       0.00   0.0    0.0
Energy                                          2.0       0.07   3.0    3.0
Environment                                     0.0       0.00   0.0    0.0
Excise                                          0.0       0.00   0.0    0.0
Financial Assistance                            0.0       0.00   0.0    0.0
General                                         1.0       0.00  52.0   52.0
Health Care                                     0.0       0.00   0.0    0.0
Housing                                         1.0       0.00  11.0   11.0
ICDS                                            0.0       0.00   0.0    0.0

### Subcategory

In [12]:
pivot_res_subcategory = disposal_time_pivot(df_res, "subcategory")
pivot_res_subcategory

                              2021-2022                           \
                                Discard
                                  count percentage   mean median
subcategory
AIDS                                0.0        0.0    0.0    0.0
Aadhar Card Issues                  0.0        0.0    0.0    0.0
Absence of officials                0.0        0.0    0.0    0.0
Absurd/Irrelevant                   0.0        0.0    0.0    0.0
Accidental Claims                   0.0        0.0    0.0    0.0
...                                 ...        ...    ...    ...
Voltage fluctuations                0.0        0.0    0.0    0.0
Water Supply issue                 11.0        4.6  282.0  215.0
Water Tanks/ Reservoirs/Ponds       0.0        0.0    0.0    0.0
Web Portal Issues                   0.0        0.0    0.0    0.0
Workplace Harrassement              0.0        0.0    0.0    0.0

                                                                              \
                              Disposed with Benefit
                                              count percentage   mean median
subcategory
AIDS                                            0.0       0.00    0.0    0.0
Aadhar Card Issues                              1.0       6.25  131.0  131.0
Absence of officials                            0.0       0.00    0.0    0.0
Absurd/Irrelevant                               1.0      20.00  152.0  152.0
Accidental Claims                               0.0       0.00    0.0    0.0
...                                             ...        ...    ...    ...
Voltage fluctuations                            3.0      15.79  260.0   46.0
Water Supply issue                             74.0      30.96  153.0  106.0
Water Tanks/ Reservoirs/Ponds                   0.0       0.00    0.0    0.0
Web Portal Issues                               3.0      20.00  123.0  100.0
Workplace Harrassement                          0.0       0.00    0.0    0.0

                                                                 \
                              Disposed
                                 count percentage   mean median
subcategory
AIDS                               0.0       0.00    0.0    0.0
Aadhar Card Issues                15.0      93.75  198.0  161.0
Absence of officials               0.0       0.00    0.0    0.0
Absurd/Irrelevant                  4.0      80.00  409.0  230.0
Accidental Claims                  5.0     100.00  164.0  153.0
...                                ...        ...    ...    ...
Voltage fluctuations              16.0      84.21  272.0  154.0
Water Supply issue               154.0      64.44  253.0  166.0
Water Tanks/ Reservoirs/Ponds      0.0       0.00    0.0    0.0
Web Portal Issues                 12.0      80.00  297.0  151.0
Workplace Harrassement             8.0     100.00  212.0  135.0

                                                                              \
                              In Follow Up With Close
                                                count percentage mean median
subcategory
AIDS                                              0.0        0.0  0.0    0.0
Aadhar Card Issues                                0.0        0.0  0.0    0.0
Absence of officials                              0.0        0.0  0.0    0.0
Absurd/Irrelevant                                 0.0        0.0  0.0    0.0
Accidental Claims                                 0.0        0.0  0.0    0.0
...                                               ...        ...  ...    ...
Voltage fluctuations                              0.0        0.0  0.0    0.0
Water Supply issue                                0.0        0.0  0.0    0.0
Water Tanks/ Reservoirs/Ponds                     0.0        0.0  0.0    0.0
Web Portal Issues                                 0.0        0.0  0.0    0.0
Workplace Harrassement                            0.0        0.0  0.0    0.0

                              2022-2023                           \
                                Discard
                                  count percentage   mean median
subcategory
AIDS                                0.0       0.00    0.0    0.0
Aadhar Card Issues                  0.0       0.00    0.0    0.0
Absence of officials                0.0       0.00    0.0    0.0
Absurd/Irrelevant                   0.0       0.00    0.0    0.0
Accidental Claims                   0.0       0.00    0.0    0.0
...                                 ...        ...    ...    ...
Voltage fluctuations                0.0       0.00    0.0    0.0
Water Supply issue                 10.0       3.56  109.0   83.0
Water Tanks/ Reservoirs/Ponds       0.0       0.00    0.0    0.0
Web Portal Issues                   1.0       7.69    1.0    1.0
Workplace Harrassement              0.0       0.00    0.0    0.0

                                                                              \
                              Disposed with Benefit
                                              count percentage   mean median
subcategory
AIDS                                            0.0       0.00    0.0    0.0
Aadhar Card Issues                              4.0      30.77   75.0   27.0
Absence of officials                            0.0       0.00    0.0    0.0
Absurd/Irrelevant                               1.0       8.33   45.0   45.0
Accidental Claims                               5.0      21.74   53.0   13.0
...                                             ...        ...    ...    ...
Voltage fluctuations                            2.0       7.69    6.0    6.0
Water Supply issue                             79.0      28.11  160.0   76.0
Water Tanks/ Reservoirs/Ponds                   0.0       0.00    0.0    0.0
Web Portal Issues                               1.0       7.69   16.0   16.0
Workplace Harrassement                          0.0       0.00    0.0    0.0

                                                                 \
                              Disposed
                                 count percentage   mean median
subcategory
AIDS                               1.0     100.00   14.0   14.0
Aadhar Card Issues                 9.0      69.23   46.0   28.0
Absence of officials               0.0       0.00    0.0    0.0
Absurd/Irrelevant                 11.0      91.67  206.0  164.0
Accidental Claims                 18.0      78.26  137.0   57.0
...                                ...        ...    ...    ...
Voltage fluctuations              24.0      92.31  114.0   30.0
Water Supply issue               192.0      68.33  259.0  111.0
Water Tanks/ Reservoirs/Ponds      2.0     100.00  326.0  326.0
Web Portal Issues                 11.0      84.62   46.0   45.0
Workplace Harrassement            17.0     100.00  162.0  117.0

                                                                              \
                              In Follow Up With Close
                                                count percentage mean median
subcategory
AIDS                                              0.0        0.0  0.0    0.0
Aadhar Card Issues                                0.0        0.0  0.0    0.0
Absence of officials                              0.0        0.0  0.0    0.0
Absurd/Irrelevant                                 0.0        0.0  0.0    0.0
Accidental Claims                                 0.0        0.0  0.0    0.0
...                                               ...        ...  ...    ...
Voltage fluctuations                              0.0        0.0  0.0    0.0
Water Supply issue                                0.0        0.0  0.0    0.0
Water Tanks/ Reservoirs/Ponds                     0.0        0.0  0.0    0.0
Web Portal Issues                                 0.0        0.0  0.0    0.0
Workplace Harrassement                            0.0        0.0  0.0    0.0

                              2023-2024                           \
                                Discard
                                  count percentage   mean median
subcategory
AIDS                                1.0      25.00  101.0  101.0
Aadhar Card Issues                  1.0       4.00   99.0   99.0
Absence of officials                0.0       0.00    0.0    0.0
Absurd/Irrelevant                   0.0       0.00    0.0    0.0
Accidental Claims                   0.0       0.00    0.0    0.0
...                                 ...        ...    ...    ...
Voltage fluctuations                0.0       0.00    0.0    0.0
Water Supply issue                 21.0       1.37  191.0  133.0
Water Tanks/ Reservoirs/Ponds       2.0       0.26   15.0   15.0
Web Portal Issues                   0.0       0.00    0.0    0.0
Workplace Harrassement              0.0       0.00    0.0    0.0

                                                                              \
                              Disposed with Benefit
                                              count percentage   mean median
subcategory
AIDS                                            1.0      25.00   31.0   31.0
Aadhar Card Issues                              4.0      16.00  201.0  197.0
Absence of officials                            1.0      50.00  506.0  506.0
Absurd/Irrelevant                               1.0      12.50    0.0    0.0
Accidental Claims                               3.0       8.82  166.0   17.0
...                                             ...        ...    ...    ...
Voltage fluctuations                           12.0      15.79   75.0   55.0
Water Supply issue                            354.0      23.11  104.0   66.0
Water Tanks/ Reservoirs/Ponds                  46.0       5.96   58.0   37.0
Web Portal Issues                               1.0       8.33   12.0   12.0
Workplace Harrassement                          1.0       5.88   65.0   65.0

                                                                 \
                              Disposed
                                 count percentage   mean median
subcategory
AIDS                               2.0      50.00  105.0  105.0
Aadhar Card Issues                20.0      80.00  287.0  305.0
Absence of officials               1.0      50.00   20.0   20.0
Absurd/Irrelevant                  7.0      87.50  194.0  151.0
Accidental Claims                 31.0      91.18  151.0   71.0
...                                ...        ...    ...    ...
Voltage fluctuations              64.0      84.21  171.0   97.0
Water Supply issue              1157.0      75.52  146.0   91.0
Water Tanks/ Reservoirs/Ponds    724.0      93.78  119.0   57.0
Web Portal Issues                 11.0      91.67  269.0  272.0
Workplace Harrassement            16.0      94.12  119.0   70.0

                                                                              \
                              In Follow Up With Close
                                                count percentage mean median
subcategory
AIDS                                              0.0        0.0  0.0    0.0
Aadhar Card Issues                                0.0        0.0  0.0    0.0
Absence of officials                              0.0        0.0  0.0    0.0
Absurd/Irrelevant                                 0.0        0.0  0.0    0.0
Accidental Claims                                 0.0        0.0  0.0    0.0
...                                               ...        ...  ...    ...
Voltage fluctuations                              0.0        0.0  0.0    0.0
Water Supply issue                                0.0        0.0  0.0    0.0
Water Tanks/ Reservoirs/Ponds                     0.0        0.0  0.0    0.0
Web Portal Issues                                 0.0        0.0  0.0    0.0
Workplace Harrassement                            0.0        0.0  0.0    0.0

                              2024-2025                          \
                                Discard
                                  count percentage  mean median
subcategory
AIDS                                0.0       0.00   0.0    0.0
Aadhar Card Issues                  4.0       3.70  36.0   18.0
Absence of officials                0.0       0.00   0.0    0.0
Absurd/Irrelevant                   1.0       3.03  56.0   56.0
Accidental Claims                   3.0       3.33  84.0   65.0
...                                 ...        ...   ...    ...
Voltage fluctuations                0.0       0.00   0.0    0.0
Water Supply issue                 15.0       0.71  58.0   40.0
Water Tanks/ Reservoirs/Ponds       1.0       0.68  79.0   79.0
Web Portal Issues                   1.0       2.63  45.0   45.0
Workplace Harrassement              0.0       0.00   0.0    0.0

                                                                              \
                              Disposed with Benefit
                                              count percentage   mean median
subcategory
AIDS                                            0.0       0.00    0.0    0.0
Aadhar Card Issues                              5.0       4.63   62.0   54.0
Absence of officials                            0.0       0.00    0.0    0.0
Absurd/Irrelevant                               1.0       3.03   28.0   28.0
Accidental Claims                               7.0       7.78   75.0   33.0
...                                             ...        ...    ...    ...
Voltage fluctuations                           13.0      15.12   63.0   65.0
Water Supply issue                            435.0      20.66   67.0   51.0
Water Tanks/ Reservoirs/Ponds                   1.0       0.68   89.0   89.0
Web Portal Issues                               2.0       5.26  119.0  119.0
Workplace Harrassement                          0.0       0.00    0.0    0.0

                                                                 \
                              Disposed
                                 count percentage   mean median
subcategory
AIDS                              12.0     100.00   42.0   34.0
Aadhar Card Issues                99.0      91.67   64.0   39.0
Absence of officials               0.0       0.00    0.0    0.0
Absurd/Irrelevant                 31.0      93.94  101.0   79.0
Accidental Claims                 80.0      88.89   72.0   59.0
...                                ...        ...    ...    ...
Voltage fluctuations              73.0      84.88   65.0   32.0
Water Supply issue              1656.0      78.63   76.0   58.0
Water Tanks/ Reservoirs/Ponds    145.0      98.64   69.0   43.0
Web Portal Issues                 35.0      92.11   84.0   65.0
Workplace Harrassement            31.0     100.00  107.0   80.0

                                                                              \
                              In Follow Up With Close
                                                count percentage mean median
subcategory
AIDS                                              0.0        0.0  0.0    0.0
Aadhar Card Issues                                0.0        0.0  0.0    0.0
Absence of officials                              0.0        0.0  0.0    0.0
Absurd/Irrelevant                                 0.0        0.0  0.0    0.0
Accidental Claims                                 0.0        0.0  0.0    0.0
...                                               ...        ...  ...    ...
Voltage fluctuations                              0.0        0.0  0.0    0.0
Water Supply issue                                0.0        0.0  0.0    0.0
Water Tanks/ Reservoirs/Ponds                     0.0        0.0  0.0    0.0
Web Portal Issues                                 0.0        0.0  0.0    0.0
Workplace Harrassement                            0.0        0.0  0.0    0.0

                              Aggregate                           \
                                Discard
                                  count percentage   mean median
subcategory
AIDS                                1.0       5.88  101.0  101.0
Aadhar Card Issues                  5.0       3.09   49.0   26.0
Absence of officials                0.0       0.00    0.0    0.0
Absurd/Irrelevant                   1.0       1.72   56.0   56.0
Accidental Claims                   3.0       1.97   84.0   65.0
...                                 ...        ...    ...    ...
Voltage fluctuations                0.0       0.00    0.0    0.0
Water Supply issue                 57.0       1.37  159.0  120.0
Water Tanks/ Reservoirs/Ponds       3.0       0.33   36.0   16.0
Web Portal Issues                   2.0       2.56   23.0   23.0
Workplace Harrassement              0.0       0.00    0.0    0.0

                                                                              \
                              Disposed with Benefit
                                              count percentage   mean median
subcategory
AIDS                                            1.0       5.88   31.0   31.0
Aadhar Card Issues                             14.0       8.64  110.0   95.0
Absence of officials                            1.0      50.00  506.0  506.0
Absurd/Irrelevant                               4.0       6.90   56.0   36.0
Accidental Claims                              15.0       9.87   86.0   26.0
...                                             ...        ...    ...    ...
Voltage fluctuations                           30.0      14.49   84.0   55.0
Water Supply issue                            942.0      22.66   96.0   58.0
Water Tanks/ Reservoirs/Ponds                  47.0       5.10   58.0   42.0
Web Portal Issues                               7.0       8.97   90.0   57.0
Workplace Harrassement                          1.0       1.37   65.0   65.0

                                                                 \
                              Disposed
                                 count percentage   mean median
subcategory
AIDS                              15.0      88.24   48.0   34.0
Aadhar Card Issues               143.0      88.27  108.0   60.0
Absence of officials               1.0      50.00   20.0   20.0
Absurd/Irrelevant                 53.0      91.38  158.0   93.0
Accidental Claims                134.0      88.16  102.0   64.0
...                                ...        ...    ...    ...
Voltage fluctuations             177.0      85.51  129.0   54.0
Water Supply issue              3159.0      75.97  121.0   69.0
Water Tanks/ Reservoirs/Ponds    871.0      94.57  111.0   51.0
Web Portal Issues                 69.0      88.46  144.0   69.0
Workplace Harrassement            72.0      98.63  134.0   85.0


                              In Follow Up With Close
                                                count percentage mean median
subcategory
AIDS                                              0.0        0.0  0.0    0.0
Aadhar Card Issues                                0.0        0.0  0.0    0.0
Absence of officials                              0.0        0.0  0.0    0.0
Absurd/Irrelevant                                 0.0        0.0  0.0    0.0
Accidental Claims                                 0.0        0.0  0.0    0.0
...                                               ...        ...  ...    ...
Voltage fluctuations                              0.0        0.0  0.0    0.0
Water Supply issue                                0.0        0.0  0.0    0.0
Water Tanks/ Reservoirs/Ponds                     0.0        0.0  0.0    0.0
Web Portal Issues                                 0.0        0.0  0.0    0.0
Workplace Harrassement                            0.0        0.0  0.0    0.0

[238 rows x 80 columns]

## 3. Status Group at Petitioner Level

In [ ]:
pivot_pet_status_yearly = petitioner_status_count_pivot(
    df_filtered, "custom_year")
print("\nPetitioner Status Group — Yearly:")
print(pivot_pet_status_yearly)

Petitioner Status Group — Yearly:
              Discard            Disposed with Benefit             Disposed  \
                count percentage                 count percentage     count
custom_year
2021-2022      8685.0      12.20                9298.0      13.06   51517.0
2022-2023     17848.0      13.74               19599.0      15.09   88420.0
2023-2024     25508.0       9.20               24823.0       8.96  212794.0
2024-2025     58784.0      11.68               17562.0       3.49  350752.0
Aggregate    105509.0      11.29               68113.0       7.29  667418.0

                           Open
            percentage    count percentage
custom_year
2021-2022        72.34   1717.0       2.41
2022-2023        68.09   3989.0       3.07
2023-2024        76.78  14022.0       5.06
2024-2025        69.68  76287.0      15.15
Aggregate        71.41  93560.0      10.01

In [9]:
pivot_pet_status_district = petitioner_status_count_pivot(
    df_filtered, "district")
print("\nPetitioner Status Group — District:")
pivot_pet_status_district

Petitioner Status Group — District:

               2021-2022                                                       \
                 Discard            Disposed with Benefit            Disposed
                   count percentage                 count percentage    count
district
Angul                293      14.45                   198       9.76     1511
Balangir             357      10.48                   807      23.70     2194
Baleswar             886      14.47                   260       4.25     4846
Bargarh              355      15.56                   181       7.93     1714
Bhadrak              401      11.03                   184       5.06     2866
Boudh                139      26.38                    79      14.99      304
Cuttack              469      15.93                   351      11.92     2039
Deogarh               50      10.64                    30       6.38      389
Dhenkanal            794      23.41                   113       3.33     2468
Gajapati              96       7.89                    53       4.35     1054
Ganjam               470      12.60                   411      11.02     2807
Jagatsinghapur       248       9.65                   127       4.94     2176
Jajpur               391       9.97                   157       4.00     2773
Jharsuguda            65      15.15                    55      12.82      288
Kalahandi            671       8.44                   565       7.11     6698
Kandhamal             50      10.73                    80      17.17      325
Kendrapara           268       7.10                   230       6.09     3239
Kendujhar            146       9.57                   124       8.13     1207
Khordha              783      12.15                  2594      40.24     2946
Koraput              136      16.00                   155      18.24      545
Malkangiri            41      15.47                    75      28.30      141
Mayurbhanj           201       8.45                  1118      47.01     1017
NaN                   93       7.33                   278      21.91      845
Nabarangpur           78      10.96                    80      11.24      551
Nayagarh             241      12.27                   139       7.08     1572
Nuapada               82       8.22                    78       7.82      827
Puri                 266      12.84                   256      12.36     1505
Rayagada             107      12.80                   127      15.19      583
Sambalpur            179      17.13                   105      10.05      741
Subarnapur           128      14.00                   172      18.82      602
Sundargarh           201      18.72                   116      10.80      744

                                           2022-2023             \
                           Open              Discard
               percentage count percentage     count percentage
district
Angul               74.51    26       1.28       442      18.31
Balangir            64.43    47       1.38      1444      14.97
Baleswar            79.13   132       2.16      2253      18.53
Bargarh             75.11    32       1.40       456      15.76
Bhadrak             78.82   185       5.09       538      10.58
Boudh               57.69     5       0.95       267       8.45
Cuttack             69.26    85       2.89       761      16.05
Deogarh             82.77     1       0.21        71       9.77
Dhenkanal           72.76    17       0.50      1269      34.39
Gajapati            86.61    14       1.15       478      13.61
Ganjam              75.23    43       1.15      1098      12.20
Jagatsinghapur      84.67    19       0.74       328       5.39
Jajpur              70.70   601      15.32      1224      20.51
Jharsuguda          67.13    21       4.90       211      28.13
Kalahandi           84.24    17       0.21      1132       9.89
Kandhamal           69.74    11       2.36        99      13.94
Kendrapara          85.82    37       0.98       679      12.75
Kendujhar           79.15    48       3.15       450      18.40
Khordha             45.70   124       1.92      1130      17.35
Koraput             64.12    14       1.65       283      22.16
Malkangiri          53.21     8       3.02        77      24.21
Mayurbhanj          42.77    42       1.77       380       6.74
NaN                 66.59    53       4.18        76      19.59
Nabarangpur         77.39     3       0.42       165       6.16
Nayagarh            80.04    12       0.61       605      11.87
Nuapada             82.87    11       1.10       163       6.10
Puri                72.64    45       2.17       589      10.43
Rayagada            69.74    19       2.27       246      11.97
Sambalpur           70.91    20       1.91       285      18.82
Subarnapur          65.86    12       1.31       197      10.26
Sundargarh          69.27    13       1.21       452      10.32

                                                                           \
               Disposed with Benefit            Disposed             Open
                               count percentage    count percentage count
district
Angul                            158       6.55     1738      72.00    76
Balangir                        4380      45.40     3716      38.52   108
Baleswar                         418       3.44     8986      73.91   501
Bargarh                          195       6.74     2196      75.91    46
Bhadrak                          267       5.25     4105      80.74   174
Boudh                            690      21.84     2167      68.60    35
Cuttack                          506      10.68     3306      69.75   167
Deogarh                           36       4.95      612      84.18     8
Dhenkanal                        249       6.75     2098      56.86    74
Gajapati                         105       2.99     2851      81.18    78
Ganjam                           654       7.27     7126      79.18   122
Jagatsinghapur                   192       3.16     5490      90.24    74
Jajpur                           227       3.80     3408      57.10  1109
Jharsuguda                        52       6.93      463      61.73    24
Kalahandi                       3597      31.41     6638      57.97    84
Kandhamal                         83      11.69      496      69.86    32
Kendrapara                       516       9.69     4011      75.31   120
Kendujhar                        137       5.60     1711      69.95   148
Khordha                         1361      20.89     3663      56.23   360
Koraput                          255      19.97      688      53.88    51
Malkangiri                        41      12.89      196      61.64     4
Mayurbhanj                      4113      72.96     1018      18.06   126
NaN                               40      10.31      243      62.63    29
Nabarangpur                      111       4.15     2367      88.42    34
Nayagarh                         173       3.40     4267      83.75    50
Nuapada                           80       2.99     2378      88.93    53
Puri                             285       5.05     4655      82.40   120
Rayagada                         301      14.65     1447      70.41    61
Sambalpur                        127       8.39     1061      70.08    41
Subarnapur                       110       5.73     1575      82.03    38
Sundargarh                       140       3.20     3744      85.52    42

                          2023-2024                                   \
                            Discard            Disposed with Benefit
               percentage     count percentage                 count
district
Angul                3.15       674      10.02                   279
Balangir             1.12      1691       8.03                  1750
Baleswar             4.12      1661      10.95                   651
Bargarh              1.59       682       8.97                   187
Bhadrak              3.42       907       9.85                   542
Boudh                1.11       245       6.96                   145
Cuttack              3.52      1458      14.56                  1632
Deogarh              1.10       145       5.12                   288
Dhenkanal            2.01      2833      22.89                   970
Gajapati             2.22       308       6.11                   190
Ganjam               1.36      1862       9.70                   516
Jagatsinghapur       1.22       318       5.08                   161
Jajpur              18.58      1244      13.70                   263
Jharsuguda           3.20       454      12.76                    68
Kalahandi            0.73      1249       6.57                  3376
Kandhamal            4.51       286       8.31                   154
Kendrapara           2.25       779      15.40                   790
Kendujhar            6.05       812       7.03                   181
Khordha              5.53      1449      12.13                  2176
Koraput              3.99       541      10.71                   840
Malkangiri           1.26       131       8.61                   319
Mayurbhanj           2.24      1042       6.77                  5994
NaN                  7.47       127      25.81                    29
Nabarangpur          1.27       333       6.49                   831
Nayagarh             0.98       504       7.30                   132
Nuapada              1.98       325       4.30                   345
Puri                 2.12       687       8.95                   376
Rayagada             2.97       590      18.81                    63
Sambalpur            2.71       789       4.06                   267
Subarnapur           1.98       339       9.58                    63
Sundargarh           0.96      1043       5.59                  1245

                                                               2024-2025  \
                          Disposed             Open              Discard
               percentage    count percentage count percentage     count
district
Angul                4.15     5421      80.61   351       5.22      1648
Balangir             8.31    16817      79.89   792       3.76      4332
Baleswar             4.29    10385      68.47  2470      16.29      3046
Bargarh              2.46     6529      85.87   205       2.70      1176
Bhadrak              5.89     7149      77.64   610       6.62      2339
Boudh                4.12     2837      80.64   291       8.27       613
Cuttack             16.30     6275      62.68   646       6.45      2871
Deogarh             10.17     2372      83.73    28       0.99       346
Dhenkanal            7.84     8320      67.23   253       2.04      5503
Gajapati             3.77     4353      86.32   192       3.81       797
Ganjam               2.69    16283      84.82   537       2.80      4940
Jagatsinghapur       2.57     5375      85.92   402       6.43       961
Jajpur               2.90     6170      67.95  1403      15.45      4654
Jharsuguda           1.91     2976      83.62    61       1.71       633
Kalahandi           17.75    14072      74.00   319       1.68      3036
Kandhamal            4.48     2888      83.95   112       3.26       610
Kendrapara          15.61     3039      60.06   452       8.93      1949
Kendujhar            1.57    10065      87.12   495       4.28      1643
Khordha             18.21     7336      61.40   986       8.25      3356
Koraput             16.62     3483      68.93   189       3.74       689
Malkangiri          20.97     1022      67.19    49       3.22       244
Mayurbhanj          38.94     7852      51.01   506       3.29      1560
NaN                  5.89      225      45.73   111      22.56       232
Nabarangpur         16.21     3426      66.81   538      10.49       853
Nayagarh             1.91     6055      87.75   209       3.03      4248
Nuapada              4.57     6270      83.04   611       8.09       509
Puri                 4.90     6181      80.50   434       5.65      1917
Rayagada             2.01     2376      75.74   108       3.44      1109
Sambalpur            1.37    18155      93.31   246       1.26      1010
Subarnapur           1.78     3038      85.82   100       2.82       997
Sundargarh           6.67    16049      86.04   316       1.69       963

                                                                     \
                          Disposed with Benefit            Disposed
               percentage                 count percentage    count
district
Angul               10.53                   159       1.02    11390
Balangir            18.69                   180       0.78    14894
Baleswar            11.58                   638       2.43    15670
Bargarh              5.93                   195       0.98    16688
Bhadrak              8.04                  1231       4.23    20018
Boudh                9.60                   157       2.46     4116
Cuttack             10.31                   777       2.79    20189
Deogarh              5.53                    76       1.22     5013
Dhenkanal           24.12                   346       1.52    14125
Gajapati            10.36                    68       0.88     5645
Ganjam              12.02                   645       1.57    32322
Jagatsinghapur       6.24                   203       1.32    12075
Jajpur              15.89                   348       1.19    19258
Jharsuguda          13.50                    70       1.49     3273
Kalahandi           12.91                  1220       5.19    17472
Kandhamal            6.93                   107       1.22     7057
Kendrapara          11.44                   443       2.60    11419
Kendujhar            8.96                   240       1.31    13102
Khordha             12.17                   955       3.46    18013
Koraput              8.68                   180       2.27     6035
Malkangiri           4.85                    97       1.93     4245
Mayurbhanj           7.37                  7610      35.95     9596
NaN                 21.62                    29       2.70      393
Nabarangpur          8.83                   119       1.23     7630
Nayagarh            32.12                   200       1.51     6067
Nuapada              4.80                   385       3.63     7306
Puri                 9.72                   306       1.55    14450
Rayagada            20.88                    79       1.49     3467
Sambalpur            7.12                   157       1.11    11023
Subarnapur           7.17                   136       0.98    10521
Sundargarh           8.91                   206       1.91     8280

                                           Aggregate             \
                           Open              Discard
               percentage count percentage     count percentage
district
Angul               72.79  2451      15.66      2908      11.40
Balangir            64.25  3776      16.29      7574      13.69
Baleswar            59.58  6947      26.41      7343      13.14
Bargarh             84.12  1779       8.97      2524       8.07
Bhadrak             68.85  5487      18.87      3980       9.00
Boudh               64.48  1497      23.45      1179       9.07
Cuttack             72.48  4019      14.43      5265      12.15
Deogarh             80.16   819      13.10       594       5.98
Dhenkanal           61.91  2841      12.45      9684      24.72
Gajapati            73.38  1183      15.38      1624       9.60
Ganjam              78.67  3181       7.74      7966      11.55
Jagatsinghapur      78.43  2156      14.00      1761       6.27
Jajpur              65.76  5025      17.16      7172      15.68
Jharsuguda          69.79   714      15.22      1291      14.33
Kalahandi           74.30  1789       7.61      5899      10.00
Kandhamal           80.15  1031      11.71      1012       7.80
Kendrapara          67.03  3225      18.93      3459      11.74
Kendujhar           71.48  3345      18.25      2888       9.01
Khordha             65.30  5260      19.07      6383      12.80
Koraput             75.99  1038      13.07      1585      10.89
Malkangiri          84.33   448       8.90       483       6.92
Mayurbhanj          45.33  2401      11.34      3057       7.09
NaN                 36.63   419      39.05       510      16.32
Nabarangpur         79.01  1055      10.92      1378       7.80
Nayagarh            45.88  2709      20.49      5423      20.86
Nuapada             68.92  2400      22.64      1042       4.93
Puri                73.29  3044      15.44      3271       9.83
Rayagada            65.27   657      12.37      1964      17.96
Sambalpur           77.76  1986      14.01      2164       6.22
Subarnapur          75.71  2242      16.13      1588       8.13
Sundargarh          76.58  1363      12.61      2538       7.51

                                                                           \
               Disposed with Benefit            Disposed             Open
                               count percentage    count percentage count
district
Angul                            737       2.89    19039      74.67  2815
Balangir                        6935      12.54    36197      65.45  4600
Baleswar                        1855       3.32    36934      66.11  9732
Bargarh                          677       2.17    26051      83.32  2015
Bhadrak                         2091       4.73    31805      71.96  6324
Boudh                           1021       7.85     9024      69.41  1777
Cuttack                         3122       7.20    30184      69.64  4770
Deogarh                          415       4.18     8073      81.32   846
Dhenkanal                       1553       3.96    24841      63.40  3103
Gajapati                         397       2.35    13441      79.49  1447
Ganjam                          2082       3.02    55150      79.94  3793
Jagatsinghapur                   628       2.24    23121      82.34  2570
Jajpur                           902       1.97    29791      65.14  7872
Jharsuguda                       220       2.44     6694      74.31   803
Kalahandi                       8580      14.54    42352      71.80  2159
Kandhamal                        382       2.94    10440      80.43  1147
Kendrapara                      1875       6.37    20405      69.28  3716
Kendujhar                        615       1.92    24613      76.75  3952
Khordha                         6823      13.68    30159      60.47  6508
Koraput                         1336       9.18    10384      71.34  1250
Malkangiri                       510       7.31     5484      78.60   500
Mayurbhanj                     18083      41.92    18976      44.00  3016
NaN                              365      11.68     1652      52.86   598
Nabarangpur                     1115       6.31    13561      76.75  1615
Nayagarh                         593       2.28    17030      65.52  2945
Nuapada                          857       4.05    16213      76.68  3032
Puri                            1093       3.28    25391      76.30  3523
Rayagada                         549       5.02     7598      69.47   826
Sambalpur                        601       1.73    29773      85.60  2245
Subarnapur                       444       2.27    15152      77.53  2359
Sundargarh                      1657       4.90    27890      82.55  1702



               percentage
district
Angul               11.04
Balangir             8.32
Baleswar            17.42
Bargarh              6.44
Bhadrak             14.31
Boudh               13.67
Cuttack             11.01
Deogarh              8.52
Dhenkanal            7.92
Gajapati             8.56
Ganjam               5.50
Jagatsinghapur       9.15
Jajpur              17.21
Jharsuguda           8.91
Kalahandi            3.66
Kandhamal            8.84
Kendrapara          12.62
Kendujhar           12.32
Khordha             13.05
Koraput              8.59
Malkangiri           7.17
Mayurbhanj           6.99
NaN                 19.14
Nabarangpur          9.14
Nayagarh            11.33
Nuapada             14.34
Puri                10.59

In [10]:
pivot_pet_status_office = petitioner_status_count_pivot(
    df_filtered, "office")
print("\nPetitioner Status Group — Office:")
pivot_pet_status_office

Petitioner Status Group — Office:

                         2021-2022                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary              526.0      24.96                1127.0
Collector                   3716.0      12.84                4913.0
DG & IG Police                75.0       4.17                 100.0
Departments                 2673.0      18.56                1742.0
Governor                     242.0      17.32                   3.0
NaN                          148.0       4.62                 739.0
Office of Chief Minister    1959.0       9.80                 758.0
Superintendent of Police     462.0       8.58                 214.0

                                                                           \
                                    Disposed              Open
                         percentage    count percentage  count percentage
office
Chief Secretary               53.49    396.0      18.79   58.0       2.75
Collector                     16.98  20143.0      69.61  167.0       0.58
DG & IG Police                 5.56   1600.0      88.89   25.0       1.39
Departments                   12.10   9702.0      67.38  282.0       1.96
Governor                       0.21   1115.0      79.81   37.0       2.65
NaN                           23.08   2164.0      67.58  151.0       4.72
Office of Chief Minister       3.79  17007.0      85.09  262.0       1.31
Superintendent of Police       3.98   3920.0      72.84  786.0      14.60

                         2022-2023                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary             1118.0      28.51                2178.0
Collector                   8194.0      11.31               13866.0
DG & IG Police               173.0       5.85                   0.0
Departments                 4725.0      19.82                1392.0
Governor                     401.0      27.43                   0.0
NaN                          142.0       4.15                 725.0
Office of Chief Minister    5469.0      21.43                1183.0
Superintendent of Police     536.0       7.05                 879.0

                                                                            \
                                    Disposed               Open
                         percentage    count percentage   count percentage
office
Chief Secretary               55.53    421.0      10.73   205.0       5.23
Collector                     19.14  49465.0      68.30   902.0       1.25
DG & IG Police                 0.00   2697.0      91.27    85.0       2.88
Departments                    5.84  16820.0      70.56   901.0       3.78
Governor                       0.00    997.0      68.19    64.0       4.38
NaN                           21.20   2237.0      65.41   316.0       9.24
Office of Chief Minister       4.63  18437.0      72.23   436.0       1.71
Superintendent of Police      11.56   4919.0      64.67  1272.0      16.72

                         2023-2024                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary             2082.0      38.87                2758.0
Collector                  11432.0       5.77               19031.0
DG & IG Police               247.0       5.09                   1.0
Departments                 9300.0      23.21                 978.0
Governor                     510.0      22.92                   2.0
NaN                          127.0       3.04                1031.0
Office of Chief Minister    4463.0      14.07                 768.0
Superintendent of Police     971.0      14.40                 713.0

                                                                             \
                                     Disposed               Open
                         percentage     count percentage   count percentage
office
Chief Secretary               51.48      56.0       1.05   461.0       8.61
Collector                      9.61  162503.0      82.03  5128.0       2.59
DG & IG Police                 0.02    2424.0      49.99  2177.0      44.90
Departments                    2.44   27151.0      67.76  2639.0       6.59
Governor                       0.09    1480.0      66.52   233.0      10.47
NaN                           24.64    2155.0      51.51   871.0      20.82
Office of Chief Minister       2.42   24748.0      78.04  1731.0       5.46
Superintendent of Police      10.57    3345.0      49.59  1716.0      25.44

                         2024-2025                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary             1640.0      25.79                3372.0
Collector                  27478.0       9.29                9708.0
DG & IG Police               463.0       5.81                   6.0
Departments                22815.0      19.82                2151.0
Governor                     729.0      20.13                   1.0
NaN                          128.0       2.10                1097.0
Office of Chief Minister    6262.0       7.09                 319.0
Superintendent of Police    3112.0      28.47                1360.0

                                                                              \
                                     Disposed                Open
                         percentage     count percentage    count percentage
office
Chief Secretary               53.04     112.0       1.76   1234.0      19.41
Collector                      3.28  235228.0      79.53  23368.0       7.90
DG & IG Police                 0.08     716.0       8.99   6781.0      85.12
Departments                    1.87   58572.0      50.88  31577.0      27.43
Governor                       0.03    1906.0      52.64    985.0      27.20
NaN                           18.03    2324.0      38.20   2534.0      41.66
Office of Chief Minister       0.36   70993.0      80.43  10696.0      12.12
Superintendent of Police      12.44    1857.0      16.99   4601.0      42.10

                         Aggregate                                   \
                           Discard            Disposed with Benefit
                             count percentage                 count
office
Chief Secretary             4976.0      30.46                8558.0
Collector                  49252.0       8.55               46545.0
DG & IG Police               930.0       5.51                 107.0
Departments                38001.0      20.43                6063.0
Governor                    1799.0      21.98                   6.0
NaN                          500.0       3.67                2873.0
Office of Chief Minister   17357.0      10.92                2978.0
Superintendent of Police    5032.0      16.98                3078.0


                                     Disposed                Open
                         percentage     count percentage    count percentage
office
Chief Secretary               52.39     953.0       5.83   1849.0      11.32
Collector                      8.08  450978.0      78.29  29262.0       5.08
DG & IG Police                 0.63    7061.0      41.84   8780.0      52.02
Departments                    3.26  106969.0      57.51  34961.0      18.80
Governor                       0.07    5107.0      62.39   1273.0      15.55
NaN                           21.09    6989.0      51.30   3261.0      23.94
Office of Chief Minister       1.87  125754.0      79.09  12911.0       8.12
Superintendent of Police      10.39   13336.0      45.00   8192.0      27.64

In [12]:
pivot_pet_status_dept = petitioner_status_count_pivot(
    df_filtered, "dept")
print("\nPetitioner Status Group — Department:")
pivot_pet_status_dept

Petitioner Status Group — Department:

                                                   2021-2022             \
                                                     Discard
                                                       count percentage
dept
Agriculture & Farmers' Empowerment                      70.0       4.11
Co-operation                                             7.0       2.76
Commerce & Transport                                    12.0       3.57
Electronics & Information Technology                     4.0       5.33
Energy                                                  13.0       1.22
Excise                                                   2.0       1.40
Finance                                                 13.0       5.60
Fisheries & Animal Resources Development                 1.0       0.52
Food Supplies & Consumer Welfare                        42.0       1.83
Forest, Environment and Climate Change Department        5.0       1.98
General Administration & Public Grievance              156.0       8.49
Handlooms ,Textiles & Handicrafts                        1.0       3.33
Health & Family Welfare                                 78.0       2.43
Higher Education                                        58.0      12.31
Home department                                        172.0       2.14
Housing & Urban Development                            123.0       2.18
Industries                                               4.0       6.90
Information & Public Relations                          10.0      17.24
Labour & Employees' State Insurance                     12.0       3.02
Law                                                      2.0       2.11
Micro, Small & Medium Enterprise                         4.0      12.12
Mission Shakti                                           0.0       0.00
NaN                                                   7525.0      33.21
Odia Language Literature & Culture                       2.0       1.53
Panchayati Raj & Drinking Water                        250.0       1.57
Parliamentary Affairs                                    0.0       0.00
Planning & Convergence                                   1.0       2.50
Public Enterprises                                       0.0       0.00
Revenue & Disaster Management                          158.0       3.21
Rural Development                                       42.0       8.64
ST & SC Development, Minorities & Backward Clas...      49.0       9.42
School & Mass Education                                 58.0       2.04
Science & Technology                                     0.0       0.00
Skill Development & Technical Education                  8.0       4.82
Social Security & Empowerment of Persons with D...      69.0       4.57
Sports & Youth Services                                  1.0       2.22
Steel & Mines                                            6.0      10.34
Tourism                                                  3.0       8.11
Water Resources                                         14.0       2.39
Women & Child Development                                6.0       1.13
Works                                                   40.0      10.26

                                                                          \
                                                   Disposed with Benefit
                                                                   count
dept
Agriculture & Farmers' Empowerment                                 142.0
Co-operation                                                        16.0
Commerce & Transport                                                29.0
Electronics & Information Technology                                 7.0
Energy                                                             301.0
Excise                                                               5.0
Finance                                                             40.0
Fisheries & Animal Resources Development                            36.0
Food Supplies & Consumer Welfare                                   594.0
Forest, Environment and Climate Change Department                   30.0
General Administration & Public Grievance                          279.0
Handlooms ,Textiles & Handicrafts                                   11.0
Health & Family Welfare                                            505.0
Higher Education                                                    57.0
Home department                                                   1367.0
Housing & Urban Development                                        952.0
Industries                                                           8.0
Information & Public Relations                                      12.0
Labour & Employees' State Insurance                                 40.0
Law                                                                  8.0
Micro, Small & Medium Enterprise                                     3.0
Mission Shakti                                                       4.0
NaN                                                               1230.0
Odia Language Literature & Culture                                   8.0
Panchayati Raj & Drinking Water                                   2419.0
Parliamentary Affairs                                                1.0
Planning & Convergence                                              12.0
Public Enterprises                                                   1.0
Revenue & Disaster Management                                      832.0
Rural Development                                                   62.0
ST & SC Development, Minorities & Backward Clas...                  63.0
School & Mass Education                                            322.0
Science & Technology                                                 0.0
Skill Development & Technical Education                             27.0
Social Security & Empowerment of Persons with D...                 206.0
Sports & Youth Services                                              4.0
Steel & Mines                                                        2.0
Tourism                                                              9.0
Water Resources                                                    159.0
Women & Child Development                                           47.0
Works                                                               73.0

                                                                        \
                                                              Disposed
                                                   percentage    count
dept
Agriculture & Farmers' Empowerment                       8.34   1480.0
Co-operation                                             6.30    225.0
Commerce & Transport                                     8.63    293.0
Electronics & Information Technology                     9.33     62.0
Energy                                                  28.34    727.0
Excise                                                   3.50    133.0
Finance                                                 17.24    177.0
Fisheries & Animal Resources Development                18.85    153.0
Food Supplies & Consumer Welfare                        25.85   1654.0
Forest, Environment and Climate Change Department       11.86    215.0
General Administration & Public Grievance               15.18   1367.0
Handlooms ,Textiles & Handicrafts                       36.67     18.0
Health & Family Welfare                                 15.70   2439.0
Higher Education                                        12.10    343.0
Home department                                         16.99   5688.0
Housing & Urban Development                             16.85   4523.0
Industries                                              13.79     45.0
Information & Public Relations                          20.69     36.0
Labour & Employees' State Insurance                     10.08    341.0
Law                                                      8.42     82.0
Micro, Small & Medium Enterprise                         9.09     25.0
Mission Shakti                                           5.97     63.0
NaN                                                      5.43  13724.0
Odia Language Literature & Culture                       6.11    120.0
Panchayati Raj & Drinking Water                         15.21  13104.0
Parliamentary Affairs                                    5.88     16.0
Planning & Convergence                                  30.00     27.0
Public Enterprises                                       9.09     10.0
Revenue & Disaster Management                           16.92   3900.0
Rural Development                                       12.76    370.0
ST & SC Development, Minorities & Backward Clas...      12.12    397.0
School & Mass Education                                 11.35   2287.0
Science & Technology                                     0.00      7.0
Skill Development & Technical Education                 16.27    128.0
Social Security & Empowerment of Persons with D...      13.65   1222.0
Sports & Youth Services                                  8.89     39.0
Steel & Mines                                            3.45     49.0
Tourism                                                 24.32     24.0
Water Resources                                         27.09    381.0
Women & Child Development                                8.82    463.0
Works                                                   18.72    271.0

                                                                      \
                                                                Open
                                                   percentage  count
dept
Agriculture & Farmers' Empowerment                      86.91   11.0
Co-operation                                            88.58    6.0
Commerce & Transport                                    87.20    2.0
Electronics & Information Technology                    82.67    2.0
Energy                                                  68.46   21.0
Excise                                                  93.01    3.0
Finance                                                 76.29    2.0
Fisheries & Animal Resources Development                80.10    1.0
Food Supplies & Consumer Welfare                        71.98    8.0
Forest, Environment and Climate Change Department       84.98    3.0
General Administration & Public Grievance               74.37   36.0
Handlooms ,Textiles & Handicrafts                       60.00    0.0
Health & Family Welfare                                 75.84  194.0
Higher Education                                        72.82   13.0
Home department                                         70.68  821.0
Housing & Urban Development                             80.05   52.0
Industries                                              77.59    1.0
Information & Public Relations                          62.07    0.0
Labour & Employees' State Insurance                     85.89    4.0
Law                                                     86.32    3.0
Micro, Small & Medium Enterprise                        75.76    1.0
Mission Shakti                                          94.03    0.0
NaN                                                     60.58  177.0
Odia Language Literature & Culture                      91.60    1.0
Panchayati Raj & Drinking Water                         82.37  135.0
Parliamentary Affairs                                   94.12    0.0
Planning & Convergence                                  67.50    0.0
Public Enterprises                                      90.91    0.0
Revenue & Disaster Management                           79.32   27.0
Rural Development                                       76.13   12.0
ST & SC Development, Minorities & Backward Clas...      76.35   11.0
School & Mass Education                                 80.61  170.0
Science & Technology                                    87.50    1.0
Skill Development & Technical Education                 77.11    3.0
Social Security & Empowerment of Persons with D...      80.98   12.0
Sports & Youth Services                                 86.67    1.0
Steel & Mines                                           84.48    1.0
Tourism                                                 64.86    1.0
Water Resources                                         64.91   33.0
Women & Child Development                               86.87   17.0
Works                                                   69.49    6.0

                                                              2022-2023  \
                                                                Discard
                                                   percentage     count
dept
Agriculture & Farmers' Empowerment                       0.65      39.0
Co-operation                                             2.36       3.0
Commerce & Transport                                     0.60      11.0
Electronics & Information Technology                     2.67       0.0
Energy                                                   1.98      30.0
Excise                                                   2.10       4.0
Finance                                                  0.86       7.0
Fisheries & Animal Resources Development                 0.52       2.0
Food Supplies & Consumer Welfare                         0.35      36.0
Forest, Environment and Climate Change Department        1.19      15.0
General Administration & Public Grievance                1.96      38.0
Handlooms ,Textiles & Handicrafts                        0.00       1.0
Health & Family Welfare                                  6.03      57.0
Higher Education                                         2.76      84.0
Home department                                         10.20     202.0
Housing & Urban Development                              0.92     105.0
Industries                                               1.72       2.0
Information & Public Relations                           0.00      11.0
Labour & Employees' State Insurance                      1.01      20.0
Law                                                      3.16       4.0
Micro, Small & Medium Enterprise                         3.03       2.0
Mission Shakti                                           0.00       1.0
NaN                                                      0.78   16578.0
Odia Language Literature & Culture                       0.76       3.0
Panchayati Raj & Drinking Water                          0.85     307.0
Parliamentary Affairs                                    0.00       0.0
Planning & Convergence                                   0.00       4.0
Public Enterprises                                       0.00       0.0
Revenue & Disaster Management                            0.55     211.0
Rural Development                                        2.47      91.0
ST & SC Development, Minorities & Backward Clas...       2.12     146.0
School & Mass Education                                  5.99      95.0
Science & Technology                                    12.50       0.0
Skill Development & Technical Education                  1.81      10.0
Social Security & Empowerment of Persons with D...       0.80      57.0
Sports & Youth Services                                  2.22       6.0
Steel & Mines                                            1.72       3.0
Tourism                                                  2.70       0.0
Water Resources                                          5.62      29.0
Women & Child Development                                3.19      42.0
Works                                                    1.54      26.0

                                                               \

                                                   percentage
dept
Agriculture & Farmers' Empowerment                       0.84
Co-operation                                             0.78
Commerce & Transport                                     1.73
Electronics & Information Technology                     0.00
Energy                                                   1.51
Excise                                                   1.85
Finance                                                  1.86
Fisheries & Animal Resources Development                 0.52
Food Supplies & Consumer Welfare                         0.87
Forest, Environment and Climate Change Department        2.58
General Administration & Public Grievance                0.54
Handlooms ,Textiles & Handicrafts                        1.56
Health & Family Welfare                                  1.40
Higher Education                                         9.44
Home department                                          1.49
Housing & Urban Development                              1.24
Industries                                               2.53
Information & Public Relations                           1.24
Labour & Employees' State Insurance                      1.91
Law                                                      1.59
Micro, Small & Medium Enterprise                         2.15
Mission Shakti                                           0.62
NaN                                                     98.78
Odia Language Literature & Culture                       0.93
Panchayati Raj & Drinking Water                          0.67
Parliamentary Affairs                                    0.00
Planning & Convergence                                   5.80
Public Enterprises                                       0.00
Revenue & Disaster Management                            1.82
Rural Development                                        8.02
ST & SC Development, Minorities & Backward Clas...      11.46
School & Mass Education                                  1.68
Science & Technology                                     0.00
Skill Development & Technical Education                  4.59
Social Security & Empowerment of Persons with D...       1.28
Sports & Youth Services                                  5.41
Steel & Mines                                            4.48
Tourism                                                  0.00
Water Resources                                          4.16
Women & Child Development                                3.48
Works                                                    2.38

                                                                          \
                                                   Disposed with Benefit
                                                                   count
dept
Agriculture & Farmers' Empowerment                                 407.0
Co-operation                                                        46.0
Commerce & Transport                                                81.0
Electronics & Information Technology                                22.0
Energy                                                             449.0
Excise                                                              23.0
Finance                                                             59.0
Fisheries & Animal Resources Development                            79.0
Food Supplies & Consumer Welfare                                   628.0
Forest, Environment and Climate Change Department                  130.0
General Administration & Public Grievance                         2547.0
Handlooms ,Textiles & Handicrafts                                   18.0
Health & Family Welfare                                            734.0
Higher Education                                                   127.0
Home department                                                   1858.0
Housing & Urban Development                                        761.0
Industries                                                          15.0
Information & Public Relations                                      57.0

In [13]:
pivot_pet_status_category = petitioner_status_count_pivot(
    df_filtered, "category")
print("\nPetitioner Status Group — Category:")
pivot_pet_status_category

Petitioner Status Group — Category:

                            2021-2022                                   \
                              Discard            Disposed with Benefit
                                count percentage                 count
category
Accident                          1.0       7.69                   3.0
Agriculture & Farming            24.0       2.82                  73.0
BSKY                              0.0       0.00                   4.0
CMRF                              3.0       0.58                 165.0
COVID-19                          6.0       4.00                  28.0
Culture                           0.0       0.00                   1.0
Disaster Management               0.0       0.00                  24.0
Education                        55.0       6.38                  83.0
Energy                           26.0       2.17                 366.0
Environment                       0.0       0.00                   6.0
Excise                            1.0       0.75                   4.0
Financial Assistance             17.0       2.44                  90.0
General                         247.0       2.33                2412.0
Health Care                      49.0       2.98                 208.0
Housing                         145.0       1.22                 887.0
ICDS                              2.0       1.12                   5.0
Infrastructure                   92.0       5.71                 264.0
Irrigation                        0.0       0.00                   0.0
Land Matters                     66.0       2.94                 303.0
Legal                             0.0       0.00                   1.0
Miscellaneous                   144.0       4.49                 585.0
NaN                            7699.0      31.48                1546.0
Pension/Retirement Benefits      30.0       2.54                 667.0
Police Case                      95.0       1.99                 865.0
Public Utility                   24.0       3.35                  74.0
Scheme &amp;amp; Benefits         0.0       0.00                   0.0
School & College                  7.0       2.57                  13.0
Service Matters                 111.0       3.83                 345.0
Social Welfare                  128.0       2.37                 503.0
Sports                            1.0       2.78                   1.0
Tourism                           0.0       0.00                   0.0
Traffic                           0.0       0.00                   4.0
Transport                         6.0       2.75                  11.0
Waste Management                  9.0       4.39                  73.0
Water Supply                     23.0       1.64                 365.0
Women Issues                      1.0       1.06                   7.0

                                                                              \
                                       Disposed              Open
                            percentage    count percentage  count percentage
category
Accident                         23.08      9.0      69.23    0.0       0.00
Agriculture & Farming             8.57    743.0      87.21   12.0       1.41
BSKY                              6.25     50.0      78.12   10.0      15.62
CMRF                             31.98    345.0      66.86    3.0       0.58
COVID-19                         18.67    111.0      74.00    5.0       3.33
Culture                           8.33     11.0      91.67    0.0       0.00
Disaster Management              27.91     62.0      72.09    0.0       0.00
Education                         9.63    681.0      79.00   43.0       4.99
Energy                           30.55    783.0      65.36   23.0       1.92
Environment                       5.45    104.0      94.55    0.0       0.00
Excise                            3.01    127.0      95.49    1.0       0.75
Financial Assistance             12.91    585.0      83.93    5.0       0.72
General                          22.76   7177.0      67.72  762.0       7.19
Health Care                      12.67   1308.0      79.66   77.0       4.69
Housing                           7.45  10865.0      91.29    4.0       0.03
ICDS                              2.81    168.0      94.38    3.0       1.69
Infrastructure                   16.38   1204.0      74.69   52.0       3.23
Irrigation                        0.00      0.0       0.00    0.0       0.00
Land Matters                     13.51   1848.0      82.39   26.0       1.16
Legal                             7.14     13.0      92.86    0.0       0.00
Miscellaneous                    18.25   2395.0      74.73   81.0       2.53
NaN                               6.32  14989.0      61.29  221.0       0.90
Pension/Retirement Benefits      56.57    451.0      38.25   31.0       2.63
Police Case                      18.09   3587.0      75.03  234.0       4.89
Public Utility                   10.32    601.0      83.82   18.0       2.51
Scheme &amp;amp; Benefits         0.00      1.0     100.00    0.0       0.00
School & College                  4.78    233.0      85.66   19.0       6.99
Service Matters                  11.90   2334.0      80.54  108.0       3.73
Social Welfare                    9.31   4729.0      87.57   40.0       0.74
Sports                            2.78     33.0      91.67    1.0       2.78
Tourism                           0.00      7.0     100.00    0.0       0.00
Traffic                          17.39     17.0      73.91    2.0       8.70
Transport                         5.05    200.0      91.74    1.0       0.46
Waste Management                 35.61    122.0      59.51    1.0       0.49
Water Supply                     26.07    986.0      70.43   26.0       1.86
Women Issues                      7.45     84.0      89.36    2.0       2.13

                            2022-2023                                   \
                              Discard            Disposed with Benefit
                                count percentage                 count
category
Accident                          0.0       0.00                   6.0
Agriculture & Farming            18.0       1.46                 137.0
BSKY                              2.0       2.04                   7.0
CMRF                              0.0       0.00                 146.0
COVID-19                          1.0       1.72                   8.0
Culture                           0.0       0.00                   1.0
Disaster Management               4.0       3.12                  14.0
Education                        89.0       7.34                 155.0
Energy                           28.0       1.30                 472.0
Environment                       0.0       0.00                  11.0
Excise                            3.0       1.81                  11.0
Financial Assistance             20.0       0.90                 529.0
General                         350.0       1.40                5167.0
Health Care                      33.0       1.54                 325.0
Housing                         140.0       0.42                6882.0
ICDS                             10.0       3.56                  13.0
Infrastructure                  157.0       4.33                 434.0
Irrigation                        0.0       0.00                   5.0
Land Matters                     85.0       1.29                1138.0
Legal                             1.0       4.17                   3.0
Miscellaneous                   229.0       2.43                1234.0
NaN                           16580.0      98.77                   0.0
Pension/Retirement Benefits      32.0       2.29                 242.0
Police Case                     123.0       1.45                1146.0
Public Utility                   23.0       1.33                 173.0
Scheme &amp;amp; Benefits         0.0       0.00                   0.0
School & College                  2.0       0.30                  92.0
Service Matters                 172.0       3.81                 744.0
Social Welfare                  143.0       0.82                1258.0
Sports                            6.0       6.67                   3.0
Tourism                           0.0       0.00                   0.0
Traffic                           1.0       2.56                   4.0
Transport                         4.0       1.11                   3.0
Waste Management                  3.0       1.67                  59.0
Water Supply                     30.0       1.40                 524.0
Women Issues                      0.0       0.00                  21.0

                                                                               \
                                       Disposed               Open
                            percentage    count percentage   count percentage
category
Accident                         17.14     29.0      82.86     0.0       0.00
Agriculture & Farming            11.08   1054.0      85.21    28.0       2.26
BSKY                              7.14     82.0      83.67     7.0       7.14
CMRF                             29.98    337.0      69.20     4.0       0.82
COVID-19                         13.79     46.0      79.31     3.0       5.17
Culture                          20.00      4.0      80.00     0.0       0.00
Disaster Management              10.94    110.0      85.94     0.0       0.00
Education                        12.79    894.0      73.76    74.0       6.11
Energy                           21.91   1587.0      73.68    67.0       3.11
Environment                       8.03    124.0      90.51     2.0       1.46
Excise                            6.63    149.0      89.76     3.0       1.81
Financial Assistance             23.68   1635.0      73.19    50.0       2.24
General                          20.62  17491.0      69.80  2051.0       8.18
Health Care                      15.16   1654.0      77.15   132.0       6.16
Housing                          20.85  25914.0      78.53    64.0       0.19
ICDS                              4.63    248.0      88.26    10.0       3.56
Infrastructure                   11.98   2881.0      79.52   151.0       4.17
Irrigation                       13.89     28.0      77.78     3.0       8.33
Land Matters                     17.31   5286.0      80.40    66.0       1.00
Legal                            12.50     19.0      79.17     1.0       4.17
Miscellaneous                    13.11   7506.0      79.72   447.0       4.75
NaN                               0.00      0.0       0.00   207.0       1.23
Pension/Retirement Benefits      17.34   1039.0      74.43    83.0       5.95
Police Case                      13.52   7027.0      82.90   180.0       2.12
Public Utility                   10.02   1465.0      84.83    66.0       3.82
Scheme &amp;amp; Benefits         0.00      0.0       0.00     0.0       0.00
School & College                 13.79    507.0      76.01    66.0       9.90
Service Matters                  16.48   3263.0      72.29   335.0       7.42
Social Welfare                    7.18  16029.0      91.51    86.0       0.49
Sports                            3.33     81.0      90.00     0.0       0.00
Tourism                           0.00      7.0      87.50     1.0      12.50
Traffic                          10.26     34.0      87.18     0.0       0.00
Transport                         0.84    352.0      98.05     0.0       0.00
Waste Management                 32.78    114.0      63.33     4.0       2.22
Water Supply                     24.38   1504.0      69.99    91.0       4.23
Women Issues                     15.11    113.0      81.29     5.0       3.60

                            2023-2024                                   \
                              Discard            Disposed with Benefit
                                count percentage                 count
category
Accident                          0.0       0.00                   4.0
Agriculture & Farming            26.0       1.46                 120.0
BSKY                              1.0       0.41                  21.0
CMRF                              0.0       0.00                 175.0
COVID-19                          0.0       0.00                   5.0
Culture                           3.0       0.74                  34.0
Disaster Management               0.0       0.00                  13.0
Education                       662.0      15.15                 297.0
Energy                           29.0       0.87                 563.0
Environment                      10.0       4.39                  21.0
Excise                            0.0       0.00                  24.0
Financial Assistance             32.0       0.66                 926.0
General                         263.0       1.03                4521.0
Health Care                      37.0       1.22                 340.0
Housing                         176.0       0.23                5241.0
ICDS                             11.0       2.03                  29.0
Infrastructure                  229.0       0.51                5818.0
Irrigation                       19.0       0.92                 247.0
Land Matters                    103.0       0.95                1042.0
Legal                             3.0       1.97                   8.0
Miscellaneous                   258.0       1.41                1244.0
NaN                           23679.0      98.84                   0.0
Pension/Retirement Benefits      16.0       1.09                 130.0
Police Case                     112.0       1.13                 759.0
Public Utility                   47.0       0.89                 456.0
Scheme &amp;amp; Benefits         0.0       0.00                   0.0
School & College                 14.0       0.55                 207.0
Service Matters                 307.0       3.00                 584.0
Social Welfare                  161.0       0.42                2543.0
Sports                           19.0       2.75                  80.0
Tourism                           3.0       0.57                  69.0
Traffic                           1.0       1.49                   7.0
Transport                         1.0       0.28                  25.0
Waste Management                  3.0       3.26                  22.0
Water Supply                     36.0       0.91                 733.0
Women Issues                      2.0       2.20                  12.0

                                                                               \
                                       Disposed               Open
                            percentage    count percentage   count percentage
category
Accident                          7.84     42.0      82.35     5.0       9.80
Agriculture & Farming             6.73   1528.0      85.65   110.0       6.17
BSKY                              8.68    190.0      78.51    30.0      12.40
CMRF                             22.41    454.0      58.13   152.0      19.46
COVID-19                          8.93     42.0      75.00     9.0      16.07
Culture                           8.33    358.0      87.75    13.0       3.19
Disaster Management               7.34    156.0      88.14     8.0       4.52
Education                         6.80   3167.0      72.49   243.0       5.56
Energy                           16.80   2538.0      75.74   221.0       6.60
Environment                       9.21    186.0      81.58    11.0       4.82
Excise                            9.30    225.0      87.21     9.0       3.49
Financial Assistance             19.03   3636.0      74.74   271.0       5.57
General                          17.64  17397.0      67.87  3451.0      13.46
Health Care                      11.23   2290.0      75.63   361.0      11.92
Housing                           6.81  70592.0      91.79   901.0       1.17
ICDS                              5.34    434.0      79.93    69.0      12.71
Infrastructure                   13.01  37098.0      82.96  1572.0       3.52
Irrigation                       12.00   1654.0      80.33   139.0       6.75
Land Matters                      9.65   9357.0      86.65   297.0       2.75
Legal                             5.26    127.0      83.55    14.0       9.21
Miscellaneous                     6.80  14904.0      81.50  1881.0      10.29
NaN                               0.00      0.0       0.00   279.0       1.16
Pension/Retirement Benefits       8.87   1137.0      77.61   182.0      12.42
Police Case                       7.68   6565.0      66.41  2450.0      24.78
Public Utility                    8.65   4376.0      83.04   391.0       7.42
Scheme &amp;amp; Benefits         0.00      0.0       0.00     0.0       0.00
School & College                  8.17   2057.0      81.18   256.0      10.10
Service Matters                   5.70   8291.0      80.90  1067.0      10.41
Social Welfare                    6.59  35397.0      91.70   498.0       1.29
Sports                           11.59    549.0      79.57    42.0       6.09
Tourism                          13.19    439.0      83.94    12.0       2.29
Traffic                          10.45     53.0      79.10     6.0       8.96
Transport                         6.93    327.0      90.58     8.0       2.22
Waste Management                 23.91     60.0      65.22     7.0       7.61
Water Supply                     18.58   2651.0      67.20   525.0      13.31
Women Issues                     13.19     72.0      79.12     5.0       5.49

                            2024-2025                                   \
                              Discard            Disposed with Benefit
                                count percentage                 count
category
Accident                          0.0       0.00                   4.0
Agriculture & Farming            27.0       1.18                  38.0
BSKY                              2.0       1.74                   1.0
CMRF                              9.0       0.64                  25.0
COVID-19                          0.0       0.00                   0.0
Culture                           7.0       4.12                   5.0
Disaster Management               2.0       0.70                  14.0
Education                       543.0      10.93                 460.0
Energy                           33.0       0.51                 453.0
Environment                       5.0       0.88                  48.0
Excise                            2.0       0.40                   7.0
Financial Assistance             77.0       0.83                 242.0
General                         352.0       0.78                6946.0
Health Care                      34.0       0.91                 149.0
Housing                         158.0       0.10                3834.0
ICDS                              6.0       0.69                  31.0
Infrastructure                  132.0       1.03                 440.0
Irrigation                       25.0       2.36                  12.0
Land Matters                    168.0       0.80                 520.0
Legal                             4.0       1.26                   2.0
Miscellaneous                   365.0       1.13                 885.0
NaN                           56482.0      77.13                   0.0
Pension/Retirement Benefits      49.0       1.29                  75.0
Police Case                      75.0       0.42                1191.0
Public Utility                   18.0       0.43                 116.0
Scheme &amp;amp; Benefits         0.0       0.00                   0.0
School & College                 15.0       0.75                  52.0
Service Matters                 336.0       1.67                 363.0
Social Welfare                  414.0       0.36                2322.0
Sports                           15.0       5.60                   1.0
Tourism                           1.0       0.78                   9.0
Traffic                           4.0       2.88                   2.0

In [14]:
 
pivot_pet_status_subcategory = petitioner_status_count_pivot(
    df_filtered, "subcategory")
print("\nPetitioner Status Group — Subcategory:")
pivot_pet_status_subcategory.head(10)

Petitioner Status Group — Subcategory:

                      2021-2022                                              \
                        Discard            Disposed with Benefit
                          count percentage                 count percentage
subcategory
AIDS                        0.0       0.00                   0.0       0.00
Aadhar Card Issues          0.0       0.00                   1.0       6.25
Absence of officials        0.0       0.00                   0.0       0.00
Absurd/Irrelevant           0.0       0.00                   1.0      20.00
Accidental Claims           0.0       0.00                   0.0       0.00
Admissions                  1.0       3.33                   5.0      16.67
Agriculture/Farming         3.0       2.01                  13.0       8.72
Ahar Yojana                 0.0       0.00                   1.0      20.00
Allegation/Corruption      19.0       3.60                  32.0       6.06
Anganwadi Centres           0.0       0.00                   0.0       0.00

                                                           2022-2023  \
                      Disposed             Open              Discard
                         count percentage count percentage     count
subcategory
AIDS                       0.0       0.00   0.0       0.00       0.0
Aadhar Card Issues        14.0      87.50   1.0       6.25       0.0
Absence of officials       0.0       0.00   0.0       0.00       0.0
Absurd/Irrelevant          4.0      80.00   0.0       0.00       0.0
Accidental Claims          5.0     100.00   0.0       0.00       0.0
Admissions                24.0      80.00   0.0       0.00       0.0
Agriculture/Farming      132.0      88.59   1.0       0.67       4.0
Ahar Yojana                4.0      80.00   0.0       0.00       0.0
Allegation/Corruption    442.0      83.71  35.0       6.63      28.0
Anganwadi Centres          0.0       0.00   0.0       0.00       0.0

                                                                            \
                                 Disposed with Benefit            Disposed
                      percentage                 count percentage    count
subcategory
AIDS                        0.00                   0.0       0.00      1.0
Aadhar Card Issues          0.00                   4.0      28.57      9.0
Absence of officials        0.00                   0.0       0.00      0.0
Absurd/Irrelevant           0.00                   1.0       7.14     11.0
Accidental Claims           0.00                   5.0      22.73     17.0
Admissions                  0.00                  49.0      40.83     66.0
Agriculture/Farming         0.94                  40.0       9.43    370.0
Ahar Yojana                 0.00                   2.0      33.33      4.0
Allegation/Corruption       1.81                 167.0      10.80   1260.0
Anganwadi Centres           0.00                   0.0       0.00      2.0

                                                  2023-2024             \
                                  Open              Discard
                      percentage count percentage     count percentage
subcategory
AIDS                      100.00   0.0       0.00       1.0      25.00
Aadhar Card Issues         64.29   1.0       7.14       1.0       3.70
Absence of officials        0.00   0.0       0.00       0.0       0.00
Absurd/Irrelevant          78.57   2.0      14.29       0.0       0.00
Accidental Claims          77.27   0.0       0.00       0.0       0.00
Admissions                 55.00   5.0       4.17       1.0       0.59
Agriculture/Farming        87.26  10.0       2.36       8.0       1.42
Ahar Yojana                66.67   0.0       0.00       0.0       0.00
Allegation/Corruption      81.50  91.0       5.89      24.0       1.17
Anganwadi Centres         100.00   0.0       0.00       7.0       2.31

                                                                            \
                      Disposed with Benefit            Disposed
                                      count percentage    count percentage
subcategory
AIDS                                    1.0      25.00      2.0      50.00
Aadhar Card Issues                      4.0      14.81     19.0      70.37
Absence of officials                    1.0      50.00      1.0      50.00
Absurd/Irrelevant                       1.0       8.33      7.0      58.33
Accidental Claims                       3.0       8.33     31.0      86.11
Admissions                             29.0      17.16    121.0      71.60
Agriculture/Farming                    43.0       7.62    479.0      84.93
Ahar Yojana                             2.0       6.25     28.0      87.50
Allegation/Corruption                 187.0       9.08   1526.0      74.11
Anganwadi Centres                      15.0       4.95    235.0      77.56

                                        2024-2025             \
                        Open              Discard
                       count percentage     count percentage
subcategory
AIDS                     0.0       0.00       0.0       0.00
Aadhar Card Issues       3.0      11.11       4.0       2.38
Absence of officials     0.0       0.00       0.0       0.00
Absurd/Irrelevant        4.0      33.33       1.0       2.70
Accidental Claims        2.0       5.56       3.0       2.73
Admissions              18.0      10.65       3.0       0.84
Agriculture/Farming     34.0       6.03       7.0       0.97
Ahar Yojana              2.0       6.25       0.0       0.00
Allegation/Corruption  322.0      15.64      56.0       0.95
Anganwadi Centres       46.0      15.18       4.0       0.62

                                                                            \
                      Disposed with Benefit            Disposed
                                      count percentage    count percentage
subcategory
AIDS                                    0.0       0.00     12.0      92.31
Aadhar Card Issues                      5.0       2.98     97.0      57.74
Absence of officials                    0.0       0.00      0.0       0.00
Absurd/Irrelevant                       1.0       2.70     28.0      75.68
Accidental Claims                       7.0       6.36     80.0      72.73
Admissions                             25.0       7.00    274.0      76.75
Agriculture/Farming                    18.0       2.51    450.0      62.67
Ahar Yojana                             3.0       8.11     25.0      67.57
Allegation/Corruption                  93.0       1.57   3963.0      66.92
Anganwadi Centres                      19.0       2.93    424.0      65.43

                                         Aggregate             \
                         Open              Discard
                        count percentage     count percentage
subcategory
AIDS                      1.0       7.69       1.0       5.56
Aadhar Card Issues       62.0      36.90       5.0       2.23
Absence of officials      0.0       0.00       0.0       0.00
Absurd/Irrelevant         7.0      18.92       1.0       1.47
Accidental Claims        20.0      18.18       3.0       1.74
Admissions               55.0      15.41       5.0       0.75
Agriculture/Farming     243.0      33.84      22.0       1.21
Ahar Yojana               9.0      24.32       0.0       0.00
Allegation/Corruption  1810.0      30.56     126.0       1.30
Anganwadi Centres       201.0      31.02      11.0       1.18

                                                                            \
                      Disposed with Benefit            Disposed
                                      count percentage    count percentage
subcategory
AIDS                                    1.0       5.56     15.0      83.33
Aadhar Card Issues                     14.0       6.25    138.0      61.61
Absence of officials                    1.0      50.00      1.0      50.00
Absurd/Irrelevant                       4.0       5.88     50.0      73.53
Accidental Claims                      15.0       8.72    133.0      77.33
Admissions                            107.0      15.97    480.0      71.64
Agriculture/Farming                   114.0       6.26   1401.0      76.89
Ahar Yojana                             8.0      10.00     61.0      76.25
Allegation/Corruption                 469.0       4.84   6886.0      71.13
Anganwadi Centres                      34.0       3.63    651.0      69.55


                         Open
                        count percentage
subcategory
AIDS                      1.0       5.56
Aadhar Card Issues       67.0      29.91
Absence of officials      0.0       0.00
Absurd/Irrelevant        13.0      19.12
Accidental Claims        21.0      12.21
Admissions               78.0      11.64
Agriculture/Farming     285.0      15.64
Ahar Yojana              11.0      13.75
Allegation/Corruption  2200.0      22.72
Anganwadi Centres       240.0      25.64

## 4. Disposal Time by Status Bucket at Petitioner Level

In [17]:
pivot_pet_bucket_yearly = petitioner_disposal_time_pivot(
    df_res, "custom_year")
pivot_pet_bucket_yearly

              Discard                         Disposed with Benefit  \
                count percentage  mean median                 count
custom_year
2021-2022      8685.0      12.49  67.0    3.0                9298.0
2022-2023     17848.0      14.18  20.0    2.0               19599.0
2023-2024     25508.0       9.69  21.0    3.0               24823.0
2024-2025     58784.0      13.76  30.0    3.0               17562.0
Aggregate    105509.0      12.54  29.0    3.0               68113.0

                                      Disposed                           \
            percentage   mean median     count percentage   mean median
custom_year
2021-2022        13.37  194.0  126.0   51517.0      74.09  219.0  163.0
2022-2023        15.57   90.0   37.0   88418.0      70.25  107.0   48.0
2023-2024         9.43   98.0   49.0  212786.0      80.87  109.0   64.0
2024-2025         4.11   76.0   46.0  350750.0      82.12   63.0   41.0
Aggregate         8.10  102.0   50.0  667408.0      79.35   95.0   51.0

            In Follow Up With Close
                              count percentage   mean median
custom_year
2021-2022                      31.0       0.04   71.0   35.0
2022-2023                       5.0       0.00   21.0    7.0
2023-2024                       2.0       0.00  439.0  439.0
2024-2025                      35.0       0.01  144.0  181.0
Aggregate                      73.0       0.01  108.0   57.0

In [19]:
pivot_pet_bucket_district = petitioner_disposal_time_pivot(
    df_res, "district")

pivot_pet_bucket_district

               2021-2022                                                 \
                 Discard                          Disposed with Benefit
                   count percentage   mean median                 count
district
Angul              293.0      14.63   66.0    3.0                 198.0
Balangir           357.0      10.63   72.0    8.0                 807.0
Baleswar           886.0      14.78   43.0    4.0                 260.0
Bargarh            355.0      15.76   57.0    4.0                 181.0
Bhadrak            401.0      11.62  136.0    9.0                 184.0
Boudh              139.0      26.63   42.0   10.0                  79.0
Cuttack            469.0      16.40  117.0   22.0                 351.0
Deogarh             50.0      10.66   72.0   12.0                  30.0
Dhenkanal          794.0      23.52   16.0    1.0                 113.0
Gajapati            96.0       7.98  108.0    6.0                  53.0
Ganjam             470.0      12.74   77.0    3.0                 411.0
Jagatsinghapur     248.0       9.72   71.0   16.0                 127.0
Jajpur             391.0      11.77   42.0    2.0                 157.0
Jharsuguda          65.0      15.44   41.0    4.0                  55.0
Kalahandi          671.0       8.46   41.0    2.0                 565.0
Kandhamal           50.0      10.96   67.0   20.0                  80.0
Kendrapara         268.0       7.17   63.0    4.0                 230.0
Kendujhar          146.0       9.88   86.0    6.0                 124.0
Khordha            783.0      12.38   80.0    3.0                2594.0
Koraput            136.0      16.25   76.0   14.0                 155.0
Malkangiri          41.0      15.95   30.0    2.0                  75.0
Mayurbhanj         201.0       8.60   81.0    5.0                1118.0
NaN                 93.0       7.65  264.0  177.0                 278.0
Nabarangpur         78.0      11.00   45.0    5.0                  80.0
Nayagarh           241.0      12.33   67.0    3.0                 139.0
Nuapada             82.0       8.31   48.0   10.0                  78.0
Puri               266.0      13.12   76.0    6.0                 256.0
Rayagada           107.0      13.10   72.0    4.0                 127.0
Sambalpur          179.0      17.45   69.0    4.0                 105.0
Subarnapur         128.0      14.17   70.0    8.0                 172.0
Sundargarh         201.0      18.93   61.0    5.0                 116.0

                                                                           \
                                        Disposed
               percentage   mean median    count percentage   mean median
district
Angul                9.89  179.0  150.0   1511.0      75.44  204.0  169.0
Balangir            24.03  238.0  218.0   2194.0      65.32  295.0  272.0
Baleswar             4.34  289.0  210.0   4846.0      80.86  280.0  229.0
Bargarh              8.03  139.0   84.0   1714.0      76.08  146.0   97.0
Bhadrak              5.33  353.0  232.0   2866.0      83.05  233.0  198.0
Boudh               15.13  150.0   96.0    304.0      58.24  162.0  105.0
Cuttack             12.28  298.0  259.0   2039.0      71.32  305.0  263.0
Deogarh              6.40  189.0  150.0    389.0      82.94  256.0  215.0
Dhenkanal            3.35  182.0  115.0   2468.0      73.10  119.0   59.0
Gajapati             4.41  205.0  140.0   1054.0      87.61  212.0  113.0
Ganjam              11.14  213.0  144.0   2807.0      76.11  178.0  106.0
Jagatsinghapur       4.98  236.0  220.0   2176.0      85.27  205.0  158.0
Jajpur               4.73  270.0  219.0   2773.0      83.50  200.0  145.0
Jharsuguda          13.06  173.0   73.0    288.0      68.41  144.0   54.0
Kalahandi            7.12  181.0  158.0   6698.0      84.41  193.0  154.0
Kandhamal           17.54  252.0  196.0    325.0      71.27  240.0  202.0
Kendrapara           6.15  222.0  139.0   3239.0      86.67  188.0  128.0
Kendujhar            8.40  179.0  114.0   1207.0      81.72  250.0  190.0
Khordha             41.01  157.0   87.0   2946.0      46.58  319.0  243.0
Koraput             18.52  210.0  175.0    545.0      65.11  202.0  171.0
Malkangiri          29.18   75.0   35.0    141.0      54.86  118.0   15.0
Mayurbhanj          47.86  157.0   81.0   1017.0      43.54  257.0  172.0
NaN                 22.86  146.0   99.0    845.0      69.49  208.0  106.0
Nabarangpur         11.28  226.0  139.0    551.0      77.72  140.0   88.0
Nayagarh             7.11  241.0  205.0   1572.0      80.45  201.0  165.0
Nuapada              7.90  182.0  117.0    827.0      83.79  150.0   83.0
Puri                12.63  223.0  170.0   1505.0      74.25  234.0  176.0
Rayagada            15.54  183.0  124.0    583.0      71.36  301.0  224.0
Sambalpur           10.23  185.0  103.0    741.0      72.22  163.0   95.0
Subarnapur          19.05  134.0   89.0    602.0      66.67  234.0  168.0
Sundargarh          10.92  182.0  134.0    744.0      70.06  198.0  133.0

                                                                2022-2023  \
               In Follow Up With Close                            Discard
                                 count percentage   mean median     count
district
Angul                              1.0       0.05  235.0  235.0     442.0
Balangir                           1.0       0.03   77.0   77.0    1444.0
Baleswar                           1.0       0.02   10.0   10.0    2253.0
Bargarh                            3.0       0.13   52.0   27.0     456.0
Bhadrak                            0.0       0.00    0.0    0.0     538.0
Boudh                              0.0       0.00    0.0    0.0     267.0
Cuttack                            0.0       0.00    0.0    0.0     761.0
Deogarh                            0.0       0.00    0.0    0.0      71.0
Dhenkanal                          1.0       0.03   16.0   16.0    1269.0
Gajapati                           0.0       0.00    0.0    0.0     478.0
Ganjam                             0.0       0.00    0.0    0.0    1098.0
Jagatsinghapur                     1.0       0.04  359.0  359.0     328.0
Jajpur                             0.0       0.00    0.0    0.0    1224.0
Jharsuguda                        13.0       3.09   34.0   25.0     211.0
Kalahandi                          1.0       0.01   50.0   50.0    1132.0
Kandhamal                          1.0       0.22  148.0  148.0      99.0
Kendrapara                         0.0       0.00    0.0    0.0     679.0
Kendujhar                          0.0       0.00    0.0    0.0     450.0
Khordha                            2.0       0.03  150.0  150.0    1130.0
Koraput                            1.0       0.12  296.0  296.0     283.0
Malkangiri                         0.0       0.00    0.0    0.0      77.0
Mayurbhanj                         0.0       0.00    0.0    0.0     380.0
NaN                                0.0       0.00    0.0    0.0      76.0
Nabarangpur                        0.0       0.00    0.0    0.0     165.0
Nayagarh                           2.0       0.10  107.0  107.0     605.0
Nuapada                            0.0       0.00    0.0    0.0     163.0
Puri                               0.0       0.00    0.0    0.0     589.0
Rayagada                           0.0       0.00    0.0    0.0     246.0
Sambalpur                          1.0       0.10   14.0   14.0     285.0
Subarnapur                         1.0       0.11   32.0   32.0     197.0
Sundargarh                         1.0       0.09   58.0   58.0     452.0

                                                                         \
                                       Disposed with Benefit
               percentage  mean median                 count percentage
district
Angul               18.90  18.0    2.0                 158.0       6.76
Balangir            15.14  12.0    1.0                4380.0      45.91
Baleswar            19.33  14.0    2.0                 418.0       3.59
Bargarh             16.02  17.0    1.0                 195.0       6.85
Bhadrak             10.96  11.0    1.0                 267.0       5.44
Boudh                8.55  16.0    2.0                 690.0      22.09
Cuttack             16.64  31.0    2.0                 506.0      11.06
Deogarh              9.87  16.0    2.0                  36.0       5.01
Dhenkanal           35.09   7.0    1.0                 249.0       6.89
Gajapati            13.92  26.0    6.0                 105.0       3.06
Ganjam              12.37  15.0    1.0                 654.0       7.37
Jagatsinghapur       5.46  29.0    2.0                 192.0       3.19
Jajpur              25.19  38.0    1.0                 227.0       4.67
Jharsuguda          28.98  20.0    2.0                  52.0       7.14
Kalahandi            9.96  15.0    1.0                3597.0      31.64
Kandhamal           14.60  37.0    8.0                  83.0      12.24
Kendrapara          13.05  18.0    2.0                 516.0       9.91
Kendujhar           19.59  19.0    2.0                 137.0       5.96
Khordha             18.36  37.0    2.0                1361.0      22.12
Koraput             23.06  23.0    2.0                 255.0      20.78
Malkangiri          24.52  55.0    8.0                  41.0      13.06
Mayurbhanj           6.90  21.0    2.0                4113.0      74.63
NaN                 21.17  49.0    4.0                  40.0      11.14
Nabarangpur          6.24  23.0    2.0                 111.0       4.20
Nayagarh            11.99   9.0    1.0                 173.0       3.43
Nuapada              6.22  27.0    2.0                  80.0       3.05
Puri                10.65  20.0    2.0                 285.0       5.15
Rayagada            12.34  40.0    3.0                 301.0      15.10
Sambalpur           19.35   8.0    1.0                 127.0       8.62
Subarnapur          10.47  40.0    2.0                 110.0       5.84
Sundargarh          10.42  19.0    3.0                 140.0       3.23

                                                                \
                             Disposed
                 mean median    count percentage   mean median
district
Angul           128.0   73.0   1738.0      74.31   87.0   45.0
Balangir         34.0   19.0   3716.0      38.95   73.0   33.0
Baleswar        142.0   85.0   8986.0      77.09  132.0   89.0
Bargarh         124.0   42.0   2196.0      77.13   82.0   26.0
Bhadrak         215.0   90.0   4105.0      83.60   91.0   45.0
Boudh            47.0   29.0   2167.0      69.37   81.0   42.0
Cuttack         140.0   70.0   3306.0      72.29  126.0   58.0
Deogarh         209.0  127.0    612.0      85.12  146.0   74.0
Dhenkanal       126.0   60.0   2098.0      58.02   86.0   39.0
Gajapati        152.0   87.0   2851.0      83.02  155.0   53.0
Ganjam          106.0   43.0   7126.0      80.27   71.0   31.0
Jagatsinghapur  133.0   61.0   5490.0      91.33  100.0   57.0
Jajpur          113.0   53.0   3408.0      70.14  106.0   52.0
Jharsuguda      145.0   66.0    463.0      63.60   80.0   33.0
Kalahandi        75.0   57.0   6638.0      58.40  100.0   52.0
Kandhamal       164.0   87.0    496.0      73.16  153.0   77.0
Kendrapara      151.0   91.0   4010.0      77.04  130.0   53.0
Kendujhar       130.0   56.0   1710.0      74.44  131.0   56.0
Khordha         117.0   51.0   3663.0      59.52  166.0   75.0
Koraput          91.0   35.0    688.0      56.07  101.0   40.0
Malkangiri      121.0   68.0    196.0      62.42   80.0   16.0
Mayurbhanj       97.0   33.0   1018.0      18.47  191.0   75.0
NaN              85.0   46.0    243.0      67.69  120.0   54.0
Nabarangpur     107.0   46.0   2367.0      89.56   67.0   41.0
Nayagarh        112.0   51.0   4267.0      84.58   99.0   46.0
Nuapada          80.0   25.0   2378.0      90.73  106.0   42.0
Puri            153.0   70.0   4655.0      84.19   88.0   44.0
Rayagada         73.0   28.0   1447.0      72.57  250.0  157.0
Sambalpur        72.0   33.0   1061.0      72.03   82.0   31.0
Subarnapur      175.0   91.0   1575.0      83.69  143.0   86.0
Sundargarh       77.0   29.0   3744.0      86.35   45.0   16.0

                                                               2023-2024  \
               In Follow Up With Close                           Discard
                                 count percentage  mean median     count
district
Angul                              1.0       0.04  11.0   11.0     674.0
Balangir                           0.0       0.00   0.0    0.0    1691.0
Baleswar                           0.0       0.00   0.0    0.0    1661.0
Bargarh                            0.0       0.00   0.0    0.0     682.0
Bhadrak                            0.0       0.00   0.0    0.0     907.0
Boudh                              0.0       0.00   0.0    0.0     245.0
Cuttack                            0.0       0.00   0.0    0.0    1458.0
Deogarh                            0.0       0.00   0.0    0.0     145.0
Dhenkanal                          0.0       0.00   0.0    0.0    2833.0
Gajapati                           0.0       0.00   0.0    0.0     308.0
Ganjam                             0.0       0.00   0.0    0.0    1862.0
Jagatsinghapur                     1.0       0.02   3.0    3.0     318.0
Jajpur                             0.0       0.00   0.0    0.0    1244.0
Jharsuguda                         2.0       0.27  52.0   52.0     454.0
Kalahandi                          0.0       0.00   0.0    0.0    1249.0
Kandhamal                          0.0       0.00   0.0    0.0     286.0
Kendrapara                         0.0       0.00   0.0    0.0     779.0
Kendujhar                          0.0       0.00   0.0    0.0     812.0
Khordha                            0.0       0.00   0.0    0.0    1449.0
Koraput                            1.0       0.08   3.0    3.0     541.0
Malkangiri                         0.0       0.00   0.0    0.0     131.0
Mayurbhanj                         0.0       0.00   0.0    0.0    1042.0
NaN                                0.0       0.00   0.0    0.0     127.0
Nabarangpur                        0.0       0.00   0.0    0.0     333.0
Nayagarh                           0.0       0.00   0.0    0.0     504.0
Nuapada                            0.0       0.00   0.0    0.0     325.0
Puri                               0.0       0.00   0.0    0.0     687.0
Rayagada                           0.0       0.00   0.0    0.0     590.0
Sambalpur                          0.0       0.00   0.0    0.0     789.0
Subarnapur                         0.0       0.00   0.0    0.0     339.0
Sundargarh                         0.0       0.00   0.0    0.0    1043.0

                                                                         \
                                       Disposed with Benefit
               percentage  mean median                 count percentage
district
Angul               10.57  17.0    2.0                 279.0       4.38
Balangir             8.35  17.0    2.0                1750.0       8.64
Baleswar            13.08  13.0    1.0                 651.0       5.13
Bargarh              9.22  19.0    3.0                 187.0       2.53
Bhadrak             10.56  16.0    2.0                 542.0       6.31
Boudh                7.59  29.0    2.0                 145.0       4.49
Cuttack             15.57  33.0    2.0                1632.0      17.42
Deogarh              5.17  19.0    3.0                 288.0      10.27
Dhenkanal           23.37  11.0    4.0                 970.0       8.00
Gajapati             6.35  20.0    2.0                 190.0       3.92
Ganjam               9.98  28.0    3.0                 516.0       2.77
Jagatsinghapur       5.43  20.0    3.0                 161.0       2.75
Jajpur              16.20  32.0    3.0                 263.0       3.43
Jharsuguda          12.98  10.0    1.0                  68.0       1.94
Kalahandi            6.68  23.0    5.0                3376.0      18.06
Kandhamal            8.59  18.0    3.0                 154.0       4.63
Kendrapara          16.91  33.0    3.0                 790.0      17.15
Kendujhar            7.34  32.0    4.0                 181.0       1.64
Khordha             13.22  29.0    4.0                2176.0      19.85
Koraput             11.12  18.0    2.0                 840.0      17.27
Malkangiri           8.90  19.0    4.0                 319.0      21.67
Mayurbhanj           7.00  16.0    2.0                5994.0      40.26
NaN                 33.33  46.0    7.0                  29.0       7.61
Nabarangpur          7.25  14.0    4.0                 831.0      18.10
Nayagarh             7.53  13.0    2.0                 132.0       1.97
Nuapada              4.68  15.0    3.0                 345.0       4.97
Puri                 9.48  24.0    3.0                 376.0       5.19
Rayagada            19.48  15.0    2.0                  63.0       2.08
Sambalpur            4.11  15.0    2.0                 267.0       1.39
Subarnapur           9.85  17.0    2.0                  63.0       1.83
Sundargarh           5.69  22.0    5.0                1245.0       6.79

                                                                \
                             Disposed
                 mean median    count percentage   mean median
district
Angul            99.0   31.0   5421.0      85.05  104.0   70.0
Balangir         47.0   16.0  16817.0      83.01  133.0  114.0
Baleswar        111.0   41.0  10385.0      81.79  125.0   66.0
Bargarh         148.0   74.0   6529.0      88.25  104.0   53.0
Bhadrak         117.0   65.0   7142.0      83.13  105.0   60.0
Boudh           113.0   54.0   2837.0      87.91  115.0   56.0
Cuttack          78.0   25.0   6275.0      67.00  133.0   70.0
Deogarh          46.0   25.0   2372.0      84.56  106.0   93.0
Dhenkanal        68.0   29.0   8320.0      68.63   82.0   44.0
Gajapati        107.0  111.0   4353.0      89.73  140.0  122.0
Ganjam          109.0   61.0  16283.0      87.26   91.0   53.0
Jagatsinghapur  142.0   89.0   5375.0      91.82  119.0   58.0
Jajpur          162.0   85.0   6170.0      80.37  109.0   46.0
Jharsuguda      172.0  125.0   2976.0      85.08   92.0   45.0
Kalahandi       111.0   92.0  14072.0      75.26  142.0   95.0
Kandhamal       174.0  115.0   2888.0      86.78   77.0   30.0
Kendrapara       82.0   40.0   3038.0      65.94  125.0   82.0
Kendujhar       179.0  116.0  10065.0      91.02  103.0   96.0
Khordha          79.0   46.0   7336.0      66.93  132.0   84.0
Koraput          57.0   34.0   3483.0      71.61  103.0   56.0
Malkangiri       39.0   17.0   1022.0      69.43   77.0   39.0
Mayurbhanj      123.0   86.0   7852.0      52.74  102.0   53.0
NaN             114.0   66.0    225.0      59.06  115.0   75.0
Nabarangpur      28.0   13.0   3426.0      74.64  137.0   52.0
Nayagarh        113.0   64.0   6055.0      90.48   76.0   42.0
Nuapada          90.0   27.0   6270.0      90.35  148.0  104.0
Puri            153.0   82.0   6181.0      85.33   98.0   47.0
Rayagada         93.0   66.0   2376.0      78.44  101.0   50.0
Sambalpur       139.0   72.0  18155.0      94.50   85.0   49.0
Subarnapur      110.0   59.0   3038.0      88.31   85.0   44.0
Sundargarh       50.0   31.0  16049.0      87.52   98.0   76.0

                                                                2024-2025  \
               In Follow Up With Close                            Discard
                                 count percentage   mean median     count
district
Angul                              0.0       0.00    0.0    0.0    1648.0
Balangir                           0.0       0.00    0.0    0.0    4332.0
Baleswar                           0.0       0.00    0.0    0.0    3046.0
Bargarh                            0.0       0.00    0.0    0.0    1176.0
Bhadrak                            0.0       0.00    0.0    0.0    2339.0
Boudh                              0.0       0.00    0.0    0.0     613.0
Cuttack                            1.0       0.01  479.0  479.0    2871.0
Deogarh                            0.0       0.00    0.0    0.0     346.0

In [20]:
pivot_pet_bucket_office = petitioner_disposal_time_pivot(
    df_res, "office")
pivot_pet_bucket_office

                         2021-2022                           \
                           Discard
                             count percentage   mean median
office
Chief Secretary              526.0      25.67   24.0    1.0
Collector                   3716.0      12.91   39.0    3.0
DG & IG Police                75.0       4.22   95.0   73.0
Departments                 2673.0      18.92  111.0   39.0
Governor                     242.0      17.79   41.0    4.0
NaN                          148.0       4.85  325.0  268.0
Office of Chief Minister    1959.0       9.93   19.0    1.0
Superintendent of Police     462.0      10.05  239.0  126.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         1127.0      55.00  306.0  222.0
Collector                               4913.0      17.06  152.0  104.0
DG & IG Police                           100.0       5.63   84.0   56.0
Departments                             1742.0      12.33  182.0  149.0
Governor                                   3.0       0.22  127.0  107.0
NaN                                      739.0      24.22  137.0   87.0
Office of Chief Minister                 758.0       3.84  396.0  392.0
Superintendent of Police                 214.0       4.65  281.0   64.0

                                                            \
                         Disposed
                            count percentage   mean median
office
Chief Secretary             396.0      19.33  250.0  210.0
Collector                 20143.0      69.97  162.0  107.0
DG & IG Police             1600.0      90.09  156.0  106.0
Departments                9702.0      68.68  249.0  194.0
Governor                   1115.0      81.99  287.0  213.0
NaN                        2164.0      70.93  187.0  107.0
Office of Chief Minister  17007.0      86.22  288.0  237.0
Superintendent of Police   3920.0      85.24  181.0  143.0

                                                                           \
                         In Follow Up With Close
                                           count percentage   mean median
office
Chief Secretary                              0.0       0.00    0.0    0.0
Collector                                   18.0       0.06   55.0   33.0
DG & IG Police                               1.0       0.06  149.0  149.0
Departments                                  9.0       0.06  113.0   64.0
Governor                                     0.0       0.00    0.0    0.0
NaN                                          0.0       0.00    0.0    0.0
Office of Chief Minister                     0.0       0.00    0.0    0.0
Superintendent of Police                     3.0       0.07   27.0   14.0

                         2022-2023                           \
                           Discard
                             count percentage   mean median
office
Chief Secretary             1118.0      30.08    6.0    1.0
Collector                   8194.0      11.46   11.0    1.0
DG & IG Police               173.0       6.03   10.0    2.0
Departments                 4725.0      20.60   38.0    3.0
Governor                     401.0      28.68   18.0    7.0
NaN                          142.0       4.58  282.0  168.0
Office of Chief Minister    5469.0      21.80    3.0    1.0
Superintendent of Police     536.0       8.46  174.0    6.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         2178.0      58.60  174.0   75.0
Collector                              13866.0      19.39   64.0   30.0
DG & IG Police                             0.0       0.00    0.0    0.0
Departments                             1392.0       6.07  102.0   54.0
Governor                                   0.0       0.00    0.0    0.0
NaN                                      725.0      23.36  121.0   49.0
Office of Chief Minister                1183.0       4.72  118.0   80.0
Superintendent of Police                 879.0      13.88   85.0   29.0

                                                            \
                         Disposed
                            count percentage   mean median
office
Chief Secretary             421.0      11.33   74.0   40.0
Collector                 49464.0      69.15  100.0   47.0
DG & IG Police             2697.0      93.97   88.0   43.0
Departments               16820.0      73.33  118.0   53.0
Governor                    997.0      71.32  167.0   72.0
NaN                        2236.0      72.06  130.0   49.0
Office of Chief Minister  18437.0      73.49  106.0   46.0
Superintendent of Police   4919.0      77.65   94.0   42.0

                                                                          \
                         In Follow Up With Close
                                           count percentage  mean median
office
Chief Secretary                              0.0       0.00   0.0    0.0
Collector                                    4.0       0.01  24.0   11.0
DG & IG Police                               0.0       0.00   0.0    0.0
Departments                                  0.0       0.00   0.0    0.0
Governor                                     0.0       0.00   0.0    0.0
NaN                                          0.0       0.00   0.0    0.0
Office of Chief Minister                     0.0       0.00   0.0    0.0
Superintendent of Police                     1.0       0.02   3.0    3.0

                         2023-2024                           \
                           Discard
                             count percentage   mean median
office
Chief Secretary             2082.0      42.52    3.0    1.0
Collector                  11432.0       5.92   25.0    4.0
DG & IG Police               247.0       9.24    5.0    2.0
Departments                 9300.0      24.85   24.0    3.0
Governor                     510.0      25.60   29.0    7.0
NaN                          127.0       3.83  202.0  195.0
Office of Chief Minister    4463.0      14.89    7.0    2.0
Superintendent of Police     971.0      19.31   51.0    3.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         2758.0      56.33  177.0  106.0
Collector                              19031.0       9.86   75.0   35.0
DG & IG Police                             1.0       0.04  423.0  423.0
Departments                              978.0       2.61  130.0   87.0
Governor                                   2.0       0.10  263.0  263.0
NaN                                     1031.0      31.12  113.0   57.0
Office of Chief Minister                 768.0       2.56  115.0   80.0
Superintendent of Police                 713.0      14.18   91.0   56.0

                                                             \
                          Disposed
                             count percentage   mean median
office
Chief Secretary               56.0       1.14  260.0  281.0
Collector                 162495.0      84.21  101.0   59.0
DG & IG Police              2424.0      90.72   77.0   49.0
Departments                27151.0      72.54  105.0   69.0
Governor                    1480.0      74.30  202.0  181.0
NaN                         2155.0      65.05  159.0   90.0
Office of Chief Minister   24748.0      82.55  153.0   95.0
Superintendent of Police    3345.0      66.51   79.0   42.0

                                                                           \
                         In Follow Up With Close
                                           count percentage   mean median
office
Chief Secretary                              0.0       0.00    0.0    0.0
Collector                                    0.0       0.00    0.0    0.0
DG & IG Police                               0.0       0.00    0.0    0.0
Departments                                  2.0       0.01  439.0  439.0
Governor                                     0.0       0.00    0.0    0.0
NaN                                          0.0       0.00    0.0    0.0
Office of Chief Minister                     0.0       0.00    0.0    0.0
Superintendent of Police                     0.0       0.00    0.0    0.0

                         2024-2025                          \
                           Discard
                             count percentage  mean median
office
Chief Secretary             1640.0      32.01  16.0    1.0
Collector                  27478.0      10.09  11.0    2.0
DG & IG Police               463.0      39.07   3.0    2.0
Departments                22815.0      27.30  49.0    5.0
Governor                     729.0      27.66  28.0   16.0
NaN                          128.0       3.61  43.0   21.0
Office of Chief Minister    6262.0       8.07  30.0   10.0
Superintendent of Police    3112.0      49.17  17.0    3.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         3372.0      65.81  129.0  128.0
Collector                               9708.0       3.56   50.0   30.0
DG & IG Police                             6.0       0.51  129.0  132.0
Departments                             2151.0       2.57   61.0   39.0
Governor                                   1.0       0.04  128.0  128.0
NaN                                     1097.0      30.91   76.0   52.0
Office of Chief Minister                 319.0       0.41   68.0   56.0
Superintendent of Police                1360.0      21.49   40.0   24.0

                                                             \
                          Disposed
                             count percentage   mean median
office
Chief Secretary              112.0       2.19  144.0  142.0
Collector                 235228.0      86.35   48.0   29.0
DG & IG Police               716.0      60.42   83.0   41.0
Departments                58572.0      70.09  103.0   79.0
Governor                    1906.0      72.31  123.0  118.0
NaN                         2324.0      65.48   89.0   63.0
Office of Chief Minister   70991.0      91.52   69.0   53.0
Superintendent of Police    1857.0      29.34   60.0   39.0

                                                                           \
                         In Follow Up With Close
                                           count percentage   mean median
office
Chief Secretary                              0.0       0.00    0.0    0.0
Collector                                    0.0       0.00    0.0    0.0
DG & IG Police                               0.0       0.00    0.0    0.0
Departments                                 34.0       0.04  147.0  185.0
Governor                                     0.0       0.00    0.0    0.0
NaN                                          0.0       0.00    0.0    0.0
Office of Chief Minister                     1.0       0.00   20.0   20.0
Superintendent of Police                     0.0       0.00    0.0    0.0

                         Aggregate                           \
                           Discard
                             count percentage   mean median
office
Chief Secretary             4976.0      34.35   11.0    1.0
Collector                  49252.0       9.01   16.0    2.0
DG & IG Police               930.0      11.48    5.0    2.0
Departments                38001.0      25.15   46.0    4.0
Governor                    1799.0      26.03   28.0    9.0
NaN                          500.0       4.83  218.0  124.0
Office of Chief Minister   17357.0      11.88   15.0    2.0
Superintendent of Police    5032.0      23.46   49.0    3.0

                                                                         \
                         Disposed with Benefit
                                         count percentage   mean median
office
Chief Secretary                         8558.0      59.07  168.0  117.0
Collector                              46545.0       8.51   75.0   35.0
DG & IG Police                           107.0       1.32   89.0   56.0
Departments                             6063.0       4.01  114.0   67.0
Governor                                   6.0       0.09  172.0  148.0
NaN                                     2873.0      27.73  107.0   59.0
Office of Chief Minister                2978.0       2.04  180.0  113.0
Superintendent of Police                3078.0      14.35   76.0   32.0

                                                             \
                          Disposed
                             count percentage   mean median
office
Chief Secretary              953.0       6.58  158.0  130.0
Collector                 450969.0      82.48   77.0   41.0
DG & IG Police              7061.0      87.18   96.0   55.0
Departments               106969.0      70.80  119.0   77.0
Governor                    5107.0      73.89  171.0  132.0
NaN                         6988.0      67.45  139.0   74.0
Office of Chief Minister  125754.0      86.08  117.0   64.0
Superintendent of Police   13336.0      62.17  106.0   51.0


                         In Follow Up With Close
                                           count percentage   mean median
office
Chief Secretary                              0.0       0.00    0.0    0.0
Collector                                   22.0       0.00   50.0   32.0
DG & IG Police                               1.0       0.01  149.0  149.0
Departments                                 45.0       0.03  153.0  178.0
Governor                                     0.0       0.00    0.0    0.0
NaN                                          0.0       0.00    0.0    0.0
Office of Chief Minister                     1.0       0.00   20.0   20.0
Superintendent of Police                     4.0       0.02   21.0   12.0

In [21]:
pivot_pet_bucket_dept = petitioner_disposal_time_pivot(
    df_res, "dept")
pivot_pet_bucket_dept

                                                   2021-2022             \
                                                     Discard
                                                       count percentage
dept
Agriculture & Farmers' Empowerment                      70.0       4.14
Co-operation                                             7.0       2.82
Commerce & Transport                                    12.0       3.57
Electronics & Information Technology                     4.0       5.48
Energy                                                  13.0       1.25
Excise                                                   2.0       1.42
Finance                                                 13.0       5.65
Fisheries & Animal Resources Development                 1.0       0.53
Food Supplies & Consumer Welfare                        42.0       1.83
Forest, Environment and Climate Change Department        5.0       2.00
General Administration & Public Grievance              156.0       8.64
Handlooms ,Textiles & Handicrafts                        1.0       3.33
Health & Family Welfare                                 78.0       2.58
Higher Education                                        58.0      12.64
Home department                                        172.0       2.38
Housing & Urban Development                            123.0       2.20
Industries                                               4.0       7.02
Information & Public Relations                          10.0      17.24
Labour & Employees' State Insurance                     12.0       3.05
Law                                                      2.0       2.17
Micro, Small & Medium Enterprise                         4.0      12.50
Mission Shakti                                           0.0       0.00
NaN                                                   7525.0      33.47
Odia Language Literature & Culture                       2.0       1.54
Panchayati Raj & Drinking Water                        250.0       1.58
Parliamentary Affairs                                    0.0       0.00
Planning & Convergence                                   1.0       2.50
Public Enterprises                                       0.0       0.00
Revenue & Disaster Management                          158.0       3.23
Rural Development                                       42.0       8.84
ST & SC Development, Minorities & Backward Clas...      49.0       9.63
School & Mass Education                                 58.0       2.17
Science & Technology                                     0.0       0.00
Skill Development & Technical Education                  8.0       4.91
Social Security & Empowerment of Persons with D...      69.0       4.61
Sports & Youth Services                                  1.0       2.27
Steel & Mines                                            6.0      10.53
Tourism                                                  3.0       8.33
Water Resources                                         14.0       2.53
Women & Child Development                                6.0       1.16
Works                                                   40.0      10.42

                                                                  \

                                                     mean median
dept
Agriculture & Farmers' Empowerment                   85.0   25.0
Co-operation                                        251.0  243.0
Commerce & Transport                                158.0  151.0
Electronics & Information Technology                222.0  152.0
Energy                                              188.0   69.0
Excise                                               70.0   70.0
Finance                                             529.0  526.0
Fisheries & Animal Resources Development             29.0   29.0
Food Supplies & Consumer Welfare                    254.0  198.0
Forest, Environment and Climate Change Department   252.0  285.0
General Administration & Public Grievance           130.0  101.0
Handlooms ,Textiles & Handicrafts                   201.0  201.0
Health & Family Welfare                             414.0  426.0
Higher Education                                    629.0  692.0
Home department                                     185.0  139.0
Housing & Urban Development                         210.0  166.0
Industries                                           90.0   98.0
Information & Public Relations                      113.0   71.0
Labour & Employees' State Insurance                 174.0  107.0
Law                                                 348.0  348.0
Micro, Small & Medium Enterprise                    325.0  325.0
Mission Shakti                                        0.0    0.0
NaN                                                  43.0    2.0
Odia Language Literature & Culture                  167.0  167.0
Panchayati Raj & Drinking Water                     189.0  134.0
Parliamentary Affairs                                 0.0    0.0
Planning & Convergence                              121.0  121.0
Public Enterprises                                    0.0    0.0
Revenue & Disaster Management                       192.0  189.0
Rural Development                                   120.0   49.0
ST & SC Development, Minorities & Backward Clas...  454.0  456.0
School & Mass Education                             350.0  230.0
Science & Technology                                  0.0    0.0
Skill Development & Technical Education             433.0  420.0
Social Security & Empowerment of Persons with D...  231.0  190.0
Sports & Youth Services                             243.0  243.0
Steel & Mines                                       105.0  100.0
Tourism                                             308.0  330.0
Water Resources                                     322.0  121.0
Women & Child Development                           206.0   53.0
Works                                               184.0  140.0

                                                                          \
                                                   Disposed with Benefit
                                                                   count
dept
Agriculture & Farmers' Empowerment                                 142.0
Co-operation                                                        16.0
Commerce & Transport                                                29.0
Electronics & Information Technology                                 7.0
Energy                                                             301.0
Excise                                                               5.0
Finance                                                             40.0
Fisheries & Animal Resources Development                            36.0
Food Supplies & Consumer Welfare                                   594.0
Forest, Environment and Climate Change Department                   30.0
General Administration & Public Grievance                          279.0
Handlooms ,Textiles & Handicrafts                                   11.0
Health & Family Welfare                                            505.0
Higher Education                                                    57.0
Home department                                                   1367.0
Housing & Urban Development                                        952.0
Industries                                                           8.0
Information & Public Relations                                      12.0
Labour & Employees' State Insurance                                 40.0
Law                                                                  8.0
Micro, Small & Medium Enterprise                                     3.0
Mission Shakti                                                       4.0
NaN                                                               1230.0
Odia Language Literature & Culture                                   8.0
Panchayati Raj & Drinking Water                                   2419.0
Parliamentary Affairs                                                1.0
Planning & Convergence                                              12.0
Public Enterprises                                                   1.0
Revenue & Disaster Management                                      832.0
Rural Development                                                   62.0
ST & SC Development, Minorities & Backward Clas...                  63.0
School & Mass Education                                            322.0
Science & Technology                                                 0.0
Skill Development & Technical Education                             27.0
Social Security & Empowerment of Persons with D...                 206.0
Sports & Youth Services                                              4.0
Steel & Mines                                                        2.0
Tourism                                                              9.0
Water Resources                                                    159.0
Women & Child Development                                           47.0
Works                                                               73.0

                                                                             \

                                                   percentage   mean median
dept
Agriculture & Farmers' Empowerment                       8.39  151.0  112.0
Co-operation                                             6.45  422.0  458.0
Commerce & Transport                                     8.63  153.0  147.0
Electronics & Information Technology                     9.59  161.0  169.0
Energy                                                  28.89  124.0   63.0
Excise                                                   3.55  216.0  191.0
Finance                                                 17.39  391.0  298.0
Fisheries & Animal Resources Development                18.95  215.0  108.0
Food Supplies & Consumer Welfare                        25.93  143.0  101.0
Forest, Environment and Climate Change Department       12.00  339.0  228.0
General Administration & Public Grievance               15.46  139.0   77.0
Handlooms ,Textiles & Handicrafts                       36.67  247.0  321.0
Health & Family Welfare                                 16.71  272.0  261.0
Higher Education                                        12.42  460.0  483.0
Home department                                         18.91  149.0   99.0
Housing & Urban Development                             17.00  147.0   93.0
Industries                                              14.04  271.0  232.0
Information & Public Relations                          20.69  103.0   85.0
Labour & Employees' State Insurance                     10.15  189.0  157.0
Law                                                      8.70  257.0  162.0
Micro, Small & Medium Enterprise                         9.38  474.0  457.0
Mission Shakti                                           5.97  297.0  228.0
NaN                                                      5.47  402.0  368.0
Odia Language Literature & Culture                       6.15  393.0  300.0
Panchayati Raj & Drinking Water                         15.33  149.0  105.0
Parliamentary Affairs                                    5.88  275.0  275.0
Planning & Convergence                                  30.00  188.0  178.0
Public Enterprises                                       9.09  517.0  517.0
Revenue & Disaster Management                           16.99  119.0   80.0
Rural Development                                       13.05  200.0  137.0
ST & SC Development, Minorities & Backward Clas...      12.38  250.0  113.0
School & Mass Education                                 12.05  251.0  154.0
Science & Technology                                     0.00    0.0    0.0
Skill Development & Technical Education                 16.56  418.0  419.0
Social Security & Empowerment of Persons with D...      13.75  172.0  125.0
Sports & Youth Services                                  9.09   83.0   26.0
Steel & Mines                                            3.51  217.0  217.0
Tourism                                                 25.00  285.0  192.0
Water Resources                                         28.70  366.0  337.0
Women & Child Development                                9.11  130.0  109.0
Works                                                   19.01  181.0  134.0

                                                                               \
                                                   Disposed
                                                      count percentage   mean
dept
Agriculture & Farmers' Empowerment                   1480.0      87.47   92.0
Co-operation                                          225.0      90.73  415.0
Commerce & Transport                                  293.0      87.20  293.0
Electronics & Information Technology                   62.0      84.93  188.0
Energy                                                727.0      69.77  125.0
Excise                                                133.0      94.33  186.0
Finance                                               177.0      76.96  365.0
Fisheries & Animal Resources Development              153.0      80.53  152.0
Food Supplies & Consumer Welfare                     1654.0      72.20  183.0
Forest, Environment and Climate Change Department     215.0      86.00  254.0
General Administration & Public Grievance            1367.0      75.73  186.0
Handlooms ,Textiles & Handicrafts                      18.0      60.00  232.0
Health & Family Welfare                              2439.0      80.71  245.0
Higher Education                                      343.0      74.73  482.0
Home department                                      5688.0      78.67  171.0
Housing & Urban Development                          4523.0      80.78  187.0
Industries                                             45.0      78.95  220.0
Information & Public Relations                         36.0      62.07  142.0
Labour & Employees' State Insurance                   341.0      86.55  206.0
Law                                                    82.0      89.13  344.0
Micro, Small & Medium Enterprise                       25.0      78.12  381.0
Mission Shakti                                         63.0      94.03  127.0
NaN                                                 13724.0      61.05  340.0
Odia Language Literature & Culture                    120.0      92.31  450.0
Panchayati Raj & Drinking Water                     13104.0      83.06  153.0
Parliamentary Affairs                                  16.0      94.12  188.0
Planning & Convergence                                 27.0      67.50  232.0
Public Enterprises                                     10.0      90.91   88.0
Revenue & Disaster Management                        3900.0      79.62  158.0
Rural Development                                     370.0      77.89  197.0
ST & SC Development, Minorities & Backward Clas...    397.0      78.00  252.0
School & Mass Education                              2287.0      85.59  302.0
Science & Technology                                    7.0     100.00  248.0
Skill Development & Technical Education               128.0      78.53  542.0
Social Security & Empowerment of Persons with D...   1222.0      81.58  171.0
Sports & Youth Services                                39.0      88.64  132.0
Steel & Mines                                          49.0      85.96  199.0
Tourism                                                24.0      66.67  313.0
Water Resources                                       381.0      68.77  329.0
Women & Child Development                             463.0      89.73  174.0
Works                                                 271.0      70.57  221.0

                                                           \

                                                   median
dept
Agriculture & Farmers' Empowerment                   47.0
Co-operation                                        426.0
Commerce & Transport                                265.0
Electronics & Information Technology                171.0
Energy                                               56.0
Excise                                              193.0
Finance                                             364.0
Fisheries & Animal Resources Development            112.0
Food Supplies & Consumer Welfare                    127.0
Forest, Environment and Climate Change Department   218.0
General Administration & Public Grievance            97.0
Handlooms ,Textiles & Handicrafts                   241.0
Health & Family Welfare                             160.0
Higher Education                                    524.0
Home department                                     107.0
Housing & Urban Development                         111.0
Industries                                           95.0
Information & Public Relations                       99.0
Labour & Employees' State Insurance                 173.0
Law                                                 363.0
Micro, Small & Medium Enterprise                    319.0
Mission Shakti                                      112.0
NaN                                                 296.0
Odia Language Literature & Culture                  410.0
Panchayati Raj & Drinking Water                     107.0
Parliamentary Affairs                               117.0
Planning & Convergence                              140.0
Public Enterprises                                   32.0
Revenue & Disaster Management                       117.0
Rural Development                                   111.0
ST & SC Development, Minorities & Backward Clas...  183.0
School & Mass Education                             216.0
Science & Technology                                207.0
Skill Development & Technical Education             506.0
Social Security & Empowerment of Persons with D...  110.0
Sports & Youth Services                              99.0
Steel & Mines                                       143.0
Tourism                                             257.0
Water Resources                                     166.0
Women & Child Development                           109.0
Works                                               156.0

                                                                            \
                                                   In Follow Up With Close
                                                                     count
dept
Agriculture & Farmers' Empowerment                                     0.0
Co-operation                                                           0.0
Commerce & Transport                                                   2.0
Electronics & Information Technology                                   0.0
Energy                                                                 1.0
Excise                                                                 1.0
Finance                                                                0.0
Fisheries & Animal Resources Development                               0.0
Food Supplies & Consumer Welfare                                       1.0
Forest, Environment and Climate Change Department                      0.0
General Administration & Public Grievance                              3.0
Handlooms ,Textiles & Handicrafts                                      0.0
Health & Family Welfare                                                0.0
Higher Education                                                       1.0
Home department                                                        3.0
Housing & Urban Development                                            1.0
Industries                                                             0.0
Information & Public Relations                                         0.0

In [22]:
pivot_pet_bucket_category = petitioner_disposal_time_pivot(
    df_res, "category")
pivot_pet_bucket_category

                            2021-2022                           \
                              Discard
                                count percentage   mean median
category
Accident                          1.0       7.69  243.0  243.0
Agriculture & Farming            24.0       2.86  199.0   62.0
BSKY                              0.0       0.00    0.0    0.0
CMRF                              3.0       0.58  411.0  460.0
COVID-19                          6.0       4.14  235.0  147.0
Culture                           0.0       0.00    0.0    0.0
Disaster Management               0.0       0.00    0.0    0.0
Education                        55.0       6.70  530.0  546.0
Energy                           26.0       2.21  200.0  166.0
Environment                       0.0       0.00    0.0    0.0
Excise                            1.0       0.75  121.0  121.0
Financial Assistance             17.0       2.46  214.0  187.0
General                         247.0       2.51  222.0  166.0
Health Care                      49.0       3.13  375.0  348.0
Housing                         145.0       1.22  125.0   80.0
ICDS                              2.0       1.14   50.0   50.0
Infrastructure                   92.0       5.89  200.0  105.0
Irrigation                        0.0       0.00    0.0    0.0
Land Matters                     66.0       2.97  153.0  132.0
Legal                             0.0       0.00    0.0    0.0
Miscellaneous                   144.0       4.61  180.0  120.0
NaN                            7699.0      31.77   49.0    2.0
Pension/Retirement Benefits      30.0       2.61  243.0  125.0
Police Case                      95.0       2.09  130.0  101.0
Public Utility                   24.0       3.42  195.0  141.0
Scheme &amp;amp; Benefits         0.0       0.00    0.0    0.0
School & College                  7.0       2.77  559.0  781.0
Service Matters                 111.0       3.98  241.0  153.0
Social Welfare                  128.0       2.39  181.0   98.0
Sports                            1.0       2.86  243.0  243.0
Tourism                           0.0       0.00    0.0    0.0
Traffic                           0.0       0.00    0.0    0.0
Transport                         6.0       2.75  201.0  194.0
Waste Management                  9.0       4.41  241.0  271.0
Water Supply                     23.0       1.67  254.0  216.0
Women Issues                      1.0       1.09  201.0  201.0

                                                                            \
                            Disposed with Benefit
                                            count percentage   mean median
category
Accident                                      3.0      23.08  148.0  174.0
Agriculture & Farming                        73.0       8.69  232.0  193.0
BSKY                                          4.0       7.41  166.0   42.0
CMRF                                        165.0      32.16  294.0  286.0
COVID-19                                     28.0      19.31  227.0   99.0
Culture                                       1.0       8.33   58.0   58.0
Disaster Management                          24.0      27.91  106.0  100.0
Education                                    83.0      10.11  294.0  110.0
Energy                                      366.0      31.12  131.0   80.0
Environment                                   6.0       5.45  201.0   46.0
Excise                                        4.0       3.01  151.0  179.0
Financial Assistance                         90.0      13.01  276.0  264.0
General                                    2412.0      24.49  152.0   79.0
Health Care                                 208.0      13.29  233.0  147.0
Housing                                     887.0       7.45  121.0   97.0
ICDS                                          5.0       2.86  111.0   91.0
Infrastructure                              264.0      16.91  219.0  165.0
Irrigation                                    0.0       0.00    0.0    0.0
Land Matters                                303.0      13.65  105.0   58.0
Legal                                         1.0       7.14  194.0  194.0
Miscellaneous                               585.0      18.73  183.0  143.0
NaN                                        1546.0       6.38  376.0  324.0
Pension/Retirement Benefits                 667.0      58.00  132.0   80.0
Police Case                                 865.0      19.01  138.0   80.0
Public Utility                               74.0      10.56  263.0  269.0
Scheme &amp;amp; Benefits                     0.0       0.00    0.0    0.0
School & College                             13.0       5.14  175.0  125.0
Service Matters                             345.0      12.36  281.0  272.0
Social Welfare                              503.0       9.38  172.0  138.0
Sports                                        1.0       2.86  258.0  258.0
Tourism                                       0.0       0.00    0.0    0.0
Traffic                                       4.0      19.05  137.0  141.0
Transport                                    11.0       5.05  127.0  148.0
Waste Management                             73.0      35.78  103.0   92.0
Water Supply                                365.0      26.56  150.0   92.0
Women Issues                                  7.0       7.61  227.0  163.0

                                                               \
                            Disposed
                               count percentage   mean median
category
Accident                         9.0      69.23  157.0  113.0
Agriculture & Farming          743.0      88.45  187.0  109.0
BSKY                            50.0      92.59  231.0  200.0
CMRF                           345.0      67.25  293.0  269.0
COVID-19                       111.0      76.55  255.0  241.0
Culture                         11.0      91.67  131.0   39.0
Disaster Management             62.0      72.09  169.0  145.0
Education                      681.0      82.95  325.0  226.0
Energy                         783.0      66.58  151.0   82.0
Environment                    104.0      94.55  203.0  147.0
Excise                         127.0      95.49  180.0  193.0
Financial Assistance           585.0      84.54  230.0  142.0
General                       7177.0      72.88  204.0  132.0
Health Care                   1308.0      83.58  192.0  105.0
Housing                      10865.0      91.31  129.0   93.0
ICDS                           168.0      96.00  180.0  120.0
Infrastructure                1204.0      77.13  240.0  160.0
Irrigation                       0.0       0.00    0.0    0.0
Land Matters                  1848.0      83.28  144.0  103.0
Legal                           13.0      92.86  234.0   69.0
Miscellaneous                 2395.0      76.66  229.0  161.0
NaN                          14989.0      61.84  346.0  300.0
Pension/Retirement Benefits    451.0      39.22  270.0  182.0
Police Case                   3587.0      78.84  146.0   91.0
Public Utility                 601.0      85.73  259.0  174.0
Scheme &amp;amp; Benefits        1.0     100.00  186.0  186.0
School & College               233.0      92.09  247.0  148.0
Service Matters               2334.0      83.63  246.0  167.0
Social Welfare                4729.0      88.18  142.0   80.0
Sports                          33.0      94.29  134.0   85.0
Tourism                          7.0     100.00  207.0   60.0
Traffic                         17.0      80.95   93.0   44.0
Transport                      200.0      91.74  301.0  281.0
Waste Management               122.0      59.80  213.0  207.0
Water Supply                   986.0      71.76  184.0  113.0
Women Issues                    84.0      91.30  168.0   72.0

                                                                              \
                            In Follow Up With Close
                                              count percentage   mean median
category
Accident                                        0.0       0.00    0.0    0.0
Agriculture & Farming                           0.0       0.00    0.0    0.0
BSKY                                            0.0       0.00    0.0    0.0
CMRF                                            0.0       0.00    0.0    0.0
COVID-19                                        0.0       0.00    0.0    0.0
Culture                                         0.0       0.00    0.0    0.0
Disaster Management                             0.0       0.00    0.0    0.0
Education                                       2.0       0.24   42.0   42.0
Energy                                          1.0       0.09   74.0   74.0
Environment                                     0.0       0.00    0.0    0.0
Excise                                          1.0       0.75  152.0  152.0
Financial Assistance                            0.0       0.00    0.0    0.0
General                                        12.0       0.12   41.0   27.0
Health Care                                     0.0       0.00    0.0    0.0
Housing                                         2.0       0.02   14.0   14.0
ICDS                                            0.0       0.00    0.0    0.0
Infrastructure                                  1.0       0.06   16.0   16.0
Irrigation                                      0.0       0.00    0.0    0.0
Land Matters                                    2.0       0.09   85.0   85.0
Legal                                           0.0       0.00    0.0    0.0
Miscellaneous                                   0.0       0.00    0.0    0.0
NaN                                             3.0       0.01  249.0  235.0
Pension/Retirement Benefits                     2.0       0.17   25.0   12.0
Police Case                                     3.0       0.07   65.0   34.0
Public Utility                                  2.0       0.29  151.0  151.0
Scheme &amp;amp; Benefits                       0.0       0.00    0.0    0.0
School & College                                0.0       0.00    0.0    0.0
Service Matters                                 1.0       0.04   50.0   50.0
Social Welfare                                  3.0       0.06   77.0   88.0
Sports                                          0.0       0.00    0.0    0.0
Tourism                                         0.0       0.00    0.0    0.0
Traffic                                         0.0       0.00    0.0    0.0
Transport                                       1.0       0.46   32.0   32.0
Waste Management                                0.0       0.00    0.0    0.0
Water Supply                                    0.0       0.00    0.0    0.0
Women Issues                                    0.0       0.00    0.0    0.0

                            2022-2023                           \
                              Discard
                                count percentage   mean median
category
Accident                          0.0       0.00    0.0    0.0
Agriculture & Farming            18.0       1.49  203.0  133.0
BSKY                              2.0       2.20  251.0  251.0
CMRF                              0.0       0.00    0.0    0.0
COVID-19                          1.0       1.82  732.0  732.0
Culture                           0.0       0.00    0.0    0.0
Disaster Management               4.0       3.12  262.0  104.0
Education                        89.0       7.82  311.0  273.0
Energy                           28.0       1.34  180.0   26.0
Environment                       0.0       0.00    0.0    0.0
Excise                            3.0       1.84   17.0   14.0
Financial Assistance             20.0       0.92  140.0   25.0
General                         350.0       1.52  206.0  118.0
Health Care                      33.0       1.64  277.0  168.0
Housing                         140.0       0.43   51.0   25.0
ICDS                             10.0       3.69  173.0  209.0
Infrastructure                  157.0       4.52   81.0   26.0
Irrigation                        0.0       0.00    0.0    0.0
Land Matters                     85.0       1.31   75.0   27.0
Legal                             1.0       4.35  343.0  343.0
Miscellaneous                   229.0       2.55  105.0   37.0
NaN                           16580.0     100.00   11.0    1.0
Pension/Retirement Benefits      32.0       2.44  203.0  152.0
Police Case                     123.0       1.48  129.0   36.0
Public Utility                   23.0       1.38  221.0   84.0
Scheme &amp;amp; Benefits         0.0       0.00    0.0    0.0
School & College                  2.0       0.33  252.0  252.0
Service Matters                 172.0       4.12  186.0  150.0
Social Welfare                  143.0       0.82   91.0   35.0
Sports                            6.0       6.67   21.0   12.0
Tourism                           0.0       0.00    0.0    0.0
Traffic                           1.0       2.56   10.0   10.0
Transport                         4.0       1.11  338.0  321.0
Waste Management                  3.0       1.70   22.0   32.0
Water Supply                     30.0       1.46  221.0  130.0
Women Issues                      0.0       0.00    0.0    0.0

                                                                            \
                            Disposed with Benefit
                                            count percentage   mean median
category
Accident                                      6.0      17.14   27.0   23.0
Agriculture & Farming                       137.0      11.32  120.0   94.0
BSKY                                          7.0       7.69   69.0   59.0
CMRF                                        146.0      30.23  119.0  107.0
COVID-19                                      8.0      14.55   84.0   39.0
Culture                                       1.0      20.00  420.0  420.0
Disaster Management                          14.0      10.94   49.0   35.0
Education                                   155.0      13.62  183.0  114.0
Energy                                      472.0      22.61  107.0   45.0
Environment                                  11.0       8.15  186.0  153.0
Excise                                       11.0       6.75  109.0  109.0
Financial Assistance                        529.0      24.22  114.0   70.0
General                                    5167.0      22.46  128.0   47.0
Health Care                                 325.0      16.16  105.0   42.0
Housing                                    6882.0      20.90   44.0   24.0
ICDS                                         13.0       4.80  123.0   28.0
Infrastructure                              434.0      12.50  141.0   62.0
Irrigation                                    5.0      15.15  619.0  616.0
Land Matters                               1138.0      17.48   66.0   34.0
Legal                                         3.0      13.04   61.0    9.0
Miscellaneous                              1234.0      13.76   79.0   35.0
NaN                                           0.0       0.00    0.0    0.0
Pension/Retirement Benefits                 242.0      18.43  115.0   42.0
Police Case                                1146.0      13.81   80.0   34.0
Public Utility                              173.0      10.42  103.0   59.0
Scheme &amp;amp; Benefits                     0.0       0.00    0.0    0.0
School & College                             92.0      15.31  151.0   92.0
Service Matters                             744.0      17.80  142.0   60.0
Social Welfare                             1258.0       7.22   84.0   50.0
Sports                                        3.0       3.33   85.0   74.0
Tourism                                       0.0       0.00    0.0    0.0
Traffic                                       4.0      10.26  148.0   55.0
Transport                                     3.0       0.84   20.0   29.0
Waste Management                             59.0      33.52   40.0   13.0
Water Supply                                524.0      25.46  131.0   63.0
Women Issues                                 21.0      15.67   66.0   36.0

                                                               \
                            Disposed
                               count percentage   mean median
category
Accident                        29.0      82.86  107.0   66.0
Agriculture & Farming         1054.0      87.11  171.0   71.0
BSKY                            82.0      90.11   86.0   69.0
CMRF                           337.0      69.77  128.0  105.0
COVID-19                        46.0      83.64  153.0   93.0
Culture                          4.0      80.00  127.0   90.0
Disaster Management            110.0      85.94  111.0   44.0
Education                      894.0      78.56  211.0  138.0
Energy                        1587.0      76.01  113.0   36.0
Environment                    124.0      91.85  123.0   62.0
Excise                         149.0      91.41   88.0   55.0
Financial Assistance          1635.0      74.86  155.0   67.0
General                      17491.0      76.02  141.0   60.0
Health Care                   1653.0      82.20  108.0   39.0
Housing                      25913.0      78.68   74.0   45.0
ICDS                           248.0      91.51  120.0   69.0
Infrastructure                2881.0      82.98  151.0   54.0
Irrigation                      28.0      84.85  582.0  658.0
Land Matters                  5286.0      81.21   92.0   41.0
Legal                           19.0      82.61  150.0   92.0
Miscellaneous                 7506.0      83.69  129.0   63.0
NaN                              0.0       0.00    0.0    0.0
Pension/Retirement Benefits   1039.0      79.13  156.0   81.0
Police Case                   7027.0      84.69   75.0   37.0
Public Utility                1465.0      88.20  175.0   82.0
Scheme &amp;amp; Benefits        0.0       0.00    0.0    0.0
School & College               507.0      84.36  165.0   81.0
Service Matters               3263.0      78.08  169.0   94.0
Social Welfare               16029.0      91.96   72.0   34.0
Sports                          81.0      90.00   41.0   17.0
Tourism                          7.0     100.00  139.0   50.0
Traffic                         34.0      87.18  197.0   83.0
Transport                      352.0      98.05  121.0   79.0
Waste Management               114.0      64.77  106.0   40.0
Water Supply                  1504.0      73.08  159.0   64.0
Women Issues                   113.0      84.33   90.0   37.0

                                                                             \
                            In Follow Up With Close
                                              count percentage  mean median
category
Accident                                        0.0       0.00   0.0    0.0
Agriculture & Farming                           1.0       0.08  51.0   51.0
BSKY                                            0.0       0.00   0.0    0.0
CMRF                                            0.0       0.00   0.0    0.0
COVID-19                                        0.0       0.00   0.0    0.0
Culture                                         0.0       0.00   0.0    0.0
Disaster Management                             0.0       0.00   0.0    0.0
Education                                       0.0       0.00   0.0    0.0
Energy                                          1.0       0.05   3.0    3.0
Environment                                     0.0       0.00   0.0    0.0
Excise                                          0.0       0.00   0.0    0.0
Financial Assistance                            0.0       0.00   0.0    0.0
General                                         1.0       0.00  52.0   52.0
Health Care                                     0.0       0.00   0.0    0.0
Housing                                         1.0       0.00  11.0   11.0
ICDS                                            0.0       0.00   0.0    0.0

In [23]:
pivot_pet_bucket_subcategory = petitioner_disposal_time_pivot(
    df_res, "subcategory")
pivot_pet_bucket_subcategory.head(10)

                      2021-2022                           \
                        Discard
                          count percentage   mean median
subcategory
AIDS                        0.0       0.00    0.0    0.0
Aadhar Card Issues          0.0       0.00    0.0    0.0
Absence of officials        0.0       0.00    0.0    0.0
Absurd/Irrelevant           0.0       0.00    0.0    0.0
Accidental Claims           0.0       0.00    0.0    0.0
Admissions                  1.0       3.33  865.0  865.0
Agriculture/Farming         3.0       2.03  153.0  160.0
Ahar Yojana                 0.0       0.00    0.0    0.0
Allegation/Corruption      19.0       3.85  123.0   38.0
Anganwadi Centres           0.0       0.00    0.0    0.0

                                                                               \
                      Disposed with Benefit                          Disposed
                                      count percentage   mean median    count
subcategory
AIDS                                    0.0       0.00    0.0    0.0      0.0
Aadhar Card Issues                      1.0       6.67  131.0  131.0     14.0
Absence of officials                    0.0       0.00    0.0    0.0      0.0
Absurd/Irrelevant                       1.0      20.00  152.0  152.0      4.0
Accidental Claims                       0.0       0.00    0.0    0.0      5.0
Admissions                              5.0      16.67  114.0  102.0     24.0
Agriculture/Farming                    13.0       8.78  307.0  261.0    132.0
Ahar Yojana                             1.0      20.00   17.0   17.0      4.0
Allegation/Corruption                  32.0       6.49  195.0  164.0    442.0
Anganwadi Centres                       0.0       0.00    0.0    0.0      0.0

                                                                        \
                                               In Follow Up With Close
                      percentage   mean median                   count
subcategory
AIDS                        0.00    0.0    0.0                     0.0
Aadhar Card Issues         93.33  198.0  161.0                     0.0
Absence of officials        0.00    0.0    0.0                     0.0
Absurd/Irrelevant          80.00  409.0  230.0                     0.0
Accidental Claims         100.00  164.0  153.0                     0.0
Admissions                 80.00  284.0  219.0                     0.0
Agriculture/Farming        89.19  195.0  138.0                     0.0
Ahar Yojana                80.00  163.0  202.0                     0.0
Allegation/Corruption      89.66  282.0  233.0                     0.0
Anganwadi Centres           0.00    0.0    0.0                     0.0

                                             2022-2023                    \
                                               Discard
                      percentage mean median     count percentage   mean
subcategory
AIDS                         0.0  0.0    0.0       0.0       0.00    0.0
Aadhar Card Issues           0.0  0.0    0.0       0.0       0.00    0.0
Absence of officials         0.0  0.0    0.0       0.0       0.00    0.0
Absurd/Irrelevant            0.0  0.0    0.0       0.0       0.00    0.0
Accidental Claims            0.0  0.0    0.0       0.0       0.00    0.0
Admissions                   0.0  0.0    0.0       0.0       0.00    0.0
Agriculture/Farming          0.0  0.0    0.0       4.0       0.96  181.0
Ahar Yojana                  0.0  0.0    0.0       0.0       0.00    0.0
Allegation/Corruption        0.0  0.0    0.0      28.0       1.92  158.0
Anganwadi Centres            0.0  0.0    0.0       0.0       0.00    0.0

                                                                             \
                             Disposed with Benefit
                      median                 count percentage   mean median
subcategory
AIDS                     0.0                   0.0       0.00    0.0    0.0
Aadhar Card Issues       0.0                   4.0      30.77   75.0   27.0
Absence of officials     0.0                   0.0       0.00    0.0    0.0
Absurd/Irrelevant        0.0                   1.0       8.33   45.0   45.0
Accidental Claims        0.0                   5.0      22.73   53.0   13.0
Admissions               0.0                  49.0      42.61  166.0   92.0
Agriculture/Farming    194.0                  40.0       9.64   95.0   53.0
Ahar Yojana              0.0                   2.0      33.33   85.0   85.0
Allegation/Corruption  108.0                 167.0      11.48  102.0   55.0
Anganwadi Centres        0.0                   0.0       0.00    0.0    0.0

                                                         \
                      Disposed
                         count percentage   mean median
subcategory
AIDS                       1.0     100.00   14.0   14.0
Aadhar Card Issues         9.0      69.23   46.0   28.0
Absence of officials       0.0       0.00    0.0    0.0
Absurd/Irrelevant         11.0      91.67  206.0  164.0
Accidental Claims         17.0      77.27  137.0   57.0
Admissions                66.0      57.39  137.0   61.0
Agriculture/Farming      370.0      89.16  129.0   52.0
Ahar Yojana                4.0      66.67   81.0   51.0
Allegation/Corruption   1260.0      86.60  160.0   80.0
Anganwadi Centres          2.0     100.00  372.0  372.0

                                                                       \
                      In Follow Up With Close
                                        count percentage  mean median
subcategory
AIDS                                      0.0       0.00   0.0    0.0
Aadhar Card Issues                        0.0       0.00   0.0    0.0
Absence of officials                      0.0       0.00   0.0    0.0
Absurd/Irrelevant                         0.0       0.00   0.0    0.0
Accidental Claims                         0.0       0.00   0.0    0.0
Admissions                                0.0       0.00   0.0    0.0
Agriculture/Farming                       1.0       0.24  51.0   51.0
Ahar Yojana                               0.0       0.00   0.0    0.0
Allegation/Corruption                     0.0       0.00   0.0    0.0
Anganwadi Centres                         0.0       0.00   0.0    0.0

                      2023-2024                           \
                        Discard
                          count percentage   mean median
subcategory
AIDS                        1.0      25.00  101.0  101.0
Aadhar Card Issues          1.0       4.17   99.0   99.0
Absence of officials        0.0       0.00    0.0    0.0
Absurd/Irrelevant           0.0       0.00    0.0    0.0
Accidental Claims           0.0       0.00    0.0    0.0
Admissions                  1.0       0.66  147.0  147.0
Agriculture/Farming         8.0       1.51   99.0   40.0
Ahar Yojana                 0.0       0.00    0.0    0.0
Allegation/Corruption      24.0       1.38   93.0   54.0
Anganwadi Centres           7.0       2.72   80.0   66.0

                                                                               \
                      Disposed with Benefit                          Disposed
                                      count percentage   mean median    count
subcategory
AIDS                                    1.0      25.00   31.0   31.0      2.0
Aadhar Card Issues                      4.0      16.67  201.0  197.0     19.0
Absence of officials                    1.0      50.00  506.0  506.0      1.0
Absurd/Irrelevant                       1.0      12.50    0.0    0.0      7.0
Accidental Claims                       3.0       8.82  166.0   17.0     31.0
Admissions                             29.0      19.21   90.0   55.0    121.0
Agriculture/Farming                    43.0       8.11  115.0   78.0    479.0
Ahar Yojana                             2.0       6.67   46.0   46.0     28.0
Allegation/Corruption                 187.0      10.77  174.0   87.0   1526.0
Anganwadi Centres                      15.0       5.84  107.0   46.0    235.0

                                                                        \
                                               In Follow Up With Close
                      percentage   mean median                   count
subcategory
AIDS                       50.00  105.0  105.0                     0.0
Aadhar Card Issues         79.17  287.0  305.0                     0.0
Absence of officials       50.00   20.0   20.0                     0.0
Absurd/Irrelevant          87.50  194.0  151.0                     0.0
Accidental Claims          91.18  151.0   71.0                     0.0
Admissions                 80.13  164.0  112.0                     0.0
Agriculture/Farming        90.38  127.0   65.0                     0.0
Ahar Yojana                93.33  122.0  123.0                     0.0
Allegation/Corruption      87.85  183.0  125.0                     0.0
Anganwadi Centres          91.44  135.0   73.0                     0.0

                                             2024-2025                   \
                                               Discard
                      percentage mean median     count percentage  mean
subcategory
AIDS                         0.0  0.0    0.0       0.0       0.00   0.0
Aadhar Card Issues           0.0  0.0    0.0       4.0       3.77  36.0
Absence of officials         0.0  0.0    0.0       0.0       0.00   0.0
Absurd/Irrelevant            0.0  0.0    0.0       1.0       3.33  56.0
Accidental Claims            0.0  0.0    0.0       3.0       3.33  84.0
Admissions                   0.0  0.0    0.0       3.0       0.99   3.0
Agriculture/Farming          0.0  0.0    0.0       7.0       1.47  67.0
Ahar Yojana                  0.0  0.0    0.0       0.0       0.00   0.0
Allegation/Corruption        0.0  0.0    0.0      56.0       1.36  47.0
Anganwadi Centres            0.0  0.0    0.0       4.0       0.89  73.0

                                                                             \
                             Disposed with Benefit
                      median                 count percentage   mean median
subcategory
AIDS                     0.0                   0.0       0.00    0.0    0.0
Aadhar Card Issues      18.0                   5.0       4.72   62.0   54.0
Absence of officials     0.0                   0.0       0.00    0.0    0.0
Absurd/Irrelevant       56.0                   1.0       3.33   28.0   28.0
Accidental Claims       65.0                   7.0       7.78   75.0   33.0
Admissions               0.0                  25.0       8.28   58.0   36.0
Agriculture/Farming     53.0                  18.0       3.79   62.0   53.0
Ahar Yojana              0.0                   3.0      10.71   28.0   16.0
Allegation/Corruption   28.0                  93.0       2.26   68.0   47.0
Anganwadi Centres       69.0                  19.0       4.25  124.0   90.0

                                                         \
                      Disposed
                         count percentage   mean median
subcategory
AIDS                      12.0     100.00   42.0   34.0
Aadhar Card Issues        97.0      91.51   64.0   39.0
Absence of officials       0.0       0.00    0.0    0.0
Absurd/Irrelevant         28.0      93.33  101.0   79.0
Accidental Claims         80.0      88.89   72.0   59.0
Admissions               274.0      90.73   64.0   41.0
Agriculture/Farming      450.0      94.74   67.0   50.0
Ahar Yojana               25.0      89.29   56.0   24.0
Allegation/Corruption   3963.0      96.38  110.0   89.0
Anganwadi Centres        424.0      94.85   80.0   58.0

                                                                      \
                      In Follow Up With Close
                                        count percentage mean median
subcategory
AIDS                                      0.0        0.0  0.0    0.0
Aadhar Card Issues                        0.0        0.0  0.0    0.0
Absence of officials                      0.0        0.0  0.0    0.0
Absurd/Irrelevant                         0.0        0.0  0.0    0.0
Accidental Claims                         0.0        0.0  0.0    0.0
Admissions                                0.0        0.0  0.0    0.0
Agriculture/Farming                       0.0        0.0  0.0    0.0
Ahar Yojana                               0.0        0.0  0.0    0.0
Allegation/Corruption                     0.0        0.0  0.0    0.0
Anganwadi Centres                         0.0        0.0  0.0    0.0

                      Aggregate                           \
                        Discard
                          count percentage   mean median
subcategory
AIDS                        1.0       5.88  101.0  101.0
Aadhar Card Issues          5.0       3.18   49.0   26.0
Absence of officials        0.0       0.00    0.0    0.0
Absurd/Irrelevant           1.0       1.82   56.0   56.0
Accidental Claims           3.0       1.99   84.0   65.0
Admissions                  5.0       0.84  204.0    8.0
Agriculture/Farming        22.0       1.43  102.0   73.0
Ahar Yojana                 0.0       0.00    0.0    0.0
Allegation/Corruption     126.0       1.68   67.0   29.0
Anganwadi Centres          11.0       1.58   78.0   66.0

                                                                               \
                      Disposed with Benefit                          Disposed
                                      count percentage   mean median    count
subcategory
AIDS                                    1.0       5.88   31.0   31.0     15.0
Aadhar Card Issues                     14.0       8.92  110.0   95.0    138.0
Absence of officials                    1.0      50.00  506.0  506.0      1.0
Absurd/Irrelevant                       4.0       7.27   56.0   36.0     50.0
Accidental Claims                      15.0       9.93   86.0   26.0    133.0
Admissions                            107.0      18.07  118.0   67.0    480.0
Agriculture/Farming                   114.0       7.41  121.0   72.0   1401.0
Ahar Yojana                             8.0      11.59   45.0   32.0     61.0
Allegation/Corruption                 469.0       6.27  133.0   66.0   6886.0
Anganwadi Centres                      34.0       4.89  117.0   60.0    651.0

                                                                        \
                                               In Follow Up With Close
                      percentage   mean median                   count
subcategory
AIDS                       88.24   48.0   34.0                     0.0
Aadhar Card Issues         87.90  108.0   60.0                     0.0
Absence of officials       50.00   20.0   20.0                     0.0
Absurd/Irrelevant          90.91  158.0   93.0                     0.0
Accidental Claims          88.08  102.0   64.0                     0.0
Admissions                 81.08  109.0   59.0                     0.0
Agriculture/Farming        91.09  113.0   56.0                     1.0
Ahar Yojana                88.41   95.0   59.0                     0.0
Allegation/Corruption      92.05  130.0   93.0                     0.0
Anganwadi Centres          93.53  100.0   61.0                     0.0



                      percentage  mean median
subcategory
AIDS                        0.00   0.0    0.0
Aadhar Card Issues          0.00   0.0    0.0
Absence of officials        0.00   0.0    0.0
Absurd/Irrelevant           0.00   0.0    0.0
Accidental Claims           0.00   0.0    0.0
Admissions                  0.00   0.0    0.0
Agriculture/Farming         0.07  51.0   51.0
Ahar Yojana                 0.00   0.0    0.0
Allegation/Corruption       0.00   0.0    0.0
Anganwadi Centres           0.00   0.0    0.0