# 06 - NaN Subcategory Deep Dive

All analyses of grievances whose `subcategory` is missing (`NaN` or empty
string).

Shared scaffolding is in `grievance_common.py`.

## Setup

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import geopandas as gpd

from grievance_common import (
    load_complaints, add_time_fields, filter_window, population_df,
    load_district_shapefile, draw_choropleth,
    OUTPUT_DIR, FOCUS_YEAR, VALID_YEARS,
)

# IPython display() is auto-available in Jupyter; fall back outside it.
try:
    from IPython.display import display
except ImportError:
    display = print

## Data Load

Load the complaints table, derive time fields, apply the analysis window.
Two NaN definitions are useful: the dataset has both true-null subcategories
and blank strings; we treat both as NaN.

In [2]:
df = add_time_fields(load_complaints())
df = filter_window(df)

# NaN filter: subcategory is missing OR blank string.
nan_mask = df["subcategory"].isna() | (
    df["subcategory"].astype(str).str.strip().isin(["", "NaN"])
)
print(f"Total complaints in window : {len(df):,}")
print(f"With NaN subcategory       : {int(nan_mask.sum()):,}")
print(f"NaN share                  : {nan_mask.mean()*100:.2f}%")

Total complaints in window : 1,323,840
With NaN subcategory       : 197,952
NaN share                  : 14.95%

In [4]:
df["year_month"] = df["created_on"].dt.to_period("M").astype(str)
df["district"]   = df["district"].fillna("NaN").astype(str).str.strip()
df["block"]      = df["block"].fillna("NaN").astype(str).str.strip()
if "petitioner_name" in df.columns:
    df["petitioner_name"] = (df["petitioner_name"].fillna("NaN")
                             .astype(str).str.strip())

## Helper Functions

In [5]:
# ----- NaN identification ----------------------------------------------------
 
def nan_mask(frame, col="subcategory"):
    """True where col is null or blank/NaN string."""
    return frame[col].isna() | (
        frame[col].astype(str).str.strip().isin(["", "NaN"]))
 
 
# ----- count + NaN + pct -----------------------------------------------------
 
def nan_dist_table(frame, group_cols, nan_frame=None):
    """Total complaints, NaN complaints and NaN pct by group_cols."""
    if isinstance(group_cols, str):
        group_cols = [group_cols]
    if nan_frame is None:
        nan_frame = frame[nan_mask(frame)]
    total = (frame.groupby(group_cols)["ticket_no"]
             .nunique().reset_index(name="total_complaints"))
    nan_c = (nan_frame.groupby(group_cols)["ticket_no"]
             .nunique().reset_index(name="nan_complaints"))
    out = total.merge(nan_c, on=group_cols, how="left")
    out["nan_complaints"] = out["nan_complaints"].fillna(0).astype(int)
    out["nan_pct"] = (
        out["nan_complaints"] / out["total_complaints"] * 100).round(2)
    return out
 
 
def nan_dist_with_aggregate(frame, group_col, nan_frame=None):
    """nan_dist_table by group_col x year + Aggregate column.
    Returns (long table, wide pivot)."""
    if nan_frame is None:
        nan_frame = frame[nan_mask(frame)]
    long = nan_dist_table(frame, [group_col, "custom_year"],
                          nan_frame=nan_frame)
    agg  = nan_dist_table(frame, [group_col], nan_frame=nan_frame)
    agg["custom_year"] = "Aggregate"
    long_full  = pd.concat([long, agg], ignore_index=True)
    year_order = VALID_YEARS + ["Aggregate"]
    pivot = long_full.pivot_table(
        index=group_col, columns="custom_year",
        values=["total_complaints", "nan_complaints", "nan_pct"],
        aggfunc="sum")
    pivot = pivot.swaplevel(0, 1, axis=1)
    pivot = pivot.reindex(
        columns=pd.MultiIndex.from_product(
            [year_order,
             ["total_complaints", "nan_complaints", "nan_pct"]]),
        fill_value=0)
    for col in pivot.columns:
        if col[1] == "nan_pct":
            pivot[col] = pivot[col].round(2)
        else:
            pivot[col] = pivot[col].fillna(0).astype(int)
    return long_full, pivot
 
 
def nan_dist_pivot(long_table, index_col, col_col,
                   values=("total_complaints", "nan_complaints", "nan_pct")):
    """Wide pivot of a nan_dist_table (for focus-year month tables)."""
    pivot = long_table.pivot_table(
        index=index_col, columns=col_col,
        values=list(values), aggfunc="sum")
    pivot = pivot.swaplevel(0, 1, axis=1).sort_index(axis=1)
    for col in pivot.columns:
        if col[1] == "nan_pct":
            pivot[col] = pivot[col].round(2)
        else:
            pivot[col] = pivot[col].fillna(0).astype(int)
    return pivot
 
 
# ----- per-capita ------------------------------------------------------------
 
def add_per_capita(table, pop_df, district_col="district",
                   count_cols=("total_complaints", "nan_complaints"),
                   pop_col="population_2021", scale=1000):
    """Merge population and add per-scale-population columns."""
    pop = pop_df[["district", pop_col]].copy()
    pop["district"] = pop["district"].astype(str).str.strip()
    out = table.copy()
    out[district_col] = out[district_col].astype(str).str.strip()
    out = out.merge(pop.rename(columns={"district": district_col}),
                    on=district_col, how="left")
    for col in count_cols:
        if col in out.columns:
            out[f"{col}_per_{scale}"] = (
                out[col] / out[pop_col] * scale).round(2)
    return out
 
 
def percapita_with_aggregate(frame, nan_frame, pop_df):
    """District per-capita NaN — all years + Aggregate pivot."""
    long, _ = nan_dist_with_aggregate(frame, "district",
                                      nan_frame=nan_frame)
    long_pc  = add_per_capita(long, pop_df,
                               count_cols=("total_complaints",
                                           "nan_complaints"))
    agg_pc   = (long_pc[long_pc["custom_year"] == "Aggregate"]
                .sort_values("total_complaints_per_1000",
                             ascending=False).reset_index(drop=True))
 
    pc_cols    = ["total_complaints", "nan_complaints", "nan_pct",
                  "total_complaints_per_1000", "nan_complaints_per_1000"]
    year_order = VALID_YEARS + ["Aggregate"]
    pc_pivot   = long_pc.pivot_table(
        index="district", columns="custom_year",
        values=[c for c in pc_cols if c in long_pc.columns],
        aggfunc="sum")
    pc_pivot = pc_pivot.swaplevel(0, 1, axis=1)
    pc_pivot = pc_pivot.reindex(
        columns=pd.MultiIndex.from_product(
            [year_order,
             [c for c in pc_cols if c in long_pc.columns]]),
        fill_value=0)
    for col in pc_pivot.columns:
        pc_pivot[col] = pc_pivot[col].round(2)
    return agg_pc, pc_pivot
 
 
# ----- concentration ---------------------------------------------------------
 
def concentration_table(frame, group_cols, label="count"):
    """Unique ticket count + share_pct by group_cols, sorted descending."""
    if isinstance(group_cols, str):
        group_cols = [group_cols]
    out = (frame.groupby(group_cols)["ticket_no"]
           .nunique().reset_index(name=label))
    total = out[label].sum()
    out["share_pct"] = (out[label] / total * 100).round(2) if total else 0.0
    return out.sort_values(label, ascending=False).reset_index(drop=True)
 
 
# ----- top-N ranking ---------------------------------------------------------
 
def top_n_within_group(frame, group_cols, count_col, n=5):
    """Keep top-n rows by count_col within each group.
    Adds rank and share_pct (within group) columns."""
    if isinstance(group_cols, str):
        group_cols = [group_cols]
    group_total = (frame.groupby(group_cols)[count_col].sum()
                   .reset_index(name="group_total"))
    out = frame.merge(group_total, on=group_cols, how="left")
    out["share_pct"] = (out[count_col] / out["group_total"] * 100).round(2)
    out["rank"] = (out.groupby(group_cols)[count_col]
                   .rank(method="first", ascending=False))
    return (out[out["rank"] <= n]
            .sort_values(group_cols + ["rank"])
            .assign(rank=lambda x: x["rank"].astype(int))
            .drop(columns="group_total")
            .reset_index(drop=True))
 
 
# ----- top-10 subcategory label pivot ----------------------------------------
 
def top10_subcat_pivot(frame, months, district=None):
    """Top-10 subcategories per month as 'subcat (count, share%)'."""
    d = frame.copy()
    d["year_month"]  = d["created_on"].dt.to_period("M").astype(str)
    d["subcategory"] = d["subcategory"].fillna("NaN").astype(str).str.strip()
    if district:
        d = d[d["district"] == district]
    d = d[d["year_month"].isin(months)]
    monthly_totals = (d.groupby("year_month")["ticket_no"]
                      .nunique().reset_index(name="monthly_total"))
    monthly_subcat = (d.groupby(["year_month", "subcategory"])["ticket_no"]
                      .nunique().reset_index(name="count"))
    monthly_subcat = monthly_subcat.merge(
        monthly_totals, on="year_month", how="left")
    monthly_subcat["share_pct"] = (
        monthly_subcat["count"] / monthly_subcat["monthly_total"] * 100
    ).round(0).astype(int)
    monthly_subcat["rank"] = (
        monthly_subcat.groupby("year_month")["count"]
        .rank(method="first", ascending=False))
    top10 = monthly_subcat[monthly_subcat["rank"] <= 10].copy()
    top10["label"] = (top10["subcategory"] + " ("
                      + top10["count"].astype(int).astype(str) + ", "
                      + top10["share_pct"].astype(str) + "%)")
    pivot = (top10.pivot(index="year_month", columns="rank", values="label")
                  .sort_index())
    pivot.columns = [f"Rank {int(c)}" for c in pivot.columns]
    return pivot.T.fillna("nan")
 
 
# ----- yearly subcat pivot ---------------------------------------------------
 
def yearly_subcat_pivot(frame, mask):
    """Subcategory x year count + pct pivot for a masked frame."""
    d = frame[mask].copy()
    d["subcategory"] = (d["subcategory"].fillna("NaN")
                        .astype(str).str.strip())
    yearly = (d.groupby(["subcategory", "custom_year"])["ticket_no"]
               .nunique().reset_index(name="count"))
    year_totals = d.groupby("custom_year")["ticket_no"].nunique()
    yearly["total_cases"] = yearly["custom_year"].map(year_totals)
    yearly["percentage"]  = (
        yearly["count"] / yearly["total_cases"] * 100).round(2)
    return (yearly.pivot(index="subcategory", columns="custom_year",
                         values=["count", "percentage"])
                  .swaplevel(0, 1, axis=1).sort_index(axis=1).fillna(0))

## Prepare NaN subsets

In [6]:
df_nan_all = df[nan_mask(df)].copy()
df_focus   = df[df["custom_year"] == FOCUS_YEAR].copy()
df_nan_fy  = df_focus[nan_mask(df_focus)].copy()
pop_df     = population_df()
 
print(f"NaN subcategory (all years): {df_nan_all['ticket_no'].nunique():,}")
print(f"NaN subcategory (focus yr) : {df_nan_fy['ticket_no'].nunique():,}")

NaN subcategory (all years): 197,952
NaN subcategory (focus yr) : 122,991

## 1. Monthly NaN Distribution (All Years)

Monthly counts: total complaints, NaN-subcategory complaints, and the NaN
share, for every month in the analysis window.

In [7]:
monthly_nan_dist = nan_dist_table(
    df, "year_month", nan_frame=df_nan_all
).sort_values("year_month").reset_index(drop=True)
display(monthly_nan_dist)

   year_month  total_complaints  nan_complaints  nan_pct
0     2021-07              4651              29     0.62
1     2021-08              6637              27     0.41
2     2021-09              7172              35     0.49
3     2021-10              7262              77     1.06
4     2021-11              8614            1404    16.30
5     2021-12              8158            1104    13.53
6     2022-01              6912            1006    14.55
7     2022-02              4189             655    15.64
8     2022-03              5854            1049    17.92
9     2022-04             10222            1694    16.57
10    2022-05             15274            2079    13.61
11    2022-06             13313            2008    15.08
12    2022-07             12361            1871    15.14
13    2022-08             11946            1935    16.20
14    2022-09             14681            2663    18.14
15    2022-10             13100            2480    18.93
16    2022-11             14566            1838    12.62
17    2022-12             14484            1869    12.90
18    2023-01             24588            3261    13.26
19    2023-02             19637            2967    15.11
20    2023-03             15791            2038    12.91
21    2023-04             13402            1921    14.33
22    2023-05             16527            2470    14.95
23    2023-06             10619            1752    16.50
24    2023-07             48122            3994     8.30
25    2023-08             40066            3433     8.57
26    2023-09             24902            3516    14.12
27    2023-10             16780            3143    18.73
28    2023-11             17176            2131    12.41
29    2023-12             17056            1830    10.73
30    2024-01             42243            2397     5.67
31    2024-02             46751            3482     7.45
32    2024-03             48952            4439     9.07
33    2024-04             20260            2980    14.71
34    2024-05             13356            2203    16.49
35    2024-06             19915            3181    15.97
36    2024-07             74377           12795    17.20
37    2024-08             66507            9722    14.62
38    2024-09             81691           15301    18.73
39    2024-10            135728           36357    26.79
40    2024-11             68306            9365    13.71
41    2024-12             49200            5465    11.11
42    2025-01             37559            7079    18.85
43    2025-02             32943            5635    17.11
44    2025-03             33493            5183    15.47
45    2025-04             32472            4556    14.03
46    2025-05             38701            5370    13.88
47    2025-06             37324            6163    16.51

## 2. Yearly NaN Distribution

In [8]:
yearly_nan_dist = nan_dist_table(
    df, "custom_year", nan_frame=df_nan_all
).sort_values("custom_year").reset_index(drop=True)
display(yearly_nan_dist)

  custom_year  total_complaints  nan_complaints  nan_pct
0   2021-2022             98258           11167    11.36
1   2022-2023            181702           27065    14.90
2   2023-2024            355579           36729    10.33
3   2024-2025            688301          122991    17.87

## 3. District NaN Distribution

District-level totals, NaN counts, and NaN share

In [9]:
district_nan_long, district_nan_pivot = nan_dist_with_aggregate(
    df, "district", nan_frame=df_nan_all)
 
print("District NaN — Focus Year (sorted by nan_pct):")
display(district_nan_long[district_nan_long["custom_year"] == FOCUS_YEAR]
        .sort_values("nan_pct", ascending=False).reset_index(drop=True))
 
print("\nDistrict NaN — All Years + Aggregate Pivot:")
display(district_nan_pivot)

District NaN — Focus Year (sorted by nan_pct):

          district custom_year  total_complaints  nan_complaints  nan_pct
0         Nayagarh   2024-2025             31527           16593    52.63
1        Sambalpur   2024-2025             48029           21199    44.14
2              NaN   2024-2025              2113             709    33.55
3        Dhenkanal   2024-2025             29370            7413    25.24
4         Rayagada   2024-2025              6840            1551    22.68
5         Balangir   2024-2025             27665            5567    20.12
6       Jharsuguda   2024-2025              5739            1105    19.25
7           Jajpur   2024-2025             37942            6772    17.85
8         Baleswar   2024-2025             34184            5761    16.85
9       Kendrapara   2024-2025             24823            3977    16.02
10       Kalahandi   2024-2025             28471            4011    14.09
11         Deogarh   2024-2025              7361            1021    13.87
12           Angul   2024-2025             20115            2785    13.85
13        Gajapati   2024-2025              8830            1217    13.78
14          Ganjam   2024-2025             52667            7251    13.77
15       Kendujhar   2024-2025             22756            3014    13.24
16     Nabarangpur   2024-2025             11654            1542    13.23
17           Boudh   2024-2025              7923            1043    13.16
18         Cuttack   2024-2025             37577            4828    12.85
19         Khordha   2024-2025             38293            4920    12.85
20         Bhadrak   2024-2025             37485            4630    12.35
21            Puri   2024-2025             27400            3230    11.79
22  Jagatsinghapur   2024-2025             21781            2453    11.26
23      Sundargarh   2024-2025             13309            1371    10.30
24      Subarnapur   2024-2025             15861            1554     9.80
25      Mayurbhanj   2024-2025             24974            2404     9.63
26         Koraput   2024-2025             10233             893     8.73
27         Bargarh   2024-2025             23559            1970     8.36
28      Malkangiri   2024-2025              6090             498     8.18
29       Kandhamal   2024-2025             11696             878     7.51
30         Nuapada   2024-2025             12034             831     6.91

District NaN — All Years + Aggregate Pivot:

                      2021-2022                               2022-2023  \
               total_complaints nan_complaints nan_pct total_complaints
district
Angul                      2759            422   15.30             3649
Balangir                   4094            370    9.04            12428
Baleswar                   7749           1054   13.60            15840
Bargarh                    3426            443   12.93             4521
Bhadrak                    4943            588   11.90             8312
Boudh                       778            180   23.14             4286
Cuttack                    4291            486   11.33             7592
Deogarh                     594             66   11.11              944
Dhenkanal                  4330            943   21.78             5855
Gajapati                   1424            105    7.37             3996
Ganjam                     5010            635   12.67            12624
Jagatsinghapur             3268            271    8.29             7979
Jajpur                     6042           1060   17.54             9885
Jharsuguda                  742            104   14.02             1284
Kalahandi                  9406            834    8.87            13137
Kandhamal                  2444            167    6.83             2362
Kendrapara                 4846            371    7.66             7673
Kendujhar                  2082            164    7.88             3939
Khordha                    8016            872   10.88            10198
Koraput                    1372            169   12.32             2223
Malkangiri                  472             69   14.62              494
Mayurbhanj                 2812            194    6.90             6826
NaN                        3872             44    1.14              599
Nabarangpur                1028            112   10.89             3319
Nayagarh                   2460            211    8.58             6446
Nuapada                    1249             83    6.65             3243
Puri                       3195            388   12.14             8542
Rayagada                   1171            135   11.53             2491
Sambalpur                  1573            235   14.94             2524
Subarnapur                 1260            153   12.14             2662
Sundargarh                 1550            239   15.42             5829

                                             2023-2024                         \
               nan_complaints nan_pct total_complaints nan_complaints nan_pct
district
Angul                     615   16.85             8703            963   11.07
Balangir                 1879   15.12            25275           2233    8.83
Baleswar                 3185   20.11            22134           3876   17.51
Bargarh                   684   15.13            10264            928    9.04
Bhadrak                  1148   13.81            14256           1646   11.55
Boudh                     577   13.46             4406            336    7.63
Cuttack                  1142   15.04            13828           1894   13.70
Deogarh                   110   11.65             3091            157    5.08
Dhenkanal                1941   33.15            15960           3504   21.95
Gajapati                  436   10.91             5938            346    5.83
Ganjam                   1961   15.53            24319           2584   10.63
Jagatsinghapur            501    6.28             8698            620    7.13
Jajpur                   2287   23.14            12807           1763   13.77
Jharsuguda                299   23.29             4347            569   13.09
Kalahandi                1314   10.00            22034           1312    5.95
Kandhamal                 148    6.27             5433            354    6.52
Kendrapara               1160   15.12             8292           1494   18.02
Kendujhar                 699   17.75            14757           1046    7.09
Khordha                  2025   19.86            16014           1908   11.91
Koraput                   392   17.63             6623            728   10.99
Malkangiri                 84   17.00             2067            153    7.40
Mayurbhanj                519    7.60            17889           1300    7.27
NaN                        99   16.53             1154            448   38.82
Nabarangpur               217    6.54             6251            739   11.82
Nayagarh                  834   12.94             8402            683    8.13
Nuapada                   200    6.17             8408            357    4.25
Puri                      881   10.31            11165           1145   10.26
Rayagada                  298   11.96             3934            782   19.88
Sambalpur                 438   17.35            22721            982    4.32
Subarnapur                281   10.56             5080            548   10.79
Sundargarh                711   12.20            21329           1331    6.24

                      2024-2025                               Aggregate  \
               total_complaints nan_complaints nan_pct total_complaints
district
Angul                     20115           2785   13.85            35226
Balangir                  27665           5567   20.12            69462
Baleswar                  34184           5761   16.85            79907
Bargarh                   23559           1970    8.36            41770
Bhadrak                   37485           4630   12.35            64996
Boudh                      7923           1043   13.16            17393
Cuttack                   37577           4828   12.85            63288
Deogarh                    7361           1021   13.87            11990
Dhenkanal                 29370           7413   25.24            55515
Gajapati                   8830           1217   13.78            20188
Ganjam                    52667           7251   13.77            94620
Jagatsinghapur            21781           2453   11.26            41726
Jajpur                    37942           6772   17.85            66676
Jharsuguda                 5739           1105   19.25            12112
Kalahandi                 28471           4011   14.09            73048
Kandhamal                 11696            878    7.51            21935
Kendrapara                24823           3977   16.02            45634
Kendujhar                 22756           3014   13.24            43534
Khordha                   38293           4920   12.85            72521
Koraput                   10233            893    8.73            20451
Malkangiri                 6090            498    8.18             9123
Mayurbhanj                24974           2404    9.63            52501
NaN                        2113            709   33.55             7738
Nabarangpur               11654           1542   13.23            22252
Nayagarh                  31527          16593   52.63            48835
Nuapada                   12034            831    6.91            24934
Puri                      27400           3230   11.79            50302
Rayagada                   6840           1551   22.68            14436
Sambalpur                 48029          21199   44.14            74847
Subarnapur                15861           1554    9.80            24863
Sundargarh                13309           1371   10.30            42017


               nan_complaints nan_pct
district
Angul                    4785   13.58
Balangir                10049   14.47
Baleswar                13876   17.37
Bargarh                  4025    9.64
Bhadrak                  8012   12.33
Boudh                    2136   12.28
Cuttack                  8350   13.19
Deogarh                  1354   11.29
Dhenkanal               13801   24.86
Gajapati                 2104   10.42
Ganjam                  12431   13.14
Jagatsinghapur           3845    9.21
Jajpur                  11882   17.82
Jharsuguda               2077   17.15
Kalahandi                7471   10.23
Kandhamal                1547    7.05
Kendrapara               7002   15.34
Kendujhar                4923   11.31
Khordha                  9725   13.41
Koraput                  2182   10.67
Malkangiri                804    8.81
Mayurbhanj               4417    8.41
NaN                      1300   16.80
Nabarangpur              2610   11.73
Nayagarh                18321   37.52
Nuapada                  1471    5.90
Puri                     5644   11.22
Rayagada                 2766   19.16
Sambalpur               22854   30.53
Subarnapur               2536   10.20
Sundargarh               3652    8.69

## 4. District Per-Capita NaN

In [11]:
district_pc_agg, district_pc_pivot = percapita_with_aggregate(
    df, df_nan_all, pop_df)
 
print("\nDistrict Per-Capita NaN — All Years + Aggregate Pivot:")
display(district_pc_pivot)

District Per-Capita NaN — All Years + Aggregate Pivot:

                      2021-2022                         \
               total_complaints nan_complaints nan_pct
district
Angul                      2759            422   15.30
Balangir                   4094            370    9.04
Baleswar                   7749           1054   13.60
Bargarh                    3426            443   12.93
Bhadrak                    4943            588   11.90
Boudh                       778            180   23.14
Cuttack                    4291            486   11.33
Deogarh                     594             66   11.11
Dhenkanal                  4330            943   21.78
Gajapati                   1424            105    7.37
Ganjam                     5010            635   12.67
Jagatsinghapur             3268            271    8.29
Jajpur                     6042           1060   17.54
Jharsuguda                  742            104   14.02
Kalahandi                  9406            834    8.87
Kandhamal                  2444            167    6.83
Kendrapara                 4846            371    7.66
Kendujhar                  2082            164    7.88
Khordha                    8016            872   10.88
Koraput                    1372            169   12.32
Malkangiri                  472             69   14.62
Mayurbhanj                 2812            194    6.90
NaN                        3872             44    1.14
Nabarangpur                1028            112   10.89
Nayagarh                   2460            211    8.58
Nuapada                    1249             83    6.65
Puri                       3195            388   12.14
Rayagada                   1171            135   11.53
Sambalpur                  1573            235   14.94
Subarnapur                 1260            153   12.14
Sundargarh                 1550            239   15.42

                                                                  \
               total_complaints_per_1000 nan_complaints_per_1000
district
Angul                               1.98                    0.30
Balangir                            2.32                    0.21
Baleswar                            3.01                    0.41
Bargarh                             2.22                    0.29
Bhadrak                             2.95                    0.35
Boudh                               1.59                    0.37
Cuttack                             1.53                    0.17
Deogarh                             1.74                    0.19
Dhenkanal                           3.43                    0.75
Gajapati                            2.31                    0.17
Ganjam                              1.31                    0.17
Jagatsinghapur                      2.75                    0.23
Jajpur                              3.03                    0.53
Jharsuguda                          1.19                    0.17
Kalahandi                           5.37                    0.48
Kandhamal                           3.03                    0.21
Kendrapara                          3.18                    0.24
Kendujhar                           1.05                    0.08
Khordha                             3.08                    0.34
Koraput                             0.91                    0.11
Malkangiri                          0.68                    0.10
Mayurbhanj                          1.02                    0.07
NaN                                 0.00                    0.00
Nabarangpur                         0.74                    0.08
Nayagarh                            2.46                    0.21
Nuapada                             1.91                    0.13
Puri                                1.74                    0.21
Rayagada                            1.10                    0.13
Sambalpur                           1.40                    0.21
Subarnapur                          1.94                    0.24
Sundargarh                          0.68                    0.10

                      2022-2023                         \
               total_complaints nan_complaints nan_pct
district
Angul                      3649            615   16.85
Balangir                  12428           1879   15.12
Baleswar                  15840           3185   20.11
Bargarh                    4521            684   15.13
Bhadrak                    8312           1148   13.81
Boudh                      4286            577   13.46
Cuttack                    7592           1142   15.04
Deogarh                     944            110   11.65
Dhenkanal                  5855           1941   33.15
Gajapati                   3996            436   10.91
Ganjam                    12624           1961   15.53
Jagatsinghapur             7979            501    6.28
Jajpur                     9885           2287   23.14
Jharsuguda                 1284            299   23.29
Kalahandi                 13137           1314   10.00
Kandhamal                  2362            148    6.27
Kendrapara                 7673           1160   15.12
Kendujhar                  3939            699   17.75
Khordha                   10198           2025   19.86
Koraput                    2223            392   17.63
Malkangiri                  494             84   17.00
Mayurbhanj                 6826            519    7.60
NaN                         599             99   16.53
Nabarangpur                3319            217    6.54
Nayagarh                   6446            834   12.94
Nuapada                    3243            200    6.17
Puri                       8542            881   10.31
Rayagada                   2491            298   11.96
Sambalpur                  2524            438   17.35
Subarnapur                 2662            281   10.56
Sundargarh                 5829            711   12.20

                                                                  ...  \
               total_complaints_per_1000 nan_complaints_per_1000  ...
district                                                          ...
Angul                               2.61                    0.44  ...
Balangir                            7.05                    1.07  ...
Baleswar                            6.15                    1.24  ...
Bargarh                             2.92                    0.44  ...
Bhadrak                             4.97                    0.69  ...
Boudh                               8.76                    1.18  ...
Cuttack                             2.71                    0.41  ...
Deogarh                             2.76                    0.32  ...
Dhenkanal                           4.64                    1.54  ...
Gajapati                            6.49                    0.71  ...
Ganjam                              3.30                    0.51  ...
Jagatsinghapur                      6.71                    0.42  ...
Jajpur                              4.96                    1.15  ...
Jharsuguda                          2.06                    0.48  ...
Kalahandi                           7.49                    0.75  ...
Kandhamal                           2.93                    0.18  ...
Kendrapara                          5.03                    0.76  ...
Kendujhar                           1.99                    0.35  ...
Khordha                             3.92                    0.78  ...
Koraput                             1.48                    0.26  ...
Malkangiri                          0.71                    0.12  ...
Mayurbhanj                          2.47                    0.19  ...
NaN                                 0.00                    0.00  ...
Nabarangpur                         2.40                    0.16  ...
Nayagarh                            6.43                    0.83  ...
Nuapada                             4.96                    0.31  ...
Puri                                4.66                    0.48  ...
Rayagada                            2.35                    0.28  ...
Sambalpur                           2.25                    0.39  ...
Subarnapur                          4.09                    0.43  ...
Sundargarh                          2.55                    0.31  ...

                      2024-2025                         \
               total_complaints nan_complaints nan_pct
district
Angul                     20115           2785   13.85
Balangir                  27665           5567   20.12
Baleswar                  34184           5761   16.85
Bargarh                   23559           1970    8.36
Bhadrak                   37485           4630   12.35
Boudh                      7923           1043   13.16
Cuttack                   37577           4828   12.85
Deogarh                    7361           1021   13.87
Dhenkanal                 29370           7413   25.24
Gajapati                   8830           1217   13.78
Ganjam                    52667           7251   13.77
Jagatsinghapur            21781           2453   11.26
Jajpur                    37942           6772   17.85
Jharsuguda                 5739           1105   19.25
Kalahandi                 28471           4011   14.09
Kandhamal                 11696            878    7.51
Kendrapara                24823           3977   16.02
Kendujhar                 22756           3014   13.24
Khordha                   38293           4920   12.85
Koraput                   10233            893    8.73
Malkangiri                 6090            498    8.18
Mayurbhanj                24974           2404    9.63
NaN                        2113            709   33.55
Nabarangpur               11654           1542   13.23
Nayagarh                  31527          16593   52.63
Nuapada                   12034            831    6.91
Puri                      27400           3230   11.79
Rayagada                   6840           1551   22.68
Sambalpur                 48029          21199   44.14
Subarnapur                15861           1554    9.80
Sundargarh                13309           1371   10.30

                                                                  \
               total_complaints_per_1000 nan_complaints_per_1000
district
Angul                              14.41                    1.99
Balangir                           15.69                    3.16
Baleswar                           13.28                    2.24
Bargarh                            15.24                    1.27
Bhadrak                            22.39                    2.77
Boudh                              16.20                    2.13
Cuttack                            13.41                    1.72
Deogarh                            21.52                    2.99
Dhenkanal                          23.29                    5.88
Gajapati                           14.33                    1.98
Ganjam                             13.75                    1.89
Jagatsinghapur                     18.32                    2.06
Jajpur                             19.06                    3.40
Jharsuguda                          9.23                    1.78
Kalahandi                          16.24                    2.29
Kandhamal                          14.49                    1.09
Kendrapara                         16.29                    2.61
Kendujhar                          11.52                    1.53
Khordha                            14.73                    1.89
Koraput                             6.82                    0.59
Malkangiri                          8.80                    0.72
Mayurbhanj                          9.04                    0.87
NaN                                 0.00                    0.00
Nabarangpur                         8.43                    1.12
Nayagarh                           31.46                   16.56
Nuapada                            18.40                    1.27
Puri                               14.96                    1.76
Rayagada                            6.44                    1.46
Sambalpur                          42.88                   18.93
Subarnapur                         24.36                    2.39
Sundargarh                          5.83                    0.60

                      Aggregate                         \
               total_complaints nan_complaints nan_pct
district
Angul                     35226           4785   13.58
Balangir                  69462          10049   14.47
Baleswar                  79907          13876   17.37
Bargarh                   41770           4025    9.64
Bhadrak                   64996           8012   12.33
Boudh                     17393           2136   12.28
Cuttack                   63288           8350   13.19
Deogarh                   11990           1354   11.29
Dhenkanal                 55515          13801   24.86
Gajapati                  20188           2104   10.42
Ganjam                    94620          12431   13.14
Jagatsinghapur            41726           3845    9.21
Jajpur                    66676          11882   17.82
Jharsuguda                12112           2077   17.15
Kalahandi                 73048           7471   10.23
Kandhamal                 21935           1547    7.05
Kendrapara                45634           7002   15.34
Kendujhar                 43534           4923   11.31
Khordha                   72521           9725   13.41
Koraput                   20451           2182   10.67
Malkangiri                 9123            804    8.81
Mayurbhanj                52501           4417    8.41
NaN                        7738           1300   16.80
Nabarangpur               22252           2610   11.73
Nayagarh                  48835          18321   37.52
Nuapada                   24934           1471    5.90
Puri                      50302           5644   11.22
Rayagada                  14436           2766   19.16
Sambalpur                 74847          22854   30.53
Subarnapur                24863           2536   10.20
Sundargarh                42017           3652    8.69


               total_complaints_per_1000 nan_complaints_per_1000
district
Angul                              25.23                    3.43
Balangir                           39.40                    5.70
Baleswar                           31.04                    5.39
Bargarh                            27.02                    2.60
Bhadrak                            38.83                    4.79
Boudh                              35.57                    4.37
Cuttack                            22.58                    2.98
Deogarh                            35.06                    3.96
Dhenkanal                          44.02                   10.94
Gajapati                           32.77                    3.42
Ganjam                             24.71                    3.25
Jagatsinghapur                     35.09                    3.23
Jajpur                             33.49                    5.97
Jharsuguda                         19.47                    3.34
Kalahandi                          41.67                    4.26
Kandhamal                          27.18                    1.92
Kendrapara                         29.94                    4.59
Kendujhar                          22.04                    2.49
Khordha                            27.89                    3.74
Koraput                            13.62                    1.45
Malkangiri                         13.18                    1.16
Mayurbhanj                         18.99                    1.60
NaN                                 0.00                    0.00
Nabarangpur                        16.10                    1.89
Nayagarh                           48.74                   18.28
Nuapada                            38.13                    2.25
Puri                               27.46                    3.08
Rayagada                           13.59                    2.60
Sambalpur                          66.83                   20.41
Subarnapur                         38.19                    3.90
Sundargarh                         18.41                    1.60

[31 rows x 25 columns]

## 5. District x Month NaN Distribution (2024-25)

Long and wide views of NaN share by district and month within the focus
year.

In [14]:
district_month_nan_dist = nan_dist_table(
    df_focus, ["year_month", "district"], nan_frame=df_nan_fy
).sort_values(["year_month", "nan_pct"],
              ascending=[True, False]).reset_index(drop=True)
 
pivot = nan_dist_pivot(district_month_nan_dist, "district", "year_month")
display(pivot)

year_month            2024-07                                 2024-08          \
               nan_complaints nan_pct total_complaints nan_complaints nan_pct
district
Angul                     261   12.97             2013            209   12.68
Balangir                 1299   19.52             6656            980   21.72
Baleswar                  595   14.13             4212            244    7.29
Bargarh                   314   13.94             2252            140    6.94
Bhadrak                   440   10.95             4020            220    5.66
Boudh                     153   19.29              793             51    9.11
Cuttack                   639   17.52             3648            505   14.20
Deogarh                    52    9.92              524             28    3.05
Dhenkanal                 427   13.92             3067            176    7.04
Gajapati                  147   27.84              528             69    8.78
Ganjam                    868   18.04             4812            587   12.86
Jagatsinghapur            127    8.77             1448             88    6.61
Jajpur                    643   24.95             2577            405   15.91
Jharsuguda                167   25.57              653             66   13.72
Kalahandi                 966   17.75             5441            552   11.46
Kandhamal                  99    7.01             1413             80    6.32
Kendrapara                481   18.17             2647            557   25.19
Kendujhar                 430   17.44             2465            140    8.04
Khordha                   658   16.13             4080            411   11.54
Koraput                   124    8.82             1406             81    4.86
Malkangiri                 57   13.60              419             40   13.47
Mayurbhanj                488   14.77             3304            228    9.74
NaN                        47   28.66              164             22   17.19
Nabarangpur               242   18.86             1283            111    8.14
Nayagarh                  354   19.30             1834            354   27.06
Nuapada                   162   12.16             1332             39    3.41
Puri                      334   15.82             2111            222    9.40
Rayagada                  227   27.28              832            131   23.48
Sambalpur                1673   30.06             5566           2816   39.77
Subarnapur                106    9.84             1077             38    5.13
Sundargarh                215   11.94             1800            132   10.38

year_month                             2024-09                           \
               total_complaints nan_complaints nan_pct total_complaints
district
Angul                      1648            262   10.51             2492
Balangir                   4513            634   17.76             3570
Baleswar                   3349            591   15.21             3886
Bargarh                    2016            200    5.77             3466
Bhadrak                    3885            443   10.26             4318
Boudh                       560             80   13.58              589
Cuttack                    3556            478   12.18             3926
Deogarh                     917             70    6.86             1021
Dhenkanal                  2500           1037   29.71             3490
Gajapati                    786            138   14.65              942
Ganjam                     4564            894   16.58             5392
Jagatsinghapur             1331            136    9.04             1505
Jajpur                     2545           1350   30.16             4476
Jharsuguda                  481            178   21.42              831
Kalahandi                  4817            626   13.92             4498
Kandhamal                  1265            134    7.06             1899
Kendrapara                 2211            358   15.92             2249
Kendujhar                  1741            296   10.88             2720
Khordha                    3561            436   12.80             3405
Koraput                    1666            123   11.08             1110
Malkangiri                  297             41   12.13              338
Mayurbhanj                 2340            253    8.64             2928
NaN                         128             47   30.32              155
Nabarangpur                1364            224   10.69             2095
Nayagarh                   1308            714   37.03             1928
Nuapada                    1145             89    6.33             1407
Puri                       2362            353   10.53             3352
Rayagada                    558            193   26.73              722
Sambalpur                  7080           4562   48.58             9390
Subarnapur                  741            217    9.02             2406
Sundargarh                 1272            144   12.15             1185

year_month            2024-10  ...          2025-03        2025-04          \
               nan_complaints  ... total_complaints nan_complaints nan_pct
district                       ...
Angul                     908  ...             1073            104   14.55
Balangir                 1705  ...              640             93   10.71
Baleswar                 1952  ...             1537            267   17.80
Bargarh                   546  ...              779            131   11.40
Bhadrak                  2106  ...             1454            199   13.43
Boudh                     446  ...              335             23    6.63
Cuttack                  1306  ...             2200            292   14.55
Deogarh                   642  ...              263             22    6.16
Dhenkanal                3775  ...             1292            140   12.61
Gajapati                  556  ...              641             23    5.58
Ganjam                   1772  ...             2458            127    6.49
Jagatsinghapur            496  ...             1240            157   11.04
Jajpur                   2779  ...             1959            101    6.40
Jharsuguda                390  ...              253             51   11.46
Kalahandi                1046  ...              909             68    5.81
Kandhamal                 282  ...              522             19    3.76
Kendrapara                997  ...             1317            114   11.41
Kendujhar                1093  ...             1208            114    9.79
Khordha                   895  ...             2943            258   11.24
Koraput                   236  ...              475             16    3.40
Malkangiri                 98  ...              282             13    2.88
Mayurbhanj                655  ...             1227             77    6.89
NaN                        48  ...              118             15    9.04
Nabarangpur               592  ...              351             33    7.55
Nayagarh                 1789  ...             3466           1572   60.18
Nuapada                   262  ...              546             28    8.95
Puri                      889  ...             1506            114    8.89
Rayagada                  403  ...              329             30    8.88
Sambalpur                6754  ...              635            228   12.37
Subarnapur                714  ...              718             48    3.85
Sundargarh                225  ...              817             79   11.11

year_month                             2025-05                           \
               total_complaints nan_complaints nan_pct total_complaints
district
Angul                       715            141   16.57              851
Balangir                    868             78    8.25              946
Baleswar                   1500            224   14.12             1586
Bargarh                    1149            147    5.67             2593
Bhadrak                    1482            232   13.44             1726
Boudh                       347             62   11.74              528
Cuttack                    2007            203    7.78             2609
Deogarh                     357             53   14.93              355
Dhenkanal                  1110            124   11.01             1126
Gajapati                    412             30    7.25              414
Ganjam                     1956            393   14.12             2784
Jagatsinghapur             1422            109    8.34             1307
Jajpur                     1579             91    5.06             1800
Jharsuguda                  445             44   12.05              365
Kalahandi                  1170             52    4.83             1076
Kandhamal                   505             28    4.67              599
Kendrapara                  999            181   11.15             1624
Kendujhar                  1164            185   15.08             1227
Khordha                    2295            318   12.95             2456
Koraput                     471             47    8.61              546
Malkangiri                  451             19    1.70             1119
Mayurbhanj                 1118            111   10.25             1083
NaN                         166            403   74.08              544
Nabarangpur                 437             53   16.06              330
Nayagarh                   2612           1533   57.46             2668
Nuapada                     313             19    3.70              513
Puri                       1282            167   12.61             1324
Rayagada                    338             41   11.85              346
Sambalpur                  1843             96    5.76             1666
Subarnapur                 1248             91    5.43             1676
Sundargarh                  711             95   10.39              914

year_month            2025-06
               nan_complaints nan_pct total_complaints
district
Angul                     102   11.83              862
Balangir                  100    8.45             1183
Baleswar                  239   16.45             1453
Bargarh                   229    7.63             3003
Bhadrak                   148    8.88             1667
Boudh                      37    6.73              550
Cuttack                   288   12.37             2329
Deogarh                     9    2.89              311
Dhenkanal                 139   12.99             1070
Gajapati                   24    6.20              387
Ganjam                    335   13.16             2545
Jagatsinghapur            103    7.29             1413
Jajpur                    116    8.55             1357
Jharsuguda                 32    8.82              363
Kalahandi                  96    8.18             1173
Kandhamal                  41    5.57              736
Kendrapara                165   13.80             1196
Kendujhar                 123    9.56             1287
Khordha                   298   11.01             2707
Koraput                    37    6.26              591
Malkangiri                146   20.83              701
Mayurbhanj                103    8.80             1171
NaN                        31   29.52              105
Nabarangpur                39   10.74              363
Nayagarh                 2654   66.43             3995
Nuapada                    21    4.68              449
Puri                      158   11.88             1330
Rayagada                   25    8.36              299
Sambalpur                  97   11.24              863
Subarnapur                126   12.61              999
Sundargarh                102   11.78              866

[31 rows x 36 columns]

## 6. District x Block Concentration (2024-25)

Where the NaN-subcategory complaints concentrate by district and block.

In [16]:
block_dist = concentration_table(
    df_nan_fy, ["district", "block"], label="count")
display(block_dist.head(30))

          district            block  count  share_pct
0        Sambalpur         Kuchinda  19815      16.11
1         Nayagarh          Odagaon  12773      10.39
2           Jajpur           Jajpur   1322       1.07
3        Dhenkanal          Parjang   1233       1.00
4           Jajpur             Bari   1187       0.97
5          Cuttack     Narasinghpur   1183       0.96
6        Dhenkanal           Hindol   1101       0.90
7        Dhenkanal    Kamakhyanagar   1068       0.87
8          Khordha   Bhubaneswar mc   1016       0.83
9        Dhenkanal          Odapada    993       0.81
10          Jajpur       Binjharpur    980       0.80
11       Dhenkanal  Dhenkanal sadar    930       0.76
12         Bhadrak       Chandabali    872       0.71
13        Nayagarh         Nayagarh    857       0.70
14  Jagatsinghapur           Biridi    827       0.67
15       Dhenkanal           Gondia    804       0.65
16          Ganjam          Polsara    787       0.64
17        Baleswar           Khaira    768       0.62
18         Bhadrak           Tihidi    739       0.60
19         Bhadrak          Bhadrak    732       0.60
20         Khordha          Chilika    718       0.58
21         Khordha      Bhubaneswar    715       0.58
22      Kendrapara              Aul    714       0.58
23             NaN              NaN    705       0.57
24            Puri       Brahmagiri    654       0.53
25        Baleswar         Bahanaga    638       0.52
26       Kalahandi            Narla    621       0.50
27           Angul            Angul    618       0.50
28       Dhenkanal       Kankadahad    610       0.50
29          Jajpur            Korei    607       0.49

## 7. Petitioner Concentration (2024-25)

Which petitioners (name x district x block) file the most NaN complaints.

In [17]:
if "petitioner_name" in df_nan_fy.columns:
    petitioner_dist = concentration_table(
        df_nan_fy, ["district", "block", "petitioner_name"], label="count")
    display(petitioner_dist.head(30))
else:
    petitioner_dist = pd.DataFrame()
    print("petitioner_name not present; skipping.")

,district,block,petitioner_name,count,share_pct
0,Sambalpur,Kuchinda,Samir Nayak,19599,15.94
1,Nayagarh,Odagaon,ପବିତ୍ର କୁମାର ଦାଶ,9835,8.00
2,Nayagarh,Odagaon,PABITRA KUMAR DASH,1540,1.25
3,Jagatsinghapur,Biridi,SWADHIN RANJAN DAS,751,0.61
4,Baleswar,Bahanaga,Rajeev Kumar Tiwari,327,0.27
5,Bhadrak,Chandabali,Suresh Chandra Nayak,314,0.26
6,Kendrapara,Aul,Sunakar Sahoo,280,0.23
7,NaN,NaN,mENtor pAWan,253,0.21
8,Kendrapara,Mahakalpara,Sarbeswar Bai,180,0.15
9,NaN,NaN,ପବିତ୍ର କୁମାର ଦାଶ,147,0.12
10,Khordha,Chilika,Pramila Tarai,138,0.11
11,Kendrapara,Garadpur,Damodar sahoo,130,0.11
12,Angul,Angul,Test,115,0.09
13,Kalahandi,Narla,bhama gouda,104,0.08
14,Jagatsinghapur,Balikuda,Manoj Nayak,104,0.08
15,Sambalpur,Kuchinda,Rina Nayak,96,0.08
16,Khordha,Chilika,Sasmita Tarai,90,0.07
17,Ganjam,Buguda nac,PRAVATI KUMARI MISHRA,88,0.07
18,Kendrapara,Rajnagar,Jagabandhu mandl,86,0.07
19,Kalahandi,Koksara,ପ୍ରଧାନି ବାଗ,83,0.07
20,Jajpur,Jajpur,Smita Rani mohanty,78,0.06
21,Angul,Chhendipada,Pratap Bhutia,76,0.06
22,Jajpur,Dharmasala,Satish Biswal,73,0.06
23,Nabarangpur,Umerkote,Bikash Goldar S/o Sisu Goldar U v 52mixfarm,70,0.06
24,Ganjam,Digapahandi,Narayana gouda,62,0.05
25,Nabarangpur,Umerkote,Bikash goldar,61,0.05
26,Cuttack,Cuttack mc,Advocates` Chamber,59,0.05
27,Dhenkanal,Kamakhyanagar,RAKESH NAYAK,56,0.05
28,Jajpur,Jajpur,Smitarani mohanty,52,0.04
29,Angul,Angul,Ashok kumar prusty,51,0.04

## 8. Sambalpur Top-10 Subcategories during the NaN Spike

The original analysis flagged a NaN spike in Sambalpur during June-October
2024. Below: each month's top-10 subcategories formatted as
"subcategory (count, share%)".

In [19]:
MONTHS_SPIKE  = ["2024-06", "2024-07", "2024-08", "2024-09", "2024-10"]
pivot_top10_T = top10_subcat_pivot(df, MONTHS_SPIKE, district="Sambalpur")
display(pivot_top10_T)

year_month,2024-06,2024-07,2024-08,2024-09,2024-10
Rank 1,"IAY/MKY/BPGY/PMAY (594, 50%)","NaN (1673, 30%)","NaN (2816, 40%)","NaN (4562, 49%)","NaN (6754, 62%)"
Rank 2,"Rural Housing (258, 22%)","IAY/MKY/BPGY/PMAY (1338, 24%)","Allegation/Corruption (2004, 28%)","Allegation/Corruption (1329, 14%)","Allegation/Corruption (1449, 13%)"
Rank 3,"NaN (70, 6%)","Allegation/Corruption (1010, 18%)","IAY/MKY/BPGY/PMAY (910, 13%)","Others (782, 8%)","IAY/MKY/BPGY/PMAY (1077, 10%)"
Rank 4,"Others (58, 5%)","Others (525, 9%)","Others (595, 8%)","Illegal Activities (612, 7%)","Rural Housing (611, 6%)"
Rank 5,"Allegation/Corruption (47, 4%)","Rural Housing (277, 5%)","Miscellaneous/Others (110, 2%)","IAY/MKY/BPGY/PMAY (609, 6%)","Others (303, 3%)"
Rank 6,"Miscellaneous/Others (26, 2%)","Miscellaneous/Others (139, 2%)","Rural Housing (99, 1%)","Rural Housing (502, 5%)","Miscellaneous/Others (283, 3%)"
Rank 7,"Service Matters (14, 1%)","Ration Card Issue (51, 1%)","Illegal Activities (90, 1%)","Miscellaneous/Others (336, 4%)","Police Cases (35, 0%)"
Rank 8,"OAP/ODP/MBPY/WP (11, 1%)","Road (48, 1%)","Ration Card Issue (51, 1%)","Higher Education (205, 2%)","Road (34, 0%)"
Rank 9,"Water Supply issue (8, 1%)","OAP/ODP/MBPY/WP (41, 1%)","Road (51, 1%)","Police Cases (47, 1%)","Ration Card Issue (25, 0%)"
Rank 10,"Land Allotment/Settlement/RoR (7, 1%)","Service Matters (29, 1%)","Land Allotment/Settlement/RoR (34, 0%)","Employment/Recruitment (36, 0%)","Land Allotment/Settlement/RoR (18, 0%)"

## 9. NaN Subcategory Rank and Yearly Pivot

In [20]:
cat_nan_mask = df["category"].isna() | (
    df["category"].astype(str).str.strip().isin(["", "NaN"]))
 
rank_subcat_nan = (
    concentration_table(df[cat_nan_mask], "subcategory", label="count")
    .rename(columns={"count": "count", "share_pct": "share_pct"}))
display(rank_subcat_nan.head(30))
 
pivot_nan = yearly_subcat_pivot(df, cat_nan_mask)
display(pivot_nan.head(30))

          subcategory   count  share_pct
0                 NaN  197936      90.89
1      Excise Matters   19792       9.09
2  Water Supply issue      37       0.02
3  Test Sub  Category       1       0.00

custom_year        2021-2022            2022-2023            2023-2024  \
                       count percentage     count percentage     count
subcategory
Excise Matters       19792.0      63.89       0.0       0.00       0.0
NaN                  11156.0      36.01   27060.0      99.98   36729.0
Test Sub  Category       0.0       0.00       1.0       0.00       0.0
Water Supply issue      32.0       0.10       4.0       0.01       1.0

custom_year                   2024-2025
                   percentage     count percentage
subcategory
Excise Matters            0.0       0.0        0.0
NaN                     100.0  122991.0      100.0
Test Sub  Category        0.0       0.0        0.0
Water Supply issue        0.0       0.0        0.0